### ISSUE TITLE
Grid does not fire bbGridMultiselectSelectedIdsChanged when using deselect all

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#1000]
### Expected behavior
If you click the checkbox at the top of a multi-select grid to deselect all rows, it should fire the bbGridMultiselectSelectedIdsChanged event.

### Actual behavior
The bbGridMultiselectSelectedIdsChanged event is not fired.  It is fired when selecting or deselecting individual rows, as well as when using the checkbox at the top to select all.  It does not fire when using it to deselect all

### Steps to reproduce
Go to http://skyux.developer.blackbaud.com/components/grids/ and scroll down to the "Grid with vertical scrolling" example.  Click the "select all" check box and see the summary action bar appears.  Click it again to deselect all and see the summary action bar does not go away.  The root cause is the event is not fired.

**Comment by Blackbaud-PatrickOFriel** [comment]
Good catch, we had a test that was checking the result array, but it was passing because the reference was being updated, not the even emitting.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.13.7](https://github.com/blackbaud/skyux/releases/tag/v1.13.7)
