### ISSUE TITLE
Sectioned form tab headers always have scroll bar

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#1005]
### Expected behavior
There should not be a scroll bar for the sectioned form tabs (on the left), especailly when using short tab names.

### Actual behavior
The scroll bar is always present

### Steps to reproduce
See sectioned form example. http://skyux.developer.blackbaud.com/components/sectionedform/

**Comment by Blackbaud-PatrickOFriel** [comment]
Looks like we should change `bb-sectionedform` class to have display: flex. and remove the 25% width and float left from the left side tab header container.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.13.9](https://github.com/blackbaud/skyux/releases/tag/v1.13.9)
