### ISSUE TITLE
Sectioned form styling updates

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#1010]
Add 10px left margin to the section tab list, so that the background of the selected item is not right up against the edge of the modal.
Label on the selected tab should be semibold weight. 
Labels on unselected tabs should be color #707374

Designers: @Blackbaud-Robfavre @Blackbaud-TimHammond

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-MatthewBell if don't want to take this one just let me know and we can grab it.

**Comment by Blackbaud-MatthewBell** [comment]
I'd say go ahead and grab it if you don't mind.

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ToddRoberts @Blackbaud-Robfavre @Blackbaud-TimHammond what's the exact font-weight for 'semi-bold' is that a variable we have defined?

**Comment by Blackbaud-TimHammond** [comment]
We have a class for emphasized body copy here: http://skyux.developer.blackbaud.com/design/typography/

`<div class="bb-emphasized">Emphasized body copy</div>`

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.15.0](https://github.com/blackbaud/skyux/releases/tag/v1.15.0)
