### ISSUE TITLE
Search component needs a way to define an ID for the input box

### ISSUE THREAD

**Issue by Blackbaud-KevinEnns** [blackbaud/skyux1#1011]
### Expected behavior
When the bb-search-input component is added, the generated input box would contain an ID

### Actual behavior
There is no ID on the generated input box from bb-search-input

### Steps to reproduce
Add a bb-search-input component to a page and inspect the result

### Plunker
n/a

It would be best if an ID could be specified as a parameter to the bb-search-input component. 

The necessity for this is that the Bing maps API requires an ID for the AutoSuggest to bind to the Input.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.15.0](https://github.com/blackbaud/skyux/releases/tag/v1.15.0)
