### ISSUE TITLE
After clearing the search text resetting the search text on search component will not display text if it matches the previous value.

### ISSUE THREAD

**Issue by MikeABentley** [blackbaud/skyux1#1017]
### Expected behavior
Setting the search text will always set it

### Actual behavior
If the text matches the previous value it will not set it

### Steps to reproduce
Click on the Predefined search text (Robert) button
Note that the search text is set to Robert
Highlight the text and delete it
Click on the Predefined search text (Robert) button a few times for funsies
Note that the text is not set
Click on the Predefined search text (Hernandez) button
Note that the search text is set to Hernandez
Highlight the text and delete it
Click on the Predefined search text (Robert) button
Note that the search text is set to Robert

### Plunker
http://plnkr.co/edit/mLIrKohOFqvWWhZfbzPu?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
This is expected because this control only uses one way binding, so it only updates when searchText variable is actually changed. To keep searchText up to date when the text in the input changes (not just when it's applied), do something like this: http://plnkr.co/edit/mLIrKohOFqvWWhZfbzPu?p=preview

**Comment by MikeABentley** [comment]
Um, your example still doesn't work.  If the user manually changes the search text then the control should keep track of the change.  Once the user clears it and sets searchText = "" programatically setting searchText="foo" should update the control. 

I forgot to mention that this works properly if the user uses the X button to clear the text.

**Comment by Blackbaud-PatrickOFriel** [comment]
Sorry plunker didnt save, I swear it works http://plnkr.co/edit/F2OM9XtXsfggxN65y3B7?p=preview. It does keep track of the change, you just didn't have the appropriate callback set to keep track of it.

**Comment by MikeABentley** [comment]
Sweet, thanks!
