### ISSUE TITLE
Grid: Spinner does not center vertically relative to viewport

### ISSUE THREAD

**Issue by RARowe** [blackbaud/skyux1#1019]
### Expected behavior
When loading occurs on a grid, the spinner should be visible.

### Actual behavior
When the grid is of a great enough vertical size, the spinner is out of view for the user.

### Steps to reproduce
1. Create a grid with ~50 entries
2. Do some loading action (sort, search, or call loading directly)
3. Notice that the spinner is out of the visible area for the user

### Plunker
http://plnkr.co/edit/pQAn7gagFlVDvyOIOFSx?p=preview

This issue was referenced in https://github.com/blackbaud/skyux/issues/36#issuecomment-173676921, but there were no more comments regarding it. I looked for related issues, but did not find any. If this has already been discussed, my apologies!

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah we're probably not going to update this because that's just how blocking wait works on a large element. If you want to give some sort of wait indication that is fixed on a page you can use a nonblocking or blocking page wait http://skyux.developer.blackbaud.com/components/wait/

**Comment by Blackbaud-PatrickOFriel** [comment]
Closing unless @Blackbaud-ToddRoberts has anything else to say about this
