### ISSUE TITLE
BootLint errors in SummaryActionBar component

### ISSUE THREAD

**Issue by Blackbaud-CoreyArcher** [blackbaud/skyux1#1020]
### Expected behavior
I should not see BootLint errors when I scan a page containing this component
### Actual behavior
I see BootLint errors when I scan a page containing this component
### Steps to reproduce
Navigate to the Summary Action Bar component demo page.
Run BootLint on the page.
Observe BootLint warnings regarding button elements without a specified type attribute.

**Comment by Blackbaud-PatrickOFriel** [comment]
Can you be more specific with the actual bootlint errors?

**Comment by Blackbaud-CoreyArcher** [comment]
![image](https://cloud.githubusercontent.com/assets/17570949/25355703/8819cff4-2905-11e7-8a1b-441065b0c429.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
Thank you!

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.15.0](https://github.com/blackbaud/skyux/releases/tag/v1.15.0)
