### ISSUE TITLE
Unit tests cannot connect to Chrome

### ISSUE THREAD

**Issue by Blackbaud-BenCook** [blackbaud/skyux1#1021]
### Expected behavior

`grunt karma:unit` or `grunt test` runs unit tests successfully.

### Actual behavior

`grunt karma:unit` and `grunt test` fail with errors similar to the following:

```
27 04 2017 08:26:46.720:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
27 04 2017 08:26:46.729:INFO [launcher]: Starting browser Chrome
27 04 2017 08:26:48.930:INFO [Chrome 58.0.3029 (Windows 7 0.0.0)]: Connected on socket TGtE_6Z-lW9WWq4sAAAA with id 47698609
27 04 2017 08:26:55.715:WARN [web-server]: 404: /base/bin/css/images/broken.svg
27 04 2017 08:26:55.769:WARN [web-server]: 404: /base/bin/css/images/construction.svg
27 04 2017 08:26:55.781:WARN [web-server]: 404: /base/bin/css/images/notFound.svg
27 04 2017 08:27:01.135:WARN [Chrome 58.0.3029 (Windows 7 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
Chrome 58.0.3029 (Windows 7 0.0.0): Executed 0 of 1011 DISCONNECTED (10.008 secs / 0 secs)
```

### Steps to reproduce

Just run `grunt karma:unit` or `grunt test`.

### Plunker

N/A

### Additional information

This occurred on the `master` branch after recently getting the latest code, purging `node_modules`, and rerunning `npm install`. I've duplicated on Mac OS X and Windows. It _may_ be at least somewhat intermittent. I think it has worked a couple of times, but it definitely usually fails with the `DISCONNECTED` message. I received similar output with PhantomJS. Using Firefox worked, but I continued to receive these warnings while unit tests were running:

```
27 04 2017 08:26:55.715:WARN [web-server]: 404: /base/bin/css/images/broken.svg
27 04 2017 08:26:55.769:WARN [web-server]: 404: /base/bin/css/images/construction.svg
27 04 2017 08:26:55.781:WARN [web-server]: 404: /base/bin/css/images/notFound.svg
```

**Comment by Blackbaud-PatrickOFriel** [comment]
Should be fixed in master

**Comment by Blackbaud-BenCook** [comment]
Thanks, @Blackbaud-PatrickOFriel. I'll try again when I circle back to working on it.

**Comment by Blackbaud-BenCook** [comment]
This resolved the issue for me. Thanks.
