### ISSUE TITLE
Search Component custom max-width

### ISSUE THREAD

**Issue by Blackbaud-SeanLatif** [blackbaud/skyux1#1023]
### Expected behavior
We'd like to be able to set the max width on the search input to be something besides 300px. Preferably to fill up the container. We override that now with CSS.

### Actual behavior
No matter what the size of the container, the search box's max width is 300px.

### Steps to reproduce
Put the search component into a div container whose width is over 300px.
Notice that the search box does not extend past 300px.

### Plunker
http://plnkr.co/edit/FSHn3Zcz7p4zkIG5W3ay?p=preview
(We would want to fill up the red box)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.15.0](https://github.com/blackbaud/skyux/releases/tag/v1.15.0)
