### ISSUE TITLE
bb-tile-collapsed not working on form load

### ISSUE THREAD

**Issue by Blackbaud-RobCuller** [blackbaud/skyux1#1033]
### Expected behavior
When opening a modal that contains a bb-tile element with bb-tile-collapsed == true, I'd expect the tile section to be collapsed.

### Actual behavior
In this scenario, the section is not collapsed.

### Steps to reproduce
In the plunker below, I added "bb-tile-collapsed="true"" to the tile on the modal that loads when you click "Open modal with tile".  Notice that the tile section is not collapsed on form load.

### Plunker
http://plnkr.co/edit/9iIcWqVopISKekE4Dsjy?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.15.1](https://github.com/blackbaud/skyux/releases/tag/v1.15.1)
