### ISSUE TITLE
Select field > IE 11 render bug

### ISSUE THREAD

**Issue by Blackbaud-JeremyRyan** [blackbaud/skyux1#1035]
### Expected behavior
The select field modal renders with the cursor in the input field
### Actual behavior
The select field renders with the cursor above the input field, until you start typing or click the input box.

### Steps to reproduce
Reproducible in IE 11 on the single select field on the documentation site. The multi select field seems to fire something that prevents this problem from happening.

http://skyux.developer.blackbaud.com/components/selectfield/

### Plunker

![image](https://cloud.githubusercontent.com/assets/12037466/26640583/25c31f32-45f6-11e7-9a9d-aeb69db98aa8.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.15.3](https://github.com/blackbaud/skyux/releases/tag/v1.15.3)
