### ISSUE TITLE
Infinite scroll loadmorerows does not work without jsonmap

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#1042]
### Expected behavior
Infinite scrolls should show the values from new rows even if the column does not have a jsonmap defined.

### Actual behavior
These columsn do not show any data

### Steps to reproduce
Create a column without a jsonmap defined.  Use infinite scroll.  Notice that these columns have no data in the new rows.

### Plunker
http://plnkr.co/edit/9tKjhHVsxxOS8HUTaAlg?p=preview

The source of the issue seems to be the following code. Note that it doesn't seem to properly handle columns without a jsonmap:

+                                        // 
 +                                        if (column.jsonmap !== column.name) {
 +                                            columnHasJsonMap = true;
 +                                        }

**Comment by Blackbaud-PatrickOFriel** [comment]
Yep, in fixing #1037, a bug was introduced when a grid has a jsonmap column and a column without jsonmap. I have a fix and a test for the fix, so I should have a release out in a couple hours

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.15.5](https://github.com/blackbaud/skyux/releases/tag/v1.15.5)
