### ISSUE TITLE
Grid text search highlights context menu items

### ISSUE THREAD

**Issue by Blackbaud-StacyCarlos** [blackbaud/skyux1#1047]
### Expected behavior
Grid search text that matches context menu item titles should not highlight item text.

### Actual behavior
Context menu text is also highlighted.

![image](https://user-images.githubusercontent.com/13663118/28330990-83d2b5aa-6bbd-11e7-8983-977cf647b3c4.png)

### Steps to reproduce
Create a grid such that a row contains a context menu item title that matches the search text criteria as one of the colunms in the row.

### Plunker
http://plnkr.co/edit/C7bdmg7dtQWzO3BT2Euj?p=preview

A search for "Edit" highlights both the column and context menu text.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.15.6](https://github.com/blackbaud/skyux/releases/tag/v1.15.6)
