### ISSUE TITLE
navbar disappears

### ISSUE THREAD

**Issue by Blackbaud-RobertTester** [blackbaud/skyux1#109]
navbar disappears on smaller resolutions.  I am assuming this is because it is looking for the omnibar.  If the omnibar is not present then the navigation just becomes invisible.  You can use the plunkr example you have on the example page (http://skyux.developer.blackbaud.com/components/navbar/).  Just resize the screen to a smaller size and you will see.

**Comment by Blackbaud-PaulCrowder** [comment]
The intention is that you use the omnibar navigation at small screen resolutions. @Blackbaud-JonathanBell, do you know where Robert can find documentation for how to build omnibar navigation?

**Comment by Blackbaud-RobertTester** [comment]
We are not currently using the omnibar and don't know if we will be able to.  Are you saying that we should just use something else if we are not using the omnibar?  Also, I think you should list that in the docs of the navbar control that it will be unusable if the omnibar is not present.

**Comment by Blackbaud-PatrickOFriel** [comment]
Or we might be able to provide some sort of configuration option that doesn't hide the navbar at small sizes. Either way, should probably be documented.

**Comment by Blackbaud-PatrickOFriel** [comment]
Just dug a little bit and found that if you add the `bb-navbar-showmobile` class to the `bb-navbar` directive, then the `bb-navbar` contents will not disappear on small screens and you can set up the navbar without without the presence of an omnibar. I just merged in a pull request that added this information to the demos/documentation.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.7](https://github.com/blackbaud/skyux/releases/tag/v1.4.7)
