### ISSUE TITLE
Add hover/focus state to the alert-link class

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux1#110]
Links in an alert should have the alert-link class, as per the [Bootstrap documentation](http://getbootstrap.com/components/#alerts-links).  Their default hover/focus state is an underline, which I believe we're overriding.  We should restore either the default behavior or implement our own, but a visual indication is needed.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.0](https://github.com/blackbaud/skyux/releases/tag/v1.5.0)
