### ISSUE TITLE
Upgrade to FontAwesome 4.5.0

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux1#111]
Seems like just yesterday we upgraded to FontAwesome 4.4.0, but there's now a new version.

**Comment by Blackbaud-BobbyEarl** [comment]
This upgrade is [failing](https://travis-ci.org/blackbaud/skyux/builds/94736054) as the size of the fonts seems to have changed.  If intended, will delete the appropriate screenshots, merge, and document accordingly.

https://github.com/FortAwesome/Font-Awesome/issues/8101

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.8](https://github.com/blackbaud/skyux/releases/tag/v1.4.8)
