### ISSUE TITLE
https://blackbaud.com/ shows cert error

### ISSUE THREAD

**Issue by jayvdb** [blackbaud/skyux1#1128]
https://blackbaud.com/ shows cert error

>  The certificate is only valid for the following names: *.azurewebsites.net, *.scm.azurewebsites.net, *.azure-mobile.net, *.scm.azure-mobile.net, *.sso.azurewebsites.net
 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by Blackbaud-BobbyEarl** [comment]
Thank you for filing an issue @jayvdb.  This error is unrelated to SKY UX; however, I am definitely going to do my part to track it down and notify the right person internally.  Thanks again!

**Comment by Blackbaud-BobbyEarl** [comment]
I've been told and confirmed, this issue has now been resolved.  Thanks again @jayvdb.
