### ISSUE TITLE
Is there an estimate when sky will support Angular 1.4.x?

### ISSUE THREAD

**Issue by Blackbaud-RobertTester** [blackbaud/skyux1#114]
The Luminate team would like to start using the newest version of Angular.  Is there a timetable as to when the Sky team will start supporting Angular 1.4.x?

**Comment by Blackbaud-PatrickOFriel** [comment]
After we get in the upgrade of ui-bootstrap, we'll probably look at upgrading angular to 1.4.x in January/February. When trying to upgrade to 1.4.x a couple months ago there were some breaking changes so when we do make that angular upgrade, it will be a minor version change.

**Comment by Blackbaud-PatrickOFriel** [comment]
Also, just curious, what feature is your team looking for in 1.4.x?

**Comment by Blackbaud-RobertTester** [comment]
If you look at the release notes https://docs.angularjs.org/guide/migration you can see there have been a ton of bug fixes and performance improvements for core pieces of Angular.  Other than that there are some new features we want to use:
- For directives we would like to take advantage of the bindToController changes.  This change really cleans up the directive code.  I imagine you would want to take advantage of this as well.
- Changes to the way cookies are handled with the $cookies service
- Changes to the limitTo and filter
- Improvements to forms

Lastly, v1.4 was released last May.  I really hope we can expect upgrades in a timely manner in the future.

**Comment by Blackbaud-PatrickOFriel** [comment]
We will try to keep libraries updated. If you need a specific library updated and we haven't done so, you can request it here and we will make an action item to do so, or if you need it done faster than we can get to it you can fork and make the necessary changes in skyux and create a pull request that we will be happy to merge.

**Comment by Blackbaud-RobertTester** [comment]
OK, so you want me to upgrade the version of Angular, fix the unit tests, and then submit a pull request for that?  If that is what you are suggesting I will go through the steps to do that and start scheduling time in my team's future sprints to do this.  What tests do you have in place for something like this?  I know you have unit tests but I imagine you have something else to test the rendering of the controls.  Is there documentation somewhere that describes your testing system?

If this is not the case, I would hope you already have an action item to upgrade Angular.  However, if you don't please take this as a formal request.  We would like to start using the new version asap.  We can't wait until February (9 months after the release) to an upgrade.

**Comment by Blackbaud-PatrickOFriel** [comment]
I'll start looking into upgrading angular in the next few weeks. If you want to get a head start you can run our unit tests using `grunt test` or change and save code while running `grunt watch`. Our visual regression tests are currently run using phantomcss and slimerjs using `grunt visualtest`. We're currently working on moving our visual regression tests to use webdrivercss to leverage Browserstack in multiple browsers, and we should have more documentation around using the visual regression suite. All of these tests will run automatically when a pull request is submitted to the repository.

Please remember that this is a fairly new project that previously was used to support a product using Angular 1.3.x (which still had releases occurring regularly until the end of September). We had been upgrading libraries as RENxt needed them, or a specific feature called for them. We realize that we are serving a wider product base now and are looking forward to keeping our upgrade cycle at a quicker tempo.

**Comment by Blackbaud-IsaacAggrey** [comment]
Thanks for the info, Patrick. Also, if the newly-made #121 is going to be the official issue for tracking the upgrade for Angular 1.4, then I'd triage this issue to closed/duplicate.

**Comment by Blackbaud-PatrickOFriel** [comment]
Yep will do
