### ISSUE TITLE
Check > Font size

### ISSUE THREAD

**Issue by Blackbaud-LoriWeiss** [blackbaud/skyux1#115]
The `.bb-check-checkbox, .bb-check-radio` classes need to be updated to have `font-size: 14px`.  Currently in RE NXT, the check boxes and radio buttons are getting their font size from body, which is 13px. This makes the check mark appear vertically off center.  On the SKY UX documentation page, the check boxes get their 14px font size from bb-body-text and appear centered.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.6](https://github.com/blackbaud/skyux/releases/tag/v1.4.6)
