### ISSUE TITLE
Text expand visual regression test failing sporadically

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#116]
The "text expand with line break (expanded)" visual regression test is failing sporadically with a 1-pixel difference in the position of the text.  This is very likely because expanding the text is animated and there is a race condition between when the animation completes and when the screenshot is taken.  We should disable jQuery animations during visual regression tests to eliminate this race condition.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.6](https://github.com/blackbaud/skyux/releases/tag/v1.4.6)
