### ISSUE TITLE
Add a to-from option to daterangepicker

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#122]
Proposed spec:
https://blackbaudinc.box.com/s/5lbg2ej4dpzpwrycoycytj5hhbyl8yw9

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ToddRoberts, what kind of error messaging should occur for things like user inputing an invalid date (not an actual date or the start date is greater than the end date, etc)?

**Comment by Blackbaud-ToddRoberts** [comment]
Please enter a valid date.
Start date must be before end date.
Not sure what other error states it could end up in.

**Comment by Blackbaud-PatrickOFriel** [comment]
End date must be after start date.

Other than that I can't think of much else

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ToddRoberts any reason that the specs for the fields with labels have the datepicker inputs at half the width of the date range dropdown, but the standard width tile version the datepicker inputs are the same width as the date range dropdown?

**Comment by Blackbaud-ToddRoberts** [comment]
the smaller size fits the content better, but would look awkward on the tile version. if it is easier to make them all the same it's not a huge deal.

**Comment by Blackbaud-PatrickOFriel** [comment]
It'd be easier if they stayed just the same width as a standard input because that's how the bootstrap form-group classes work

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.5](https://github.com/blackbaud/skyux/releases/tag/v1.5.5)
