### ISSUE TITLE
Collapsible repeater pattern

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#124]
Create component/classes for collapsible repeater pattern for use within tiles.

**Comment by Blackbaud-ToddRoberts** [comment]
https://blackbaudinc.box.com/s/933glequc4suaf6m7ntzw9r8ecdotu3r

Designer: Todd

Approved

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.16](https://github.com/blackbaud/skyux/releases/tag/v1.5.16)
