### ISSUE TITLE
Pull carousel into Sky

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#126]
Currently it's sitting in a branch of the sky-sample repo, but more teams want to use it. We should pull it into Sky proper.

Completed tasks:
- [x] Component
- [x] Accessibility
- [x] Unit tests
- [x] Documentation
- [ ] Visual regression tests

**Comment by Blackbaud-PaulCrowder** [comment]
Adding @blackbaud-johnly and @Blackbaud-ToddRoberts to complete the documentation task.  The current documentation is in the [`carousel-component`](https://github.com/blackbaud/skyux/tree/carousel-component) branch.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.4](https://github.com/blackbaud/skyux/releases/tag/v1.6.4)
