### ISSUE TITLE
Autonumeric demo only allows entering one number at a time

### ISSUE THREAD

**Issue by nuander** [blackbaud/skyux1#128]
Hello.  If you check the demo at http://skyux.developer.blackbaud.com/components/autonumeric/  you can see that it only allows the user to enter one number, then the cursor goes to the far right of 2 decimal places and excepts no further input.
Mark G

**Comment by Blackbaud-PatrickOFriel** [comment]
I'm not seeing this behavior. What browser are you using?

**Comment by nuander** [comment]
Oh interesting.  Its not an issue in chrome\ff\safari.  I tested in IE11.

**Comment by nuander** [comment]
Doesn't seem to work at all in Opera 11.  Not very concerned, just FYI

**Comment by Blackbaud-BobbyEarl** [comment]
Confirmed the behavior in IE11.  Thanks for the info.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.7](https://github.com/blackbaud/skyux/releases/tag/v1.4.7)
