### ISSUE TITLE
Grid does not render correctly inside of tabset

### ISSUE THREAD

**Issue by Blackbaud-RobertTester** [blackbaud/skyux1#134]
See http://plnkr.co/edit/d9SfqWcKv32O2hkcLSaI?p=options

Grid does not render correctly when placed as the content of a tab set.  The table headers and rows do not try to fill the entire usable area.  If you resize the page the controls the rows snap into the correct width.

**Comment by Blackbaud-PatrickOFriel** [comment]
Have you been able to replicate this in a non-plunker environment? I haven't, but I suspect the problem is that it is calculating the width available for the last column before the grid is actually visible. I'll take a look at making the grid recalculate column widths when grid visibility changes.

**Comment by Blackbaud-RobertTester** [comment]
The way I found out about the problem was outside of plunker.  I just created the plunker to have something to show you.  The grid columns will snap into place if you resize the window so there is probably just some initial sizing that needs to take place.   A call to handleTableWrapperResize() inside of grids.js fixed the problem for me.

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah, I just reproduced it locally as well. I think you're right, just need to call handleTableWrapperResize() when the tableWrapper width changes from 0 to nonzero. I'll give it a whirl

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.7](https://github.com/blackbaud/skyux/releases/tag/v1.4.7)
