### ISSUE TITLE
Build Out your Application link in getting started guide is broken

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#138]
When I click the "Build Out your Application" link at the bottom of this page I get a 404.  The link on the left-hand side works fine.

http://skyux.developer.blackbaud.com/getting-started/create-a-tabbed-page/

**Comment by Blackbaud-BobbyEarl** [comment]
Fixed this and another broken link via https://github.com/blackbaud/skyux-docs/commit/0d2b40f479d582900ee57ce5ceffd6dce478fdd5  FYI @blackbaud-johnly
