### ISSUE TITLE
Sky Localization Documentation?

### ISSUE THREAD

**Issue by Blackbaud-RobertTester** [blackbaud/skyux1#141]
Is there any documentation on how to localize the library?  

I noticed that there is a locales folder in the dist directory with some overrides in it.  I am assuming that I would just include the file that would contain the locales that I need.  Is this correct?  

The other issue I have is sky does not have translations for all the languages I need to support.  So I really need all the available overrides that I can use so that I can submit new translations for the languages I need.

**Comment by Blackbaud-SteveBrush** [comment]
To add a different language, it looks like you would include a new directory and strings.json (for that language) in **js/sky/locales/** (I believe the locales files in the "dist" folder are being generated by a Grunt task "l10n" (around line 424 in gruntfile.js).

**Comment by Blackbaud-SteveBrush** [comment]
Also, saw this in **js/sky/src/help/help.js**:

### bbHelpConfig Settings
- `customLocales` Optional.  An array of additional locales for which the product has help content other than the default help content locale.  This array should contain strings like 'en-gb' or 'fr'.

My experience with SkyUX isn't great, but it looks like you would pass your locales as an array of strings to bbHelpConfig, in your Angular app's .run() method ([see the demo](https://github.com/blackbaud/skyux/blob/master/demo/static/js/KitchenSink.js#L8)).

**Comment by Blackbaud-RobertTester** [comment]
Thanks for the info Steve.  I looked in js/sky/locales and I see the strings.json you are referring to.  Do you know if the en-US strings.json contains all the keys we can override in different languages?

**Comment by Blackbaud-BobbyEarl** [comment]
That is correct @Blackbaud-RobertTester.  Here are two examples using the bbResources filter.
- Specifying the [en-ca locale](http://plnkr.co/edit/4bZts6uJkmHbiCmhtz72?p=preview)
- Using the default [en-us locale](http://plnkr.co/edit/jhMbtGC53r2mRHeFH5Cn?p=preview)

Regarding additional translations... we're currently in the process of integrating with a third-party service to provide translations of the JSON strings in the locales folder.  Just curious what additional languages will you need support for so we can help coordinate that effort.

**Comment by Blackbaud-RobertTester** [comment]
French, Spanish, German, Dutch, Italian.

We can probably do these translations if you have not already done so.  I am pretty sure we are going to use the same service for this anyway (lingoport).  We are already going to have to get the other text in our app translated in these languages.  I don't think it would be a big deal to add the sky translations since there doesn't seem to be that many.  Let me know what you think and I can look into this.

**Comment by Blackbaud-BobbyEarl** [comment]
Same vendor.  As you've already seen, we don't have a huge amount of strings to translate.  Using SKY UX is more of a test for the semi-automated process.  I'll pass the language requirements back to our contact.

I've created #143 if you're interested in tracking the progress.
