### ISSUE TITLE
Document bbResources

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux1#143]
Document bbResources, specifically how to use browser culture in conjunction with sky locales.

**Comment by Blackbaud-PatrickOFriel** [comment]
This would go in some sort of advanced sky topics section on the documentation site

**Comment by Blackbaud-MitchellThomas** [comment]
From what I see in the code, en_US language in included by default in the distribution, and one of the other `sky-locale-*.js` override files must be included by itself through something like a script tag. This will modify what bbResources contains by extending it. I really like this approach to build up the specific resources for a given language through layering. Once it's loaded, you don't have to think about it.

Presently, I don't see a way to simply provide a locale to a directive/service/etc. and have it automatically load the resources from the available languages through the standard fallback path, i.e. Language+Country -> Language -> Default. We're having to keep track of what languages are available ourselves and include the appropriate file.

I think enhancing the bbResources service to listen to a locale and automatically provide the appropriate language resources would make it much easier to use and document. This locale could be either be provided to bbResources by the code using it or pulled from the browser automatically.

The one challenge I see is with loading the requested language bundle on-demand. It would quickly get out of hand to load every possible language in initially, but a server side dependency doesn't sound very good either.
