### ISSUE TITLE
Clean up label, badge, alert & notification classes

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#145]
Do we need to revisit this issue from the old repo @Blackbaud-ToddRoberts or can we make more specific action items at this point?

**Comment by Blackbaud-ToddRoberts** [comment]
We will need to break it up into separate items. I can do that if you want.

**Comment by Blackbaud-PatrickOFriel** [comment]
Yes please

**Comment by Blackbaud-ToddRoberts** [comment]
Broke out into separate stories.
