### ISSUE TITLE
Create standalone filter components

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#146]
The filters just grow length-wise and hide the apply button until scrolling down if the amount of filters gets too high (which has happened a bunch in NXT). We need to rework filters to be more graceful in handling a bunch of content.

**Comment by Blackbaud-ToddRoberts** [comment]
Rob is working on filters. 
Proposed pattern: 
http://skyux.docs.blackbaudhosting.com/references/patterns/filtering/
Design is not done yet.

**Comment by Blackbaud-ToddRoberts** [comment]
https://blackbaudinc.box.com/s/7bhvjep06fhlqc677zs63m5x2nlel072 

Designer: Rob
Guidelines approved
Converting flyout to modal approved
Separate pattern project for the multi-section forms

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @blackbaud-johnly, some docs notes. `bb-filter-summary-item-is-dismissable` is listed as optional. It should have a default value of `true`. Let me know if you need any other info

**Comment by blackbaud-johnly** [comment]
I started reviewing the docs and made a list of edits and questions. I'm tied up for the rest of the day, but I should get back to this tomorrow.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.10](https://github.com/blackbaud/skyux/releases/tag/v1.6.10)
