### ISSUE TITLE
Add "decorator" directive for input elements so they can be styled without a lot of complex markup

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#148]
From @Blackbaud-PaulCrowder 

We need a way to decorate plain `input` elements to look like different types of controls.  One example is the search box we use in Sky that is nothing more than an `input` element with a spyglass image next to it.  It takes a decent amount of markup to accomplish this, so we should wrap it up in a directive.

**Comment by Blackbaud-BobbyEarl** [comment]
Individual components will be created as needed.  As an example, see http://skyux.developer.blackbaud.com/components/search/
