### ISSUE TITLE
bbFileDrop should stopPropagation on enter keypress

### ISSUE THREAD

**Issue by Blackbaud-DanMiller** [blackbaud/skyux1#156]
Behavior can be seen on the Add Attachments form in RENXT CDEV: https://cdev.renxt.blackbaudhosting.com/constituents/25512?tenantid=45640281-b5c6-4fba-87a8-2ab88335b0d2

Open the form, type a valid link into the "Paste a link to a file" input box, and press enter. Notice the form immediately saves before the user has a chance to do anything else in the form. This could possibly be avoided by ensuring that the submit button on the form is type="button" instead of type="submit", but since all forms use the bb-modal-footer-button-primary directive to render the submit button, consumers of SKY UX cannot specify the button type when this pattern is used.

**Comment by Blackbaud-PatrickOFriel** [comment]
Can you make a plunker that reproduces this problem?

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.8](https://github.com/blackbaud/skyux/releases/tag/v1.4.8)
