### ISSUE TITLE
Make help widget available through a repo

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#168]
Right now the help widget is referenced through a URL instead of being part of SkyUX or another consumable library. We need to decide if this is the correct way to handle this component.

**Comment by Blackbaud-BobbyEarl** [comment]
Tagging @Blackbaud-RobertTester and @Blackbaud-JohnNelson as they initially brought it up and may be interested in tracking any updates.

**Comment by Blackbaud-PaulCrowder** [comment]
The shell team is working on a shared component for help.
