### ISSUE TITLE
Tile dashboard embedded in tabs does not layout tiles properly

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#182]
If you include a tile dashboard inside a tab, then the tiles will not be layed out properly (in terms of expand/collapse and which column the tiles live in) when switching from a tab to the tab containing the dashboard.  This may only occur when the tabs are tied to states.

The problem is illustrated at: http://plnkr.co/edit/CrTU9af8xtoMYGr9oJkf

**Comment by Blackbaud-PatrickOFriel** [comment]
This does seem related to the tabs changing state. The tiles are destroyed and rebuilt because they are tied to states, and then the layout for the dashboard is not reinitialized. I'm working on a solution now.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.1](https://github.com/blackbaud/skyux/releases/tag/v1.5.1)
