### ISSUE TITLE
Visual test label screenshots don't show the whole label

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#186]
The screenshots of labels taken during our visual regression tests chop off the top and bottom of each label.  The screenshot should show the whole label.
![mac_chrome_labels_full labels 1280px baseline](https://cloud.githubusercontent.com/assets/11655766/12237734/2d98c82e-b84e-11e5-9c3f-f6f3eb07496c.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.1](https://github.com/blackbaud/skyux/releases/tag/v1.5.1)
