### ISSUE TITLE
Need the ability to load the file drop control

### ISSUE THREAD

**Issue by MikeABentley** [blackbaud/skyux1#195]
I need to use the file drop control on an edit form.  On form load I have an array of file download uri's and some other data related to each item in my array.  I've include a screenshot from the prototype of the feature.

![image](https://cloud.githubusercontent.com/assets/9357297/12270589/d5dbec24-b924-11e5-83dd-a2c8f7b9f0c1.png)

**Comment by Blackbaud-PaulCrowder** [comment]
Is this just an issue with image files or files of other types?  In other words, if you load up an item that's bound to `bb-file-item` with the same properties as the File object that's bound to it when a file is dropped on the drop target (`name`, `type`, `size`, etc.) does everything work except the preview image on files that are an image?  That seems to be what I've been able to duplicate in [this Plunker](http://plnkr.co/edit/Bz2BaPCYRZjJE1Ql03L8?p=preview).  If that's the only problem then I can look for an `imageUrl` property or something similar and use that when it's present to display the preview image.

**Comment by MikeABentley** [comment]
Yeah, on load all i have is a download url.  I have another property on my model that I can do a switch on to determine whether or not the item is an image or I can just always set the url and have the control do that logic?  It would seem that it best to have the control handle that though in the event that any of that logic needs to change.

**Comment by Blackbaud-PaulCrowder** [comment]
The control determines what to show in the file preview by looking at the file's `type` property (represented by a valid MIME type such as "image/jpeg").  If you're not preserving that information when the control originally provides it to you on save and then providing it when loading your edit form then the control's not going to be able to determine what to show in the preview.  In order for this to work you would need to provide all the fields provided in the Plunker example in my previous comment in addition to the file's URL so the image can be displayed.

**Comment by MikeABentley** [comment]
I can provide all of that information.

**Comment by Blackbaud-PaulCrowder** [comment]
OK, cool.  I'll update the control to look for a `url` property.  That way if later we decide we want to be able to preview a non-image file from the control then it can work for all file types.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.2](https://github.com/blackbaud/skyux/releases/tag/v1.5.2)
