### ISSUE TITLE
bbWait Plunker

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#200]
the “Show Page Wait” and “Show Nonblocking Page Wait” buttons work on the documentation site, but not in the Plunker. This is probably because the documentation site’s main controller is listening for the `bbBeginWait` and `bbEndWait` events, and we have nothing in Plunker that is doing so

**Comment by Blackbaud-BobbyEarl** [comment]
Fixed via https://github.com/blackbaud/skyux-docs/commit/b1398b6c827104818f90a77b850959f2fd1d0e53
