### ISSUE TITLE
bb-grid column resize doesn't work on the first try

### ISSUE THREAD

**Issue by Blackbaud-IanThomas** [blackbaud/skyux1#208]
When resizing the columns on a bb-grid, it will not resize the desired column, but instead increases the width of the first column only a small amount.  On the second attempt, it will resize properly.

We're seeing this in eTapestry and in the "Grid With Pagination In Tile" on the sky demo page.

http://skyux.developer.blackbaud.com/components/grid/

The first demo on that page does work as expected, so it seems to be something configuration related.

**Comment by Blackbaud-PatrickOFriel** [comment]
The reason this is happening with the second demo and not the first is that this only occurs when the columns are too small for the area available. This will cause the last column to become extended in size to fit the available space. The first column size increase after that is supposed to reduce the size of the last column as well. This doesn't seem to be working well, so I'll take a look
