### ISSUE TITLE
Dependency on ui-router

### ISSUE THREAD

**Issue by blackbaud-brandonstirnaman** [blackbaud/skyux1#218]
I would suggest that having a hard dependency on a routing component isn't ideal. Especially when many teams are trying to set themselves up for a future transition to angular 2, which usually starts with using `ngNewRouter`.

**Comment by Blackbaud-PatrickOFriel** [comment]
Right now the standard router for angularjs does not meet our current needs. We will revisit this with the upgrade to angular 1.5.x as there is a new Component router, which might have more of the functionality that we are looking for. 

In terms of a "hard dependency", the two components that rely on ui-router in SkyUX are the tile dashboard (which uses ui-view to populate the dashboard with tile states) and the tab-sref (which revolves completely around associating tabs to routes).  Let me know if I missed any other components that rely on ui-router. If you have suggestions/pull requests for abstracting out the routing for those components let me know, but for now we're going to close this issue.
