### ISSUE TITLE
bb-grid "load more" button makes the grid jump several rows if a row contains more than a couple of lines of text

### ISSUE THREAD

**Issue by Blackbaud-DaveMarino** [blackbaud/skyux1#225]
**Expected Result:**
I would expect the Load More button to add records to the bottom of the page regardless of the number of lines of text in a grid row

**Actual Result:** 
clicking the Load More button causes the grid to jump up several rows, pushing the record the user was looking at off the bottom of the page.  The user then has to scroll past several more records to continue scrolling through the data in the grid.

**Additional info:** 
If all rows are a single line, Load More seems to work as expected consistently. 

There are two cases where I have seen the failure case: 
_Case 1:_ I have a templated column where I am using bb-text-expand-repeater to limit the lines of data to six (which is pushing the limits of acceptable for our use case) .  The first time I click the Load More button, it behaves as expected.  Subsequent clicks jump as described in the "Actual Result Section"

_Case 2:_ I have a non-templated view with a row containing several lines of text, the Load More button will cause the grid to jump each time.

I sent Patrick the following Plunker example exhibiting the problem w/ a non-templated column: http://plnkr.co/edit/mD0iAicyphid111hZRQg?p=preview

Let me know if you need any additional info.

**Comment by Blackbaud-PatrickOFriel** [comment]
I found a more minimal reproduction [here](http://plnkr.co/edit/bd6ejFahkN0cGU5MkDTE?p=preview). You have to click load more a few times to see the effect

**Comment by Blackbaud-PatrickOFriel** [comment]
I've been able to mitigate the issue locally by grabbing the scrollTop of the window right before rows are added and then setting the scrolltop back to the value I grabbed right after rows are added. I'll take a look at getting it merged into master today

**Comment by Blackbaud-PaulCrowder** [comment]
I believe you could fix this by adding the new rows to the grid rather than blowing away the contents of the grid (causing the page to scroll up as the current scroll area disappears) and then repopulating it.  When you fire the event that's emitted when the user clicks the "load more rows" button you could provide a promise that when resolved passes back a collection of rows to be appended.  Here's some pseudocode:

```
var loadMorePromise = $q.defer().promise;
$scope.$emit('loadMoreRows', {
    promise: loadMorePromise
});

loadMorePromise.then(function (moreRows) {
    var transformedRows = transformRows(); // Do whatever you need to get the rows into jqGrid's format
    gridEl.addRows(transformedRows);
});
```

The code that consumes the grid would then provide new rows via the promise passed in the event args:

```
$scope.$on('loadMoreRows', function (args) {
    bbData.load().then(function (result) {
        args.promise.resolve(result.data.rows);
    });
});
```

**Comment by Blackbaud-PatrickOFriel** [comment]
I think Paul's approach above is a bit more robust than mine, and it also has performance benefits. I'll take on the work to create the change and update the documentation to get this happening.

**Comment by Blackbaud-IanThomas** [comment]
This is a pretty awesome fix.  We're already using a promise, so it will take next to no effort to make this happen.  I love the performance benefits, too. Refreshing the whole grid has always seemed less than ideal.  Thanks!
