### ISSUE TITLE
Wrong cursor for filter bubble in grid

### ISSUE THREAD

**Issue by Blackbaud-JonathanBell** [blackbaud/skyux1#230]
The filter bubble for grids has a cursor of "pointer" when it shouldn't.   The cursor indicates that you can take an action but clicking does nothing.  The "X" (.close) should have the special cursor but not the entire bubble.

This is defined in _tables.scss.   It applies the style to .bb-applied-filter-content instead of to .close.

It can be observed at the following link by applying a filter to the first grid on the page and hovering over the filter bubble.

http://skyux.developer.blackbaud.com/components/grid/

**Comment by Blackbaud-JonathanBell** [comment]
So it turns out this bubble is cilckable..... it will open the filter form if it isn't open.  So my complaint in this issue is completely invalid :-1:

**Comment by Blackbaud-PatrickOFriel** [comment]
Well, we changed it, so we can change it back haha
