### ISSUE TITLE
Create a class/directive that appends the current tile configuration icon 

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#234]
In NXT we have configuration messages that include the icon. Click <i class="fa fa-wrench"></i> to configure...

It would be nice to be able to easily keep these in sync whenever the icon used on the actual tile header changes.

Click <i class="bb-configuration-icon"></i> to configure...

**Comment by Blackbaud-PatrickOFriel** [comment]
So just to make sure we're on the same page, you have places where you're using `class="fa fa-wrench"` for configuration. If we allow you to use a class like `bb-config-icon` then you can use that everywhere and when we make a change (like from wrench to cog) then it will change everywhere. Is that about right?

**Comment by Blackbaud-MichaelLopez** [comment]
that is correct.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.5](https://github.com/blackbaud/skyux/releases/tag/v1.5.5)
