### ISSUE TITLE
BB-Grid Filter Bubble tool tip

### ISSUE THREAD

**Issue by Blackbaud-JonathanBell** [blackbaud/skyux1#238]
If the contents of the filter bubble is very long, it is automatically ellipsesed so that it doesn't wrap or stretch the screen, which is good.  However, it would be good to have a tooltip (html "title"?)  showing the full text so that the user can see that information if they want.

**Comment by josh-channin** [comment]
Hey Jonathan, I was messing around with grid filters and saw you could add title-tooltips to the filter summary like in this plunker. http://plnkr.co/edit/2pCCxAyo3ZXlSdmeTDyg?p=preview

**Comment by Blackbaud-JonathanBell** [comment]
Awesome thanks!

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-JonathanBell do you need anything more than the solution provided by @josh-channin? I know there are also some design changes in general that might be coming down the road for applied filters

**Comment by Blackbaud-JonathanBell** [comment]
I think this should be good.  Thanks yall!
