### ISSUE TITLE
Typo on the getting started homepage: "...create SKY UX the two common page types."

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#244]
There's a nasty typo on our getting started page in this paragraph:

"You can use the tutorials that follow to get started with SKY UX. They walk you through the basics of a simple application and demonstrate how to create SKY UX the two common page types."

http://skyux.developer.blackbaud.com/getting-started/

**Comment by Blackbaud-BobbyEarl** [comment]
Fixed in https://github.com/blackbaud/skyux-docs/commit/af355bb641c98db4691d92c6bfbc39541ef08991 

FYI, this ran last night but failed to automatically update the site due to GitHub connectivity issues.
