### ISSUE TITLE
Update Bootstrap text-danger and has-error classes

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#251]
We should use the sass variable $bb-error-color for any error related text. The Bootstrap classes associated with error text do the same.

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-ToddRoberts, here's a plunker of the old and the new bootstrap text danger colors, just confirming that this what we want http://plnkr.co/edit/9VMkwFUTRTlWSbb65M2q?p=preview.

**Comment by Blackbaud-ToddRoberts** [comment]
Looks correct to me

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.5](https://github.com/blackbaud/skyux/releases/tag/v1.5.5)
