### ISSUE TITLE
Add monitoring to our web site and CDN to detect outages

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#255]
We need to set up a regular ping to our web site and CDN so that we're notified when one becomes unavailable.  Azure's Application Insights may meet this requirement.

**Comment by Blackbaud-BobbyEarl** [comment]
Endpoint monitoring has been enabled for approximately 3 months.  Email alerts were enabled if failures occur for more than five minutes.  We also have the need to enable PagerDuty should be need arise.

<img width="560" alt="monitoring-and-availability" src="https://cloud.githubusercontent.com/assets/4612419/13765531/95dd6f0c-ea30-11e5-988a-6599515d6f98.png">
