### ISSUE TITLE
Grid column resize bug fix is causing issues with other table elements on the page

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#257]
[This change](https://github.com/blackbaud/skyux/blame/master/js/sky/src/grids/grids.js#L537-L538) for issue #208 is causing the width of the first `table` element on the page to be resized because the `bDiv` and `hDiv` elements used as the jQuery context parameters are undefined.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.4](https://github.com/blackbaud/skyux/releases/tag/v1.5.4)
