### ISSUE TITLE
searchfield_no_records text is "text for ui-select search control when no records are found"

### ISSUE THREAD

**Issue by Blackbaud-SeanLatif** [blackbaud/skyux1#264]
Per Bug 590800, when a record does not come up in a search, "text for ui-select search control when no records are found."

The following files also have that text set for searchfiled_no_records:
sky.js
sky-bundle.js
sky-bundle.min.js
sky.min.js
sky-locale-en-US.js

**Comment by Blackbaud-PatrickOFriel** [comment]
Looks like this happened when we were restructuring locale files for lingoport. The actual message should be  `Sorry, no matching records found`

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.4](https://github.com/blackbaud/skyux/releases/tag/v1.5.4)
