### ISSUE TITLE
We would like to have a phone number field directive in sky

### ISSUE THREAD

**Issue by MikeABentley** [blackbaud/skyux1#265]
As we get into more record CRUD operations we've found that we have a need for a phone number field.  We'd like to allow the user to enter phone numbers and have the system auto-format the number for them.  

After doing some research I've found that google has a decent library called libphonenumber.  The library allows you to define a default country format.  Phone number values entered into the field will attempt to format using the defined country value.  The library also allows for the user to enter a country code regardless of the default country value.  The library will then format the number based on the country code provided.

Since this functionality will be used on multiple forms it would be best to have it wrapped up in an angular directive.  This feature will likely be needed in multiple applications making sky the best location for the directive.

[https://github.com/googlei18n/libphonenumber](https://github.com/googlei18n/libphonenumber)

**Comment by Blackbaud-PatrickOFriel** [comment]
We're going to need some more info on exactly what functionality is required. Is this needed only in form fields, or should it be available as a read-only filter? Should we also make this available through a service? What countries must be supported? I would have your designer send specs to the design council so we can figure out everything that'll need to be supported across products

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-Robfavre do you have any requirements for phone fields?

**Comment by Blackbaud-Robfavre** [comment]
Nothing concrete right now but I can put some together to use as a starting point.  To start we would need to support US, Canada, UK, Ireland, Australia and New Zealand but that list is only going to grow over time so the control will need to either handle others or at least be extensible.

**Comment by Blackbaud-PatrickOFriel** [comment]
Hokay, is there any idea if it would be one input that you would type in, or separate inputs for each phone number segment. I believe I've seen both in the history of internet

**Comment by Blackbaud-Robfavre** [comment]
I would prefer a single field that is smart enough to figure out the formatting once it loses focus

**Comment by Blackbaud-PatrickOFriel** [comment]
See #583
