### ISSUE TITLE
"Local Npm module not found" errors occur when running Grunt tasks

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#267]
When running Grunt tasks, the following errors are emitted to the console/build log.  This is occurring both locally and in Travis.
- Local Npm module "grunt-contrib-copy" not found. Is it installed?
- Local Npm module "grunt-contrib-watch" not found. Is it installed?

I'm also now receiving a third error locally but I haven't seen it in Travis.
- Local Npm module "grunt-exec" not found. Is it installed?

These errors occur immediately after this message is logged to the console, so the two may be related:
- STACHE Defaulting to config file stache.yml

**Comment by Blackbaud-BobbyEarl** [comment]
These warnings are specifically related to Stache adding support for NPM3.  https://github.com/blackbaud/stache/commit/2324ee15ee5c1d75d1cad8c32be79ded95ddba50

They are under active development and I will close this issue once the fix has been released.

**Comment by Blackbaud-BobbyEarl** [comment]
This was resolved in Stache version 0.7.6.
