### ISSUE TITLE
sky charts module deprecated?

### ISSUE THREAD

**Issue by Blackbaud-BrandonHay** [blackbaud/skyux1#27]
Hello,

We recently have tested upgrading to the latest sky and have noticed that we see this error on page load ![image](https://cloud.githubusercontent.com/assets/11929859/10981595/a01cccee-83d6-11e5-8f64-eeb1f6d06e98.png)

Did you guys get rid of the `sky.charts` module? I'm not certain that we were even using it, but wanted to confirm that it's no longer supported.

Thanks,
- Brandon

**Comment by Blackbaud-PaulCrowder** [comment]
It has been removed.  I am curious as to why your code is referencing it, though, since adding the `sky` module as a dependency to your Angular app pulls in all the modules you would need without having to pull in each individual one.

```
angular.module('yourapp', ['sky']);
```

**Comment by Blackbaud-BrandonHay** [comment]
I'm not entirely sure why that was in our code. Regardless, it is gone. Thanks for the quick reply.
