### ISSUE TITLE
Avatar initials aren't displayed if the name isn't available when the directive is initially linked

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#272]
If the name provided to the avatar directive isn't available immediately (e.g. retrieved during an Ajax call) then the initials are never rendered.

http://plnkr.co/edit/3DyKpXK5ts3YjLhDLxuQ?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.5](https://github.com/blackbaud/skyux/releases/tag/v1.5.5)
