### ISSUE TITLE
Add a set of searchable column properties to the grid directive

### ISSUE THREAD

**Issue by Blackbaud-SpencerMurphy** [blackbaud/skyux1#276]
Currently, the search functionality of the column picker on grid directive uses the default search functionality of the checklist directive. This results in all of the properties on the grid that get passed into the checklist directive being used in the search criteria. It would be good to be able to specify which properties should actually be used when searching. 

The proposed fix for this will be to add a new optional property to grid-options that is an array of properties on the columns to search on (i.e. ['caption', 'description']). This option would be optional and would still maintain the default searching behavior when this new option is not used. The bb-checklist-filter-callback function would then be used when passing data to the checklist directive inside of the column picker to do searches similar to the default behavior, but only accept values in those properties rather than all of them.

**Comment by Blackbaud-BobbyEarl** [comment]
In [v1.5.9](https://github.com/blackbaud/skyux/releases/tag/v1.5.9)
