### ISSUE TITLE
Text Expand: "See more" link href triggers page navigation with "see more" modal

### ISSUE THREAD

**Issue by Blackbaud-IanThomas** [blackbaud/skyux1#277]
In our application, when the "See more" link is clicked for a piece of text that opens a modal, it navigates the page instead of just opening the modal.  

`<a href="#" class="bb-text-expand-see-more">See more</a>`

I don't think there is a need for the `href="#"`. Clicking on the anchor tag works just fine without it.  Removing it solves this issue.

Also the close button on the bottom of the modal isn't localized.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.6](https://github.com/blackbaud/skyux/releases/tag/v1.5.6)
