### ISSUE TITLE
Card layout component

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#286]
https://blackbaudinc.box.com/s/e1qq1mos2qccqx30em74mhdgg1i4fua3

Approved

Design contact: Todd Roberts

**Comment by Blackbaud-PaulCrowder** [comment]
A couple questions:
- For the Width and Height options, should we provide some predefined sizes (small, medium, large)?  That way we could maintain consistency for similar cards across implementation.  We could do this in conjunction with allowing a numeric value for special cases.
- Do the arbitrary content areas on either side of the title have a max-width?
- The right side of the title accommodates arbitrary content, but at the bottom of the document you show a checkbox that presumably also alters the card's background color.  The only way to sync the background color of the card with the checked state of the checkbox is to make the checkbox a first-class feature.  If we do that, do we still want to allow arbitrary content to the right of the title?

**Comment by Blackbaud-ToddRoberts** [comment]
Predefined default sizes make sense. How about:
Small: 200x250 (gives 6 columns on a 1280w grid view)
Large: 300x350 (as in the carousel)

Not sure on this, if it is better to be restrictive up front I think it'd be fair to make max width = height of the title bar so those sections are squares.

Is there a way to work around the checkbox issue, like you could use arbitrary content OR a checkbox, but only get the bg color switch with the checkbox?

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.15](https://github.com/blackbaud/skyux/releases/tag/v1.5.15)
