### ISSUE TITLE
Listbuilder view switcher

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#287]
https://blackbaudinc.box.com/s/lo1hlvb16ktlo6nmq6zg94abbj7ququi

Approved

Design contact: Todd Roberts

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-ToddRoberts, for the listbuilder toolbar at 480px screenwidth: how do we handle custom buttons?

**Comment by Blackbaud-ToddRoberts** [comment]
We have another design project to look at the tool bar because it does not scale. I assume we need to finish that project in order for view switcher to be finished?

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah, otherwise it'll just wrap the buttons in another row of the toolbar I would think because that's kind of the default degradation.

**Comment by Blackbaud-ToddRoberts** [comment]
http://scdr6h.axshare.com/#g=1&p=collapsed_view_switch

**Comment by Blackbaud-PatrickOFriel** [comment]
Listbuilder toolbar notes: 

Add button/filter button: no content but the icon. Add titles for hover: ("Add", "Filters" @Blackbaud-ToddRoberts  let me know if you'd rather have something different). 

Search: On mobile it should turn into a button and behave like omnibar search (On click animate in an input with a dismiss button). There is a design enhancement for an x button on large screens which clears search text.

**Comment by Blackbaud-PatrickOFriel** [comment]
Note that this issue will consist of taking the card listbuilder and adding the ability to have a repeater view that can be switched between with the card view. At the end of this work there should be the ability for users to plug in custom views into the listbuilder

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.8.0](https://github.com/blackbaud/skyux/releases/tag/v1.8.0)
