### ISSUE TITLE
Update styling of <select> inputs

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#304]
https://blackbaudinc.box.com/s/8bfg18hq1qstifg92cwvr7tjr66izq27

Design approved
Matt Garbarino owns the design

**Comment by Blackbaud-PatrickOFriel** [comment]
For this, we will apply the styles possible (not all browsers will accept style changes for all parts of the select control).

**Comment by Blackbaud-PatrickOFriel** [comment]
Might be valuable to create a directive that wraps the select with html/css, like we do with bb-check. See [this](https://github.com/filamentgroup/select-css) for an example.

**Comment by Blackbaud-PatrickOFriel** [comment]
For now, updated `form-control` class to look nice in IE11. If this isn't sufficient, we can look at creating a wrapper directive like with `bb-check`

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.2](https://github.com/blackbaud/skyux/releases/tag/v1.6.2)
