### ISSUE TITLE
fix vertical alignment of omnibar help icon

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#318]
![help icon](https://cloud.githubusercontent.com/assets/13765813/13080052/06e67344-d495-11e5-9231-c51edfb29a67.png)

Top is current, bottom is fix

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ToddRoberts I do not believe we have control of that help widget. I think it's in Blue Steel's source.

**Comment by Blackbaud-BobbyEarl** [comment]
As @Blackbaud-PatrickOFriel mentioned, this styling is controlled via the Omnibar team.  I would suggest reaching out to them.
