### ISSUE TITLE
Support 2 column tile above tile dashboard

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#319]
We have a page in RE NXT where we have a single tile that spans both columns above a 2 column dashboard.  We have an issue with this wide column not matching the width of the 2 column dashboard below it, both on desktop and in the mobile view.  I'd like for Sky to provide some guidance for how to approach this, or possibly additional styles to make this supported.

Here is a link to a page showing the issue:
https://renxt.blackbaud.com/analyze/overview

Note that the top tile is not using the normal header section pattern, because it should still be collapsible.  We're also inside of a tab so I'm not completely sure a header would make sense here.  Either way, we're mostly looking to Sky for guidance on this.

**Comment by Blackbaud-MatthewBell** [comment]
Our use case for this no longer exists, based on some design changes on our page related to GoodData.  This may still be valuable functionality, but it is no longer a blocking issue.

**Comment by Blackbaud-PatrickOFriel** [comment]
Closing until there's a pressing use case for this
