### ISSUE TITLE
Angular upgrade

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#323]
1.5.x is available

**Comment by Blackbaud-RobertTester** [comment]
Any update on this issue?

**Comment by Blackbaud-PatrickOFriel** [comment]
Yep, it's currently in the milestone Sprint 4 (next week). We should start the upgrade and bump a minor version in Sky once it's in.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.0-0](https://github.com/blackbaud/skyux/releases/tag/v1.6.0-0). Will comment on this issue again when the prerelease is merged into master.
