### ISSUE TITLE
bbAutonumeric does not update model if the user pastes into the input

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#33]
From @Blackbaud-MichaelLopez

If a user copies and then pastes text into an input element that has bbAutonumeric applied, the model is not updated and autonumeric rules are never applied to this value.

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-MichaelLopez Are you seeing this behavior in a specific browser and can you provide a plunkr?  I'm unable to reproduce.
