### ISSUE TITLE
Sortable list component

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#330]
https://blackbaudinc.box.com/s/8yls64znigpshiq47e8a7ao4bontn236

Approved

Design contact: Rob Favre

**Comment by Blackbaud-PaulCrowder** [comment]
#406

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @blackbaud-johnly can you take a look at the documentation for this when you get a chance. It's under the `reorder` folder. We can make another issue specifically for the documentation if you'd like

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.14](https://github.com/blackbaud/skyux/releases/tag/v1.5.14)
