### ISSUE TITLE
Indicate required settings for grid component

### ISSUE THREAD

**Issue by Blackbaud-TimothyWittig** [blackbaud/skyux1#333]
The grid component has a large list of settings. It is not obvious which of these are required or not required. Missing a required field does not always manifest itself in an obvious way. It would be nice to see ahead of time what the required fields are in the documentation.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.10](https://github.com/blackbaud/skyux/releases/tag/v1.5.10)
