### ISSUE TITLE
grid: sort order will toggle when reordering a sorted column in Firefox.

### ISSUE THREAD

**Issue by Blackbaud-DaveMarino** [blackbaud/skyux1#334]
**Summary:** 
When reordering a sorted column in Firefox v. 44.0.2, the click event will sometimes fire causing the sort order of the grid to toggle.  This is easily reproducible using the grid's stock Plunker example.

*_Steps to reproduce: *_
1. Open the Plunker on the Grid documentation page in Firefox: http://skyux.developer.blackbaud.com/components/grids/
2.  Sort using the Name column
3. Drag the Name column to the right of the Instrument column
   _Note:_ you may have to change the column order a couple of times to see the issue.  It is pretty reliable, happening about 75% of the time.

**Other Notes:**
This only appears to be an issue in Firefox.  I did not see this behavior in Chrome, IE or Safari.
When setting a breakpoint in the initgrid function of grid.js, I can see the click event for the column that was moved at the root of the stack trace.  This does not appear to happen for either IE or Firefox.

Let me know if you need more details.

**Comment by Blackbaud-BobbyEarl** [comment]
In [v1.5.9](https://github.com/blackbaud/skyux/releases/tag/v1.5.9)
