### ISSUE TITLE
Improve validation on the avatar directive

### ISSUE THREAD

**Issue by Blackbaud-DanielHiggins** [blackbaud/skyux1#335]
The avatar directive doesn't allow showing a validation message if a user selects a file greater than the max file size or selects a file that isn't an image.  It would be helpful to have a way to report to a user why the file they selected isn't valid.

**Comment by Blackbaud-ToddRoberts** [comment]
Show a modal error alert. Styling should follow new generic error handling directive.

File is too large.
Please choose an image that is less than &lt;max filesize&gt;.

File is not an image.
Please choose an image file of type &lt;supported file types&gt;.

**Comment by Blackbaud-PaulCrowder** [comment]
Do we need any footer buttons on the error dialog?

**Comment by Blackbaud-ToddRoberts** [comment]
I think just a Close button

**Comment by Blackbaud-DanielHiggins** [comment]
One more enhancement request that I think makes sense to bundle with these changes:

I know you all had previously discussed having a consistent max file size but I was wondering if we could either revisit that or increase it significantly from 500k (I believe that's the current value).  We want to support allowing users to easily take pictures of constituents or use existing pictures and not have to resize it themselves.  Our original plan was to take the selected image, resize it using JS code that we already have and then upload both the original and the resized image.  We would then only show the resized image as the avatar source but would retain the original image.

**Comment by Blackbaud-PaulCrowder** [comment]
What should be the error dialog's header text?

**Comment by blackbaud-johnly** [comment]
I'm not sure how much space the header takes, but would "Cannot Display File" work?

**Comment by Blackbaud-ToddRoberts** [comment]
"Cannon upload file" I think would be more accurate

**Comment by Blackbaud-ToddRoberts** [comment]
Re: larger file sizes and pre-processing, Paul and I had talked about that but decided to wait on implementing it. If you think that is a critical piece of this, we should revisit that decision.

**Comment by Blackbaud-PaulCrowder** [comment]
Daniel, what would you propose the max file size be if we were to simply increase it rather than make it configurable?

**Comment by Blackbaud-DanielHiggins** [comment]
Our previous max file size for the constituent profile picture was 10MB.  Not sure if we did research to see if that's a reasonable limit or if we just chose it arbitrarily though.
