### ISSUE TITLE
BB-Check has unclickable area in Firefox on Windows

### ISSUE THREAD

**Issue by Blackbaud-JohnSarris** [blackbaud/skyux1#340]
BB-Checkbox > Grid filter modal > Firefox > Functional portion of checkbox (span) is not clickable because input element is in the way

[Unhelpful screenshot of me looking at the offending input element in the inspector](https://tfs.blackbaud.com/tfs/defaultcollection/workitemtracking/v1.0/attachfilehandler.ashx?filenameguid=11a77087-a502-40eb-b3a5-7bc9c6d809a1&filename=temp1455742941095.png).

Discovered while doing some crazy automation work. This only occurs in Firefox. I am not sure when it was introduced, but since it doesn't occur in RENXT PROD it should have been sometime after **v. 1.4.7**

In the grid filter modal, the input element is in the way of the span, which prevents the click from checking the checkbox. This also occurs when trying to uncheck the checkbox.

In checkboxes that are not in the grid filter modal, the input element is still in front of the span. However, for some reason the click works on those checkboxes.

When hovering over the input element, instead of the [pointy interaction finger cursor](https://cdn4.iconfinder.com/data/icons/pixel-web-part-1/512/pointer2-128.png) I see the [regular mouse pointer](https://cdn4.iconfinder.com/data/icons/social-productivity-line-art-5/128/mouse-pointer-128.png).

**Comment by Blackbaud-PatrickOFriel** [comment]
Can you give a plunker showing the problem?

**Comment by Blackbaud-JohnSarris** [comment]
I will put in my best effort as an uninitiated member of QA

**Comment by Blackbaud-JohnSarris** [comment]
It's reproducible in your checklist plunker: http://skyux.developer.blackbaud.com/components/checklist/
The List example shows the case where the click still works but the mouse pointer isn't in interaction mode or whatever.
The Grid example shows the case where the click does not work.

**Comment by Blackbaud-PatrickOFriel** [comment]
gotcha, maybe it only appears in windows, let me check it out

**Comment by Blackbaud-PatrickOFriel** [comment]
Yep, its a windows firefox only issue. I should have a fix out pretty soon.

**Comment by Blackbaud-JohnSarris** [comment]
Awesome

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey, join I have a fix waiting to go in master. If this is a bug that you need fixed before sky releases, the css to fix it is this:

```
.bb-check-checkbox,
.bb-check-radio {
  position: relative;
}
```

You can put that in one of your shell css files to fix the issue if you need it immediately

**Comment by Blackbaud-JohnSarris** [comment]
You're a legend Patrick

**Comment by Blackbaud-PatrickOFriel** [comment]
That's what I tell myself all the time

**Comment by Blackbaud-BobbyEarl** [comment]
In [v1.5.9](https://github.com/blackbaud/skyux/releases/tag/v1.5.9)
