### ISSUE TITLE
Very long column caption names breaks scrolling on mobile Safari in grid column chooser

### ISSUE THREAD

**Issue by Blackbaud-DanMiller** [blackbaud/skyux1#347]
### Expected behavior

I open the column chooser and swipe up to scroll down, and it should scroll down.
### Actual behavior

I open the column chooser and swipe up to scroll down, and it does not scroll down.
### Steps to reproduce
1. Have a very long column caption name (such that it would run off the side of the column chooser when viewing it in mobile Safari).
2. Open the column chooser for the grid.
3. Attempt to scroll down.
4. Notice that scrolling does not occur.

This was seen on an iPhone 5s. If the phone is rotated to landscape mode (such that the caption fits within the confines of the modal) scrolling works.
### Plunker

Open this on mobile Safari: [http://embed.plnkr.co/9TfCzFBtMCsDTVrYUwzQ/](Plunker)

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-DanMiller, the link to that plunker gives me a 404

**Comment by Blackbaud-DanMiller** [comment]
http://plnkr.co/edit/9TfCzFBtMCsDTVrYUwzQ?p=preview

Try opening the embedded view from there.

**Comment by Blackbaud-PatrickOFriel** [comment]
I am also seeing this behavior with very long descriptions

**Comment by Blackbaud-BobbyEarl** [comment]
In [v1.5.9](https://github.com/blackbaud/skyux/releases/tag/v1.5.9)
