### ISSUE TITLE
Update getting started guide to use new page summary component

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#358]
The record page section of the getting started guide uses a summary section that does not use the page summary component. It needs to be updated to use the page summary component and the wording probably needs to be tweaked to mention it and link to its documentation.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.12](https://github.com/blackbaud/skyux/releases/tag/v1.5.12)
