### ISSUE TITLE
bb-grid loading spinner centers on columns rather than viewport

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#36]
From @Blackbaud-LoriWeiss

Precondition:
Your list has more columns then can appear in the window, and there is scroll bar on the list.
1. Refresh list
2. Notice that the spinner is not centered in the browser

We think this is because the spinner is being centered by the width of the columns, even those that are off screen.

**Comment by Blackbaud-DaveMarino** [comment]
I'm seeing the same problem with rows.  In my case, the wait spinner is centering vertically in the grid.  As I click the load more button a few times, the spinner eventually scrolls out of view.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.8](https://github.com/blackbaud/skyux/releases/tag/v1.5.8)
