### ISSUE TITLE
extend wizard with number-only steps

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#360]
Add a mode for number-only steps in the wizard. This should be a configurable option, as well as the responsive solution when textual steps do not fit in allotted space (instead of horizontal scroll like now). 

Is it possible to extract the wizard components from the modal, to use with in-page forms? New products coming on are uncovering use cases where modals don't really work for some form flows.

https://blackbaudinc.box.com/s/xeknv4fdbk3k2hl3mc6dz8dxr0eiq143

design contact: adam funderburk

Approved

**Comment by Blackbaud-PatrickOFriel** [comment]
I believe the wizard should already work in in-line forms. All you need is to put the `bb-wizard` directive along with a `uib-tabset` directive.

**Comment by Blackbaud-ToddRoberts** [comment]
Ah ok, if that is the case we should think about modifying the documentation for Wizard since it makes it sound like it has to be used on a modal. Or maybe that is just a false inference on my part. @blackbaud-johnly what do you think?

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah reading the documentation, I would agree with that. The only thing different in a non-modal would be that the buttons might need some kind of footer area since we had that predefined space in the modal form.

**Comment by Blackbaud-ToddRoberts** [comment]
Yeah, footer action bar is on my to do list since they are implemented in several places but there is not a directive yet.

**Comment by blackbaud-johnly** [comment]
Do we want to call anything out in the documentation about using a wizard for inline forms? Or do we just need to remove the references to modal forms? In the body of the help topic, "modal" appears 6 times, and if we don't need to draw out a distinction between using the wizard with modal vs. inline forms, then I think we can just delete "modal" in all 6 instances.

**Comment by Blackbaud-PatrickOFriel** [comment]
Let me whip up a Plunker using wizard inline and see if there are any major differences. I don't anticipate any

**Comment by Blackbaud-PatrickOFriel** [comment]
http://plnkr.co/edit/4K6it78ZjFdsQlsbYwTB?p=preview

Hokay, actually implementing it in plunker, the functionality works, but I think it relies on bb-modal styling to make it look good. One part is the footer bar that doesn't look quite right. Another part is the default gray background color doesn't look fantastic. And the third part is the modal body padding of 15px all around makes it look a bit better, and that does not exist without the modal. So to make this work inline, we should probably make and effort to add some css to the wizard that'll make it look up to snuff. (part of this might also be our lack of styling around inline forms in general, white background and padding could occur within a bb-form-inline class if we so decide)

**Comment by Blackbaud-ToddRoberts** [comment]
Yeah we have to address inline forms in general. We haven't defined that yet, but can probably extract layout from AngelPoints implementation once they do it.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.21](https://github.com/blackbaud/skyux/releases/tag/v1.5.21)
