### ISSUE TITLE
Add a `columnsResized` event that is emitted when columns have been resized on the grid

### ISSUE THREAD

**Issue by Blackbaud-IanThomas** [blackbaud/skyux1#366]
When the user finishes resizing a column, it would be useful to have an event emitted from the scope that controllers can listen to and persist the column sizes for subsequent visits to the grid.

The use case here is that we have a grid view that users customize pretty heavily and want to save their changes.  Column width is the one missing piece.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.10](https://github.com/blackbaud/skyux/releases/tag/v1.5.10)
