### ISSUE TITLE
Is the filter flyout only available in grids?

### ISSUE THREAD

**Issue by Blackbaud-DanHamlin** [blackbaud/skyux1#368]
We were thinking we would be able to use the flyout on a page not realizing it was a part of the grid widget.  Is there a way to use it outside the context of a grid?

**Comment by Blackbaud-PatrickOFriel** [comment]
Right now there is not, but I think design was thinking of reworking grid filters. Am I correct @Blackbaud-ToddRoberts

**Comment by Blackbaud-ToddRoberts** [comment]
Yeah we are redoing filters, part of that would be extracting them from Grid so that they are generally usable.

**Comment by Blackbaud-DanHamlin** [comment]
Is there any timeline for that change?

**Comment by Blackbaud-ToddRoberts** [comment]
@Blackbaud-Robfavre was working on it for RE NXT but I am not sure where it is in their priority list.

**Comment by Blackbaud-Robfavre** [comment]
We have some initial designs for putting the filters into a modal, but that work is approximately nowhere on the RE NXT 2016 roadmap so I won't probably be getting to it for a while.  If someone else is so inclined I would be happy to help out.

**Comment by Blackbaud-ToddRoberts** [comment]
Ok. I should have more info about timeline after Friday in that case.

**Comment by Blackbaud-DanHamlin** [comment]
Thanks for the info.  I may be hitting you up for that help, depending on our product owner.
