### ISSUE TITLE
reInitGrid event listener

### ISSUE THREAD

**Issue by Blackbaud-IanThomas** [blackbaud/skyux1#369]
It would be great to have an event listener inside the grid directive that allowed controllers to manually reinitialize the grid.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.10](https://github.com/blackbaud/skyux/releases/tag/v1.5.10)

**Comment by nuander** [comment]
Could I please get an example of how reInitGrid would be triggered?  Is it fired on any particular element?

**Comment by Blackbaud-IanThomas** [comment]
@nuander You trigger it like this: `$scope.$broadcast("reInitGrid");` where `$scope` is the scope of your controller for the grid.
