### ISSUE TITLE
Missing documentation about free-jqgrid

### ISSUE THREAD

**Issue by Blackbaud-BrandonHay** [blackbaud/skyux1#37]
Hello,

I noticed after upgrading to the latest sky-ux that you guys are now using free-jqgrid as opposed to jqgrid in your code. I assume this is because jqgrid is no longer free to use anymore? It doesn't reflect this in the documentation http://skyux.docs.blackbaudhosting.com/documentation/grid/ so thought this might be something you would like to update for future users of sky-ux.

**Comment by Blackbaud-PatrickOFriel** [comment]
So that documentation was the internal site and is slightly out of date. Our public facing docs are up at http://skyux.developer.blackbaud.com/components/grid/ and it has the link going to the correct repo.

**Comment by Blackbaud-BrandonHay** [comment]
Thanks, Patrick.
