### ISSUE TITLE
UIB Dropdown Styling-Bottom Margin

### ISSUE THREAD

**Issue by Blackbaud-MitchellThomas** [blackbaud/skyux1#371]
### Expected behavior

When a dropdown menu extends below the bottom of the page when it is opened, the user can scroll to the new bottom of the window and clearly see their dropdown menu.
### Actual behavior

The dropdown menu touches the very bottom of the page, and it is hard to tell if the menu may actually extend beyond the bottom of the window but is being clipped. The styling at the bottom edge of the dropdown is very subtle when butted up against the bottom of the window.
### Steps to reproduce
1. Go to a page where a dropdown will open up at the bottom of the content and extend to beyond the previous bottom edge. This may require shrinking the browser window vertically for a page without much content.
2. Scroll to the new bottom of the window and note the lack of a gap between the dropdown and the bottom of the window
### Plunker

It can be reproduced from the plunker linked from the SKY UX docs.

http://skyux.developer.blackbaud.com/components/contextmenu/

**Comment by Blackbaud-PatrickOFriel** [comment]
http://plnkr.co/edit/cOM5fvo8nMp7doITyivj?p=preview here's an example of what this solution would look like. Just decrease the window height until the last dropdown opens below the visible screen. I don't think this change would be out of bounds, @Blackbaud-ToddRoberts ?

**Comment by Blackbaud-PatrickOFriel** [comment]
Another way to avoid this issue, is to use the dropup class like [here](http://plnkr.co/edit/UkoShWEktrizBM9AmGX4?p=preview) when your dropdown is the last content of the page.

**Comment by Blackbaud-ToddRoberts** [comment]
That fix seems to not work on Firefox, because when I look at it the bottom edge of the menu is still at the bottom of the viewport.

**Comment by Blackbaud-PatrickOFriel** [comment]
You're right, I'm seeing that in firefox as well. I'll explore a bit

**Comment by Blackbaud-PatrickOFriel** [comment]
Apparently firefox collapses margin-bottom to 0 if its the last element. Strange behavior...

**Comment by Blackbaud-PatrickOFriel** [comment]
Since that's firefox standard behavior there's not much we can do about it. I talked to Todd and we agreed that we'll put this fix in to help degrade gracefully in some browsers, but we'll recommend that if you are using a dropdown and you know that it will be one of the last items in the window, you should use the `drop-up` bootstrap class.

**Comment by Blackbaud-ToddRoberts** [comment]
Is it possible (with reasonable efficiency) to detect how close the item is to the bottom and switch it to a dropup automatically?

**Comment by Blackbaud-MitchellThomas** [comment]
The Firefox behavior is unfortunate, but for this issue, my opinion is that it's only worth as much time as an easy solution gets. It's very much a nice-to-have to me. The user can still do everything they need to do. If you guys think it's worth more effort, go for it, but I'm satisfied with it how Patrick has laid it out.

**Comment by Blackbaud-PatrickOFriel** [comment]
So I've been digging a bit and ui-bootstrap is currently working on smart positioning for things like popovers, dropdowns, etc. See [here](https://github.com/angular-ui/bootstrap/issues/4762). So if they're going to have automatic dropping up in a month, then I'd rather not double the effort unless it's real high priority

**Comment by Blackbaud-ToddRoberts** [comment]
Waiting for them to do it is fine with me ;)

**Comment by Blackbaud-MitchellThomas** [comment]
Works for me, too!

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.11](https://github.com/blackbaud/skyux/releases/tag/v1.5.11)
