### ISSUE TITLE
bb-page-summary image class has unnecessary margin-bottom

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#378]
### Expected behavior

There is a margin-bottom of 0px
### Actual behavior

There is a margin-bottom of 20px
### Steps to reproduce

View a bb-page-summary with a bb-page-summary-image
### Plunker

http://plnkr.co/edit/2xFLYAFoz02ERDepFkCR?p=preview

**Comment by Blackbaud-PaulCrowder** [comment]
What exactly was the problem the margin was causing?

**Comment by Blackbaud-PatrickOFriel** [comment]
If you go to the page summary demo and select only: show title, show subtitle, and show image, the margin at the bottom of the page summary is significantly larger than the margin above. The bb-page-summary-class and the bb-file-drop-col class were stacking to put a total of 30px below the image. It looked really awkward when I was trying to use the page-summary directive in the getting started documentation. Todd agreed that there didn't need to be margin below the image except when in small screen mode, because there will not be content directly below it and the bb-page-header class provides bottom padding for the page summary as a whole.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.11](https://github.com/blackbaud/skyux/releases/tag/v1.5.11)
