### ISSUE TITLE
list builder sorting

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#385]
Update how sorting works for list builder.

Proposal:
https://blackbaudinc.box.com/s/lzi68agvmkxvgcpqiylqg7xss8fiu1xz

Note that the styling has been updated a little bit in the view switcher design. Functionality should be the same as this proposal though.

Designer: Todd Roberts

Approved

**Comment by Blackbaud-PatrickOFriel** [comment]
Hokay @Blackbaud-ToddRoberts I'm looking at starting this story this week. The general picture looks like this:

Desktop: 
- Sort is a button with the `fa-sort` icon.
- Based on the [view switcher prototype](https://blackbaudinc.app.box.com/s/lo1hlvb16ktlo6nmq6zg94abbj7ququi), this will be to the right of the filter button.
- It opens a dropdown with the sort options.
- Label is at the top of the  dropdown options: "sort by"
- When used with a `bb-grid` there will be a way to add the sort direction arrow indication in the column header.
- Is there any indication that sort has been applied? (`bb-grid` will have a way to add the sort direction arrow in the column header, but card and repeater views don't have that)

<s>Mobile
- Sort is a button with the `fa-sort` icon.
- It opens a modal looking thing that takes up the whole page. ([Here](http://9zcaem.axshare.com/#p=ecom_style_-_phone) the modal looks to have the close button on the left and the header background color some sort of gray. Is this the final design?)
- Same question for sort indication like with tablet.</s>
- Edit: mobile should be the same as tablet and desktop

Anything I'm missing?

**Comment by Blackbaud-PatrickOFriel** [comment]
Another question about desktop sorting. What appears in the select box when no sort option has been selected?

**Comment by Blackbaud-ToddRoberts** [comment]
Style for the toolbar has changed:
https://blackbaudinc.box.com/s/1r15kbztbadtb0dzm8a5vrtezjp4b9i4

**Comment by Blackbaud-PatrickOFriel** [comment]
Updates:

The sort on all screen sizes should work like the sort depicted here: http://9zcaem.axshare.com/#p=ecom_style_-_tablet. (Button with `fa-sort` icon, clicking expands a dropdown with sort options).

Label at the top of the dropdown has "Sort by" text. Divider between label and clickable sort options.

The currently applied sort option will be highlighted in the dropdown

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-ToddRoberts can I get the css/classes for the "Sort by" header in the dropdown and the background highlight/text bold for the selected sort item. And I'm assuming the padding/spacing for sort items should be the same as those in regular dropdowns/context menu dropdowns?

**Comment by Blackbaud-ToddRoberts** [comment]
Try bb-subsection-heading for "Sort by," grid selected-row purple for the selected item background, and bb-emphasized for selected item text

**Comment by Blackbaud-PatrickOFriel** [comment]
For reference, here's what a mockup of the sort dropdown looks like: 
![screen shot 2016-09-06 at 3 31 02 pm](https://cloud.githubusercontent.com/assets/11620552/18287948/43aba176-7447-11e6-8ade-287746f5b470.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.3](https://github.com/blackbaud/skyux/releases/tag/v1.7.3)
