### ISSUE TITLE
BB-Grid: Ability to set current page

### ISSUE THREAD

**Issue by Blackbaud-JonBerthiaume** [blackbaud/skyux1#391]
It would be useful to have the ability to get/set the current page in a bbGrid's pagination. For example, we want to be able to save the user's current page so that if they navigate away from the grid and come back, the grid's pagination can be restored to its previous state instead of resetting to Page 1.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.14](https://github.com/blackbaud/skyux/releases/tag/v1.5.14)
