### ISSUE TITLE
Grid > Can't exclude portions of column template from search highlight

### ISSUE THREAD

**Issue by Blackbaud-TimothyWittig** [blackbaud/skyux1#397]
### Expected behavior

SkyUX's grid component supports column templates. As the creator of the column template, I know that certain portions should be searchable and other portions should not be. For example, read-only labels. I should be able to indicate which parts of the template are not searchable using the class 'bb-grid-no-search'.
### Actual behavior

'bb-grid-no-search' is ignored and elements with the class are still highlighted by grid search. 
### Steps to reproduce
1. Navigate to Plunker in link below.
2. Search for "Title". 
3. Observe that both Name column and Templated column contain highlighted text. 
4. Observe that in index.js, the template for the Templated column wraps "Title" in the "bb-grid-no-search" class.
### Plunker

http://plnkr.co/edit/R3Xu4hfhMu5VkvYKYPh7?p=preview
### Other notes

Culprit is here: https://github.com/blackbaud/skyux/blob/46d234563a6a744e99d269d796e6c269f9dc8591/js/sky/src/grids/grids.js#L651

Only looks for "td" elements with "bb-grid-no-search".

**Comment by Blackbaud-TimothyWittig** [comment]
While it addresses the specific example in the provided plunker, this change won't address the issue for any non-span element, which are all perfectly valid in a column template.

**Comment by Blackbaud-PatrickOFriel** [comment]
bbHighlight creates a `span` with the `highlight` class around text that you pass to it. So it should work for all cases. Unless I'm missing something obvious, which could be very possible

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.12](https://github.com/blackbaud/skyux/releases/tag/v1.5.12)
