### ISSUE TITLE
bb-avatar Initials Canvas Shown as Square Rather Than Circle When Viewing on an iPhone

### ISSUE THREAD

**Issue by Blackbaud-DanielHiggins** [blackbaud/skyux1#411]
On an iPhone 5S using Safari, the bb-avatar directive shows as a square rather than a circle when it shows the initials.  When the avatar shows an image, the image is shown as a circle as expected.

**Comment by Blackbaud-PatrickOFriel** [comment]
We're going to go ahead and close this because we cannot reproduce with our simulator on iPhone 5S using iOS 9.2.
