### ISSUE TITLE
ui-select single search does not gain focus in Firefox when ngAnimate is loaded

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#425]
### Expected behavior

Clicking in the search box should cause the search box to gain focus.
### Actual behavior

Clicking in the search box does not cause it to gain focus.
### Steps to reproduce

1.) Use ui-select and load ngAnimate
2.) Click into the search box.
3.) Notice searchbox does not gain focus. (It is a race condition it seems, but it happens very often.)

To see it is caused by ngAnimate, remove ngAnimate from the dependencies list in the plunker below.
### Plunker

http://plnkr.co/edit/QzkCWk5xm8K6HvpsGm78?p=preview

Tracking in Angular UI: https://github.com/angular-ui/ui-select/issues/1201

**Comment by Blackbaud-PatrickOFriel** [comment]
We're moving away from ui-select because it's an external library that has few active contributors anymore. It will be deprecated in the next few weeks and we recommend moving to use the bb-selectfield directive. However it looks like this can be mitigated by disabling ng-animate on the directive, which we can do.

**Comment by Blackbaud-MichaelLopez** [comment]
Yea that is all I was looking for. I rather Sky disable it than having to have several teams do it. Thanks!

**Comment by Blackbaud-PaulCrowder** [comment]
I'm not sure we should be fixing this.  We want to discourage the use of ui-select by deprecating it (it should probably be marked as such in the next release), so I want to make sure we're not directing resources to its continued support.

**Comment by Blackbaud-PatrickOFriel** [comment]
Closing this as we are deprecating ui-select as part of Sky. The above ui-select bug that @Blackbaud-MichaelLopez linked shows a workaround that should allow specific products to solve this problem if they continue to use the ui-select control.
