### ISSUE TITLE
Percent preset config for bb-autonumeric filter

### ISSUE THREAD

**Issue by Blackbaud-JeremyRyan** [blackbaud/skyux1#427]
### Expected behavior

Using `{{<value> | bb-autonumeric : 'percent'}}` should display the value with a percent sign
### Actual behavior

`'percent'` is not a supported preset

[autonumeric.js](http://www.decorplanit.com/plugin/) creates a percent format using aSign of `%` and pSign of `s`

**Comment by Blackbaud-PatrickOFriel** [comment]
Would your use case always show two decimal places? @Blackbaud-JeremyRyan

**Comment by Blackbaud-JeremyRyan** [comment]
No it should be localized and hopefully have a way to specify the number of decimal places.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.15](https://github.com/blackbaud/skyux/releases/tag/v1.5.15). We provide a base configuration with percent sign and no decimal places. You can override default settings by locale by changing the `bbAutonumericConfig` percent value. You can also specify options inline in the filter by passing a configuration object with jquery autonumeric options to the filter.
