### ISSUE TITLE
Modal: Programmatically close modal

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux1#432]
Add documentation to programmatically close a modal `$scope.$dismiss('cancel');`. I see documentation for `bbModal.open({})`, but nothing for programmatically closing the same modal.

**Comment by Blackbaud-BobbyEarl** [comment]
Curious what the resolution was?  Use `$uibModalInstance.close()`?

**Comment by Blackbaud-SteveBrush** [comment]
In your modal's controller, you can call `$scope.$dismiss('cancel');`. The initial reason I filed the issue was simply from a lack of documentation (at least on the SKYUX side). I ended up reading through the Angular Bootstrap documentation, which I assume you are expecting the consumers of SKYUX to be familiar with.
