### ISSUE TITLE
Usability issues with date field edit control

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [blackbaud/skyux1#438]
When the date control has a value, typing in the edit portion of the control shifts the cursor position to the end.  For example, if you want to change 1/7/2016 to 1/21/2016, you'd highlight the 7 and as soon you start typing the cursor moves to the end of 2016

**Comment by Blackbaud-PatrickOFriel** [comment]
This can be seen in the SkyUX documentation page for the non-custom validation datepicker

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.0-1](https://github.com/blackbaud/skyux/releases/tag/v1.6.0-1)
