### ISSUE TITLE
Checked indicator in bb-check gets left aligned if you put it in a bb-grid

### ISSUE THREAD

**Issue by Blackbaud-ChickLeiby** [blackbaud/skyux1#44]
The text-align: left set for TD in the sky css ends up applying down to the input it contains.  The result is that the checkmark/pip is to the left side of the containing square/circle rather than centered.  

I was able to address it by explicitly setting text-align: center in my site's css, but just thought you should know

**Comment by Blackbaud-PatrickOFriel** [comment]
Yep, the `text-align: center` is probably something that should be in our css for `bb-check` I'll take a look.
