### ISSUE TITLE
Build does not fail when branch coverage is less than 100%

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#444]
### Expected behavior

The Travis CI build should fail if the unit test code coverage stats for statements, branches, functions and lines are not all 100%
### Actual behavior

The Travis CI build should succeeds if the unit test code coverage stats for statements is 100% but branches is less than 100%
### Steps to reproduce

Get latest from master and run `grunt build test`.  Open the index.html file in the coverage/ folder and notice that both autonumeric/ and error/ have branch coverage of less than 100%.

**Comment by Blackbaud-PaulCrowder** [comment]
https://github.com/lemurheavy/coveralls-public/issues/31

One commenter mentioned switching to codecov.io.

**Comment by Blackbaud-BobbyEarl** [comment]
Testing implementation with Codecov via #454 worked well.  

Current code coverage is lower than expected as they don't support "optional documentation" in Istanbul comments.  https://github.com/codecov/support/issues/151

**Comment by Blackbaud-PatrickOFriel** [comment]
If this doesnt get address by codecov by May 16, we'll change our comments to fit their requirements

**Comment by Blackbaud-PatrickOFriel** [comment]
Changed our code coverage comments, waiting on codecov to release a fix which will respect `/*istanbul ignore next */` with functions
