### ISSUE TITLE
Border style on email field in modal doesn't match other fields

### ISSUE THREAD

**Issue by Blackbaud-SpencerMurphy** [blackbaud/skyux1#450]
### Expected behavior

I would expect an email field (input type=email) inside a modal to have the same styling as other input fields. 
### Actual behavior

There is a style (line 38 of _modals.scss) that changes the border style on email fields in modals. It changes the border color to a grey that does not match the other field inputs and overrides the red validation border causing it to look muted.
### Steps to reproduce

These are based on the plunker below
1. Open the modal  by clicking the open button
2. Notice that the email field border is darker than the field above
3. Type an invalid email address into the email field
4. Click into and out of the required field to get the required validation to happen.
5. Notice the difference between the two fields and the muted red of the email validation 
### Plunker

http://plnkr.co/edit/rKrdcLaIJ6nVAsVgBU5n?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.14](https://github.com/blackbaud/skyux/releases/tag/v1.5.14)
