### ISSUE TITLE
Pagination component does not correctly calculate height when tile is closed

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#458]
### Expected behavior

Pagination component can calculate height of the list when a closed tile is opened and the page list buttons do not bounce around as the user pages through the list.
### Actual behavior

The height is not calculated and the page list buttons bounce around.
### Steps to reproduce

Load a page with a tile that has a pagination component and have the tile closed during the page load. Next open the tile and see the height was never calculated.
### Plunker

http://plnkr.co/edit/P4zHSlqZIkPr6eyqnY0s?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
That's because the height of the component is 0 when display:none is applied. If you want to fix this put an ng-if around your pagination component that's set to true when the tile becomes visible.

**Comment by Blackbaud-MichaelLopez** [comment]
So I believe what other projects do is clone and position the element offscreen regardless of any css rules that applied and calculate the height there. This way regardless if the element is hidden, they can still calculate the height.

**Comment by Blackbaud-PatrickOFriel** [comment]
That is a possible solution. I do not think making changes to that directive will be high on our priority list, but you can submit a pull request with the change if you need it more immediately

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.15](https://github.com/blackbaud/skyux/releases/tag/v1.5.15)
