### ISSUE TITLE
currentCultureDateFormatString doesn't work well with angular localizable formats

### ISSUE THREAD

**Issue by BlackBaud-AlanGordon** [blackbaud/skyux1#462]
### Expected behavior

When setting `bbDatepickerConfig.currentCultureDateFormatString` to 'shortDate', bb-datepicker displays the date in the current locale's short date format, as described [here](https://docs.angularjs.org/api/ng/filter/date).
### Actual behavior

If shortDate is set, then it seems to use the shortDate for en-US, regardless of browser culture.
### Steps to reproduce
1. Attach a bb-datepicker to a Controller that sets `bbDatepickerConfig.currentCultureDateFormatString = 'shortDate';`
2. Run in a browser where the locale is set to United Kingdom
3. Set the date to May 28th
4. Check displayed date: "4/28/16" (should be "28/4/16")
### Plunker

http://plnkr.co/edit/zq45xuRq89jXQUOgE9im?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
We use the uib-datepicker-popup for our component (see https://angular-ui.github.io/bootstrap/#datepickerPopup) which only seems to accept the angular date formats using things like `MM/dd/yyyy` etc. I do not believe our documentation (or theirs really) properly conveys this. So we have two options: 
1. Update our documentation to reflect the current state of affairs. (Use formatted date with `M`, `d`, and `yyyy` that you set from momentjs or wherever you are setting/storing locale configuration)
2. Use momentjs or something else to translate shortDate, fullDate, etc to the proper configuration. 

Thoughts @Blackbaud-PaulCrowder, @Blackbaud-BobbyEarl , @Blackbaud-ToddRoberts

**Comment by Blackbaud-PatrickOFriel** [comment]
Looking more into UI-bootstrap datepicker, it seems that it should still work with `shortDate` I'll dig in further

**Comment by BlackBaud-AlanGordon** [comment]
I've been doing some digging, and this may be a problem in angularjs not supporting dynamic locales out of the box, not with your control specifically.

**Comment by Blackbaud-PatrickOFriel** [comment]
I'll keep this open for now. Today and Monday I'll be looking into another issue with `bb-datepicker` that I thought might be related to yours so I'll report back

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah after digging in a bit more, I do not think that the control we're using handles the `shortDate`, `medium`, `short`, date strings properly. We'll make a note of it in the documentation and users should use the bbDatepickerConfig to set the proper `MM/dd/yyyy` type format for a locale that they can retrieve.
