### ISSUE TITLE
Can't check the checkbox itself on iOS Safari

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#471]
### Expected behavior

Tapping a `bb-check` on iOS Safari should toggle the checked state of the checkbox.
### Actual behavior

Tapping a `bb-check` on iOS Safari doesn't toggle the checked state but does change the outline of the checkbox.  Tapping the checkbox's label does work.
### Steps to reproduce
- Navigate to Plunker below
- Tap a checkbox
### Plunker

http://plnkr.co/edit/Vlx2klOIiqezAYF1cpYO?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.15](https://github.com/blackbaud/skyux/releases/tag/v1.5.15)
