### ISSUE TITLE
Selecting a radio button on iOS Safari doesn't deselect other options

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#472]
### Expected behavior

Tapping a radio button with the `bb-check` directive should uncheck the currently selected option.
### Actual behavior

Tapping a radio button with the `bb-check` directive doesn't uncheck the currently selected option.  Tapping the label for the radio button does uncheck the currently selected option.
### Steps to reproduce
- Navigate to Plunker below
- Tap on a radio button that is not selected
### Plunker

http://plnkr.co/edit/Vlx2klOIiqezAYF1cpYO?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.15](https://github.com/blackbaud/skyux/releases/tag/v1.5.15)
