### ISSUE TITLE
Unable To Check If Datepicker With bb-custom-validation Specified Is Valid On Submit When Submit Triggered By Enter Key

### ISSUE THREAD

**Issue by Blackbaud-DanielHiggins** [blackbaud/skyux1#475]
### Expected behavior

The datepicker with bb-custom-validation specified should have validation triggered using the current datepicker value when the form is submitted by a user pressing the Enter key.
### Actual behavior

Currently, the datepicker with bb-custom-validation specified only updates the model when the control loses focus.  If the user submits a form by pressing the Enter key and an invalid date is specified, the form may still be marked as valid in the submit handler because the model hasn't been updated yet.
### Steps to reproduce
1. Add a datepicker to a form and set bb-custom-validation on it
2. Specify a submit handler that only performs an action if the form is valid
3. Enter an invalid date and, before leaving the control, press Enter
4. The action in the submit handler will have been triggered despite the check to ensure the form is valid
### Plunker

http://plnkr.co/edit/HHLR8w?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.16](https://github.com/blackbaud/skyux/releases/tag/v1.5.16)
