### ISSUE TITLE
checklist should focus the searchbox when it is present

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#476]
### Expected behavior

When the checklist is opened on a modal, it should focus the searchbox if it is present.
### Actual behavior

Does not focus.
### Steps to reproduce

Look at selectfield component demo page. Open selectfield. Notice the searchbox is not focused on checklist.
### Plunker

http://plnkr.co/edit/PVNjsFPV8W5WBqP9DTCc?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-MichaelLopez can you add a plunker to this issue. It allows us to have a versioned example of the existing behavior

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.18](https://github.com/blackbaud/skyux/releases/tag/v1.5.18)
