### ISSUE TITLE
Clicking a disabled menu item in a context menu still performs the action

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#479]
### Expected behavior

Clicking a disabled menu item in a context menu has no effect.
### Actual behavior

Clicking a disabled menu item in a context menu performs the action assigned to the menu item.
### Steps to reproduce
- Navigate to the Plunker below.
- Click the context menu button, then click the "Action Above" menu item.  Notice that the text next to "Last action clicked" is now "Action Above".
- Click the context menu button again, then click the disabled "Action Below" menu item.  Notice that the text next to "Last action clicked" is now "Action Below."  This text should not have changed as a result of clicking the disabled item.
### Plunker

http://plnkr.co/edit/w9VajsPoEpGQpb271yqc?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.19](https://github.com/blackbaud/skyux/releases/tag/v1.5.19)
