### ISSUE TITLE
Avatar launches the image picker when scrolling on mobile.

### ISSUE THREAD

**Issue by Blackbaud-JonathanBell** [blackbaud/skyux1#481]
### Expected behavior

Mobile swap doesn't launch picker.
### Actual behavior

When I scroll on mobile by swiping over the avatar, the picture picker launches.
### Plunker

http://plnkr.co/edit/pM9ZhARj9VtPoTHKq3xP?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Are these expected and actual behaviors reversed? And if you don't mind, could you please include a plunker? Even if it's just taking the plunker straight from the documentation page and saving it, it gives us a versioned reference to work against.

**Comment by Blackbaud-JonathanBell** [comment]
Updated. Sorry about that!

**Comment by Blackbaud-PaulCrowder** [comment]
This issue exists in the underlying `bb-file-drop` component and is not unique to `bb-avatar`.  This is also only reproducible on Android or Chrome desktop's mobile simulator.  It's not a problem on iOS.

**Comment by Blackbaud-PaulCrowder** [comment]
Upgrading to latest version of `ng-file-upload` (12.0.4) fixes the issue but introduces breaking changes.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.16](https://github.com/blackbaud/skyux/releases/tag/v1.5.16)
