### ISSUE TITLE
Resizing a page with a dropdown menu in a tabset results in the dropdown options being moved

### ISSUE THREAD

**Issue by Blackbaud-JackieKirchhoff** [blackbaud/skyux1#482]
### Expected behavior

The dropdown options should show up only when the dropdown menu is clicked and should appear below the dropdown menu.
### Actual behavior

The dropdown options are added to the tab dropdown when the tabs are collapsed and they sometimes appear between the tab headers and the dropdown menu.
### Steps to reproduce

In the plunker, shrink the tabs until they collapse into one.  Open the Tab 1 dropdown and notice the dropdown options appear in the tab dropdown and the other tabs do not appear in the tab dropdown.  Expand the tabs so they are no longer collapsed.  Notice the dropdown options appear 3 times between Tab 1 and the dropdown menu.
### Plunker

http://plnkr.co/edit/nn6iHucb5IwLx5NX9k6l?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.15](https://github.com/blackbaud/skyux/releases/tag/v1.5.15)
