### ISSUE TITLE
bb-page-summary-status badges overlap when wrapping

### ISSUE THREAD

**Issue by Blackbaud-JohnHolder** [blackbaud/skyux1#488]
SkyUx 1.5.13
When multiple status badges are in the bb-page-summary-status section of a bb-page-summary, I would not expect them to overlap when they wrap to a new row

status badges overlap when they wrap to a new line

Add more than one status badge and resize browser until a badge wraps to the next line

[plunker](http://plnkr.co/edit/LVsO2EOFcjJxXR61c3F0?p=info)

**Comment by Blackbaud-PatrickOFriel** [comment]
Looks like a problem with label styling in general and the css to make labels behave appropriately is adding

```
.label {
  line-height:  inherit;
  margin-bottom: 5px;
  display: inline-block;
}
```

Someone else can sanity check me if I'm thinking about this wrong.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.18](https://github.com/blackbaud/skyux/releases/tag/v1.5.18)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [1.5.19](https://github.com/blackbaud/skyux/releases/tag/v1.5.19) changed the line height back to original size, and created the `bb-label-list` class that can be placed on containers of labels to prevent the visual issues described by @Blackbaud-JohnHolder
