### ISSUE TITLE
Create component to standardize error messaging

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#49]
Based on the work Rob and Steve did for RE.

Layout templates
Default messaging by error type
Ability to override content

https://blackbaudinc.box.com/s/9ige6etpfr8wtbqqg59zx5zh66re0kia
The Excel sheet has the error types and messages. Screenshots show examples. IMO the default we provide should be message only, if teams want to include images they would provide custom content.

**Comment by Blackbaud-PatrickOFriel** [comment]
So I'm looking at the page error indication, and it shows an image of a bird. Is this something we're including in Sky for everyone to use? and if so, is there a reference to the image I can use.

**Comment by Blackbaud-PatrickOFriel** [comment]
Also, I'm going to start breaking these scenarios out into separate issues

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ToddRoberts I've seen pretty much 4 sections in all of these errors.
1. Image - optional
2. Error header - not optional
3. Error description - not optional
4. Error action button - optional (also could be either white secondary or blue primary button, do we want to restrict this to being either white or blue, not giving the option?)

Does this mesh with what you're seeing?

**Comment by Blackbaud-ToddRoberts** [comment]
Those sections look correct.

As for action buttons, we would want full-page errors to be primary, tile errors to be secondary. Is that possible programmatically or does that have to be an feature implementation choice?

**Comment by Blackbaud-PatrickOFriel** [comment]
Probably feature implementation, but I was thinking we would set defaults for tile, page, and modal errors that can be overridden by products in some sort of configuration object. Does that make sense?

**Comment by Blackbaud-ToddRoberts** [comment]
Yeah, in that case I would say page and modal actions should be primary, tile should be secondary. That should be most inline with the general goal of only having one primary action per page.

**Comment by Blackbaud-PatrickOFriel** [comment]
Sounds good

**Comment by Blackbaud-PatrickOFriel** [comment]
Styling wise, the error header looks like its some grey color in the screenshot. Should that just be an `<h3>` like in our unauthorized message? And is there any more specific styling I should know about for this control?

**Comment by Blackbaud-ToddRoberts** [comment]
It should not be an h3, because semantically that's not what it is. I know it doesn't help you now but this morning we kicked off a UX project to rationalize our typography... Given that is it easiest to grab the styling off the mockup and go back and change it once the typography work is done?

**Comment by Blackbaud-PatrickOFriel** [comment]
Sure go ahead and give me the styling and I'll try to figure out what's what

**Comment by Blackbaud-ToddRoberts** [comment]
Looking at it, I think the gray is an artifact of the design being done before we changed the base body text color. Just use the base dark gray. Header is 13px bold. Explanation is 13px regular.

**Comment by Blackbaud-PatrickOFriel** [comment]
Gotcha. Do you have your hands on any image I can use in the demo?

**Comment by Blackbaud-ToddRoberts** [comment]
I would suggest the bird with the broken arm that RE is using. Rob suggested that John Bell could point you to that file.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.8](https://github.com/blackbaud/skyux/releases/tag/v1.5.8)
