### ISSUE TITLE
bb-autonumeric will switch focus on ngModel change

### ISSUE THREAD

**Issue by Blackbaud-JohnHolder** [blackbaud/skyux1#493]
SkyUx 1.5.13
bb-autonumeric should not focus an element when the underlying ngModel value changes

if the ngModel changes, the bb-autonumeric will attempt to set the selection state which results in focus'ing the input element - it should only do this if the input element already has focus.

add a bb-autonumeric bound to ngModel foo.value then add another input bound to same ngModel - change the second input - focus will shift to first input

[plunker](http://plnkr.co/edit/58b3jsaxTK860AK7X9xr?p=preview)

**Comment by Blackbaud-PatrickOFriel** [comment]
Just curious, what's the use case for having the `ng-model` for two different inputs tied to the same variable?

**Comment by Blackbaud-JohnHolder** [comment]
For example if you have 'Discount amount' and 'Discount percent' fields - entering value in one will recalculate the other and set its model value - in this case, the recalc would have a negative side effect of setting focus to the discount amount field.  Besides this actual use case, in practice, in FENxt, clicking from a changed bb-autonumeric field to another input field will potentially exihibit this behavior since this behavior is tied to a $timeout - there is no guarantee that the model change will occur while the original input field has focus.

**Comment by Blackbaud-PatrickOFriel** [comment]
Gotcha, thanks for the info!

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.16](https://github.com/blackbaud/skyux/releases/tag/v1.5.16)
