### ISSUE TITLE
When there is a single line of text with no breaks, the text overflows the reorder row

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#494]
### Expected behavior

Reorder row can correctly handle long unbroken text strings
### Actual behavior

It does not and the text overflows
### Steps to reproduce

Add long text to title property and see the overflow happen.
### Plunker

http://plnkr.co/edit/LKLpFqUikMeWdGQYsJLW?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.16](https://github.com/blackbaud/skyux/releases/tag/v1.5.16)
