### ISSUE TITLE
Textexpand text overflows parent in Firefox and IE11 when text does not break

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#498]
### Expected behavior

The textexpand should not overflow the parent.
### Actual behavior

The textexpand overflows the parent.
### Steps to reproduce

Place a textexpand element inside a container with a width. Observe the text overflows the parent.
Notice in chrome, no overflow happens.
### Plunker

http://plnkr.co/edit/B1hCGuehKB2zOCIr8zAg?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.16](https://github.com/blackbaud/skyux/releases/tag/v1.5.16)
