### ISSUE TITLE
wizard steps overlap eachother on smaller viewports

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#504]
### Expected behavior

The steps to do not overlap
### Actual behavior

The steps overlap.
### Steps to reproduce

View the wizard control on a small screen that causes the steps to drop below one another.
### Plunker

![wizard_pixel_overlap](https://cloud.githubusercontent.com/assets/11994579/14561899/91b994bc-02e7-11e6-967e-8ad8353f1c7c.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
https://github.com/blackbaud/skyux/issues/360

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.21](https://github.com/blackbaud/skyux/releases/tag/v1.5.21)
