### ISSUE TITLE
4 directional icon is weird for one dimensional list

### ISSUE THREAD

**Issue by Blackbaud-HalleyCoplin** [blackbaud/skyux1#506]
### Expected behavior

If you can only move items up and down in a list, the icon should be representative of that. The current icon looks cluttered and misleading when actually used in a one dimensional list reorder design (see prototype image for reordering constituent codes below)
![attachfilehandler](https://cloud.githubusercontent.com/assets/12241630/14568932/bc1ed8d0-0309-11e6-8a93-9f2f667968d8.png)
### Actual behavior

There is a 4 way arrow icon: http://skyux.developer.blackbaud.com/components/reorder/

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ToddRoberts

**Comment by Blackbaud-ToddRoberts** [comment]
The original design was for the vertical arrows only, but that had an issue of also being used for web components that can be resized. I don't think having the cross arrows will be confusing (if users are having trouble of course we can change it), and we are going to be replacing the existing drag icon on tiles with cross arrows so the affordance of draggability will be consistent.

**Comment by Blackbaud-HalleyCoplin** [comment]
What about making it a configurable option? I get the reusability when talking about moving tiles around and such, but it still looks a bit cluttered on a one dimensional list.

**Comment by Blackbaud-ToddRoberts** [comment]
We're looking at toning down the icon (smaller size and/or lighter gray) so that it is less visually prominent but still consistent with other drag handles.

**Comment by Blackbaud-HalleyCoplin** [comment]
I could live with that :+1:

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.18](https://github.com/blackbaud/skyux/releases/tag/v1.5.18)
