### ISSUE TITLE
Sky version: 1.4.1 - bbToast visual bug

### ISSUE THREAD

**Issue by Blackbaud-BrandonHay** [blackbaud/skyux1#508]
### Expected behavior

Up until a little while ago, our bb toast messages were executing fine with the expected behavior (a simple pop up message appears in the bottom right corner of the screen). Lately we have noticed that the message now appears at the top of the screen and is full width (see screenshot in Actual Behavior).
### Actual behavior

![image](https://cloud.githubusercontent.com/assets/11929859/14610159/b3545e0c-055a-11e6-913e-f1c7ea8e85d3.png)
### Steps to reproduce

Execute `bbToast.open({message: "Some message"});`
### Plunker

I'm not sure how to reference an old version of sky in this plunker from your CDN...

I realize I could (and probably will) just update sky on my project and use the new bb-toast style, but I'm wondering if there is any knowledge about what may have happened to the previous version's bb-toast?

Thanks,
- Brandon

**Comment by Blackbaud-PatrickOFriel** [comment]
Here's a plunker with toasts in v1.4.1, everything seems to be working fine here http://plnkr.co/edit/rB26HFzsF7udGmbTMgYN?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Closing from lack of response/already having updated toasts at this point. Feel free to open a new issue if you have problems with the toasts in the current version of SkyUX
