### ISSUE TITLE
Scroll issue using bb-pagination inside a modal

### ISSUE THREAD

**Issue by ghost** [blackbaud/skyux1#509]
### Expected behavior

Would expect to auto-scroll to the top of the content on each page 
### Actual behavior

Focus stays at the bottom of the page where pagination control lives.  This is especially problematic when the last page contains a small amount of content because it appears to be empty.
### Plunker

http://plnkr.co/edit/AVYa1TGkobr92Ou5hSvJ?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
The only reason the bb-pagination control exists is to not cause any jumping when using paging. I would use the `uib-pagination` directive if you do not want that behavior

**Comment by ghost** [comment]
good call...swapped out bb-pagination for the base directive and got desired behavior
