### ISSUE TITLE
(Grids) Toolbar and grid headers do not scroll properly inside of modals

### ISSUE THREAD

**Issue by Blackbaud-DavidKerr** [blackbaud/skyux1#514]
A grid inside of a modal has an issue where the toolbar and column headers do not float as the user scrolls up/down on the modal. Additionally, scrolling horizontally causes the headers to become visually displaced.
### Expected behavior

The toolbar+headers scroll/float like in the examples shown here.
http://skyux.developer.blackbaud.com/components/grids/
### Steps to reproduce

http://plnkr.co/edit/qyk2Nrd7aZKoeDh0DDyG?p=preview
In the Plunker demo, open the modal and load enough rows to allow for vertical scrolling in the modal. Notice that the headers+toolbar aren't floating at the top. If you scroll horizontally while the header isn't visible, the header will become visible but will be displaced.

**Comment by Blackbaud-ToddRoberts** [comment]
What is the specific scenario where you are using the grid in a modal? Is there a build or prototype to see it in context?

**Comment by Blackbaud-DavidKerr** [comment]
Hi Todd,

We're trying to show a list of invoices inside of a modal. This is just a grid, not a list builder.
Prototype screen: https://tfs.blackbaud.com/tfs/defaultcollection/workitemtracking/v1.0/attachfilehandler.ashx?filenameguid=80127c3e-7a14-45ae-9bff-593250b84918&filename=screen%20shot%202016-04-20%20at%201.59.56%20pm.png

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-DavidKerr the ability to use `bb-grid` within modals is not a scenario that we currently support. The viewkeeper functionality that `bb-grid` relies on for the floating headers and multi-select action bar watches for the window scroll event to work properly. When placed in a modal, the window does not scroll, instead the parent modal-body is scrolled. When we create the patterns for in-page forms, we'll ensure that `bb-grid` works as expected.
