### ISSUE TITLE
When Choosing a Date In Datepicker with Custom Validation, Date Isn't Valididated Until Datepicker Loses Focus

### ISSUE THREAD

**Issue by Blackbaud-DanielHiggins** [blackbaud/skyux1#520]
### Expected behavior

When a user is interacting with a datepicker with bb-custom-validation set and the user selects a date using the calendar control, clicking a date should trigger validation.
### Actual behavior

The custom validation method is only triggered when the datepicker loses focus.
### Steps to reproduce
1. Have a datepicker with bb-custom-validation set on a form and have the bb-custom-validation method be asynchronous
2. Select a date using the calendar control
3. Click a button to trigger form submit
4. Notice that the form isn't valid yet because the validation is still in progress.  The form submit button has to be clicked again to actually submit the form, causing confusion for the user.
### Plunker

http://plnkr.co/edit/Bqx5PR?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.20](https://github.com/blackbaud/skyux/releases/tag/v1.5.20)
