### ISSUE TITLE
Grid - Clear search control value

### ISSUE THREAD

**Issue by Blackbaud-ScottVossen** [blackbaud/skyux1#521]
### Expected behavior

I'd like to be able to clear the search control value. After discussing on slack, I'm told this should likely happen when we clear the gridOptions.searchText property, but currently does not.
### Actual behavior

Clearing the gridOptions.searchText property binding works, but the search input control's value is not updated and still shows the old search string.
### Steps to reproduce

1) Do a search
2) Fire some code to set gridOptions.searchText = "";
3) Observe the search control is not updated
### Plunker

http://plnkr.co/aXyfAXZ1NeMABxMlgYUY

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.20](https://github.com/blackbaud/skyux/releases/tag/v1.5.20)
