### ISSUE TITLE
reorder component in safari browser on mac: long non-breaking text causes top link to overflow and be cut off on rows

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#522]
### Expected behavior

The top link is not cut off
### Actual behavior

The top link is cut off
### Steps to reproduce

Provide title with long non-breaking text, observe it causes the top link to be cut off.
### Plunker

http://plnkr.co/edit/LKLpFqUikMeWdGQYsJLW?p=preview

I'm guessing safari is not handling the flex layout correctly. This is working in all other major browsers.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.20](https://github.com/blackbaud/skyux/releases/tag/v1.5.20)
