### ISSUE TITLE
X to close filter bubble not properly aligned in IE

### ISSUE THREAD

**Issue by Blackbaud-JackieKirchhoff** [blackbaud/skyux1#527]
### Expected behavior

The X should be in the filter bubble
### Actual behavior

The X appears below the filter bubble
### Steps to reproduce

Open the plunker in IE and apply a filter.  Notice the X appears below the filter bubble.  If you apply filters again then the X will move to be in the filter bubble, but if you clear filters and apply a filter then the X will again be below the filter bubble.
### Plunker

http://plnkr.co/edit/huIO4KJJxMmCupyuG3yu?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.20](https://github.com/blackbaud/skyux/releases/tag/v1.5.20)
