### ISSUE TITLE
Mobile > IOS > Long tab name causes scrolling on page

### ISSUE THREAD

**Issue by Blackbaud-LoriWeiss** [blackbaud/skyux1#53]
This is reproducable on the RE NXT Lists page: 
1. on iphone save a list with a name that is 50 characters
2. notice that the list name on the tab extends past the grid below it

Notes from support:
While testing the new save feature for lists in CDEV, I noticed a gap between the list and the screen.

It appears that when the list name is using close to or the full characters (50) the page does not fit to scale.

This only appears using a mobile device and does not happen when using a desktop computer

![image](https://cloud.githubusercontent.com/assets/12037781/11130633/0e392f24-8954-11e5-846e-100c7658673f.png)

This was test on a iPhone 5s (iOS 9) and was duplicated in Chrome and Safari

**Comment by Blackbaud-PaulCrowder** [comment]
Please provide a Plunker reproducing the issue.

**Comment by Blackbaud-LoriWeiss** [comment]
http://plnkr.co/edit/RISemAupCsTpYHttKuVu?p=preview

I don't have an IPhone but there is a plunker with a tab with a really long name.

**Comment by Blackbaud-PaulCrowder** [comment]
My proposed fix is that when the window size changes we fit all the visible tabs into the available window width, accounting for the presence of the add and open buttons.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.6](https://github.com/blackbaud/skyux/releases/tag/v1.4.6)
