### ISSUE TITLE
wizard component: the wizard should scroll to the top of each step

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#540]
### Expected behavior

When next/previous are clicked, the wizard should scroll to the top of that step.
### Actual behavior

The wizard remains scrolled at the current position on the next/previous step.
### Steps to reproduce

Have wizard with long step contents
### Plunker

http://plnkr.co/edit/YxgLqACKrXeihdZdYSQC?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Note: this a firefox-only issue. The wizard scrolls to the top after each step in chrome, safari, and ie

**Comment by Blackbaud-ToddRoberts** [comment]
It seems that Next works properly except in Firefox, but Previous does not do this.

**Comment by Blackbaud-PatrickOFriel** [comment]
Solution is probably to use the scrollintoview directive within wizard. We can look at bringing this into planning next week

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.2](https://github.com/blackbaud/skyux/releases/tag/v1.7.2)

**Comment by Blackbaud-PatrickOFriel** [comment]
See [demo](http://skyux.developer.blackbaud.com/components/wizard/) for example
