### ISSUE TITLE
Grid - searching for a value that matches every item on the grid doesn't highlight that matched value

### ISSUE THREAD

**Issue by Blackbaud-LuisBello** [blackbaud/skyux1#545]
### Expected behavior

When searching on a value that matches every item in the grid, the search should still highlight every value that matches the search string
### Actual behavior

If a search text value matches on every item in the grid, the grid is not updated and the matched values are not highlighted
### Steps to reproduce
1. In the Plunker below, search for '00' in the grid
2. Observe that every item shown has '00' as part of their Date field. However they are not highlighted.
3. Now search for 'John'. Observe the grid correctly updates to one matched item and 'John' is highlighted yellow. 
4. Search for '00' again.This time the grid shows all the items, but with the 00's in the Dates highlighted.
### Plunker

http://plnkr.co/fw5EEoLhDrOO54kutGNT

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah, a quick look at a code looks like the highlight functionality is only invoked after grid data is reloaded. So a search change that doesn't alter the rows won't do anything. Got a fix prepared that should be in soon

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.21](https://github.com/blackbaud/skyux/releases/tag/v1.5.21)
