### ISSUE TITLE
Invalid input fields do not have correct styling

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#55]
On modal forms, the pink focused box shadow stays on the input element after the user has tabbed away from the input. In bootstrap, if the user tabs out of the field, the box shadow is removed. You can see the behavior below. I think the correct behavior would be to remove the box shadow like bootstrap as it is supposed to imply that the element is focused.

http://plnkr.co/edit/apd3zI75ezovJSoyBkKb?p=preview
http://getbootstrap.com/css/#forms-control-validation

On modal forms with freeform inputs, the pink hue remains, but the red border is removed when the user tabs out of the input field.

http://plnkr.co/edit/qLqqGdMNp3u47t6RJg1L?p=preview

The below rule is causing the problem.

.bb-modal-content-wrapper input[type=freeform]{
    border: 1px solid #ddd;
    font-size: 13px;
    -webkit-appearance: none;
}.

**Comment by Blackbaud-PatrickOFriel** [comment]
For this issue we said that we want the red border and shadow to be there when the user leaves the input, but we did not want the red border and shadow to be visible when the user is actually typing in the input is that correct, @Blackbaud-ToddRoberts?

**Comment by Blackbaud-ToddRoberts** [comment]
The errored field should switch to have the blue border/shadow once the field is dirty. When the user leaves the field, it should have normal gray border since we don't know if it is an error state (unless validation runs on loss of focus and re-applies the red).

**Comment by Blackbaud-PatrickOFriel** [comment]
Validation should run on loss of focus as opposed to on save, but cool, I'll take care of making that change and making sure that type=freeform is taken care of consistently @Blackbaud-MikeLopez

**Comment by Blackbaud-MichaelLopez** [comment]
@Blackbaud-PatrickOFriel is freeform something that is supported? I'm not sure where that comes from, I don't believe its part of any standards?

**Comment by Blackbaud-PatrickOFriel** [comment]
I'm not sure I've ever heard of it actually. Any reason why it wouldn't be `type=text` in that case?

**Comment by Blackbaud-MichaelLopez** [comment]
Yea this is code we inherited, it might have been a pattern from the old theme sky was using, but now that sky isn't using that theme, sky can probably begin deprecating any styles using it. I changed it to type=text to get around this bug and I'm not going to change it back.

**Comment by Blackbaud-PatrickOFriel** [comment]
I think that's for the best, I'll go ahead and deprecate it in our next patch release and take it out in our next minor release. Thanks Mike

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.7](https://github.com/blackbaud/skyux/releases/tag/v1.4.7)
