### ISSUE TITLE
Grid templated columns broken

### ISSUE THREAD

**Issue by Blackbaud-DanHamlin** [blackbaud/skyux1#550]
Moving from 1.4.x to 1.5.x resulted in the following:
### Expected behavior

Templated grid column should get their data from that mapped in the column's 'jsonmap' property.
### Actual behavior

This has changed to be using the column's 'name' property, instead.
### Steps to reproduce

Set up grid with templated column.
Set jsonmap property to define what data should be used in template.
Observe unpopulated template appears in grid column cells.
### Plunker

http://plnkr.co/edit/B93v5zn6o3TvAE90Srwu?p=preview
on plunkr it seems to accept either jsonmap or name for setting the data for a templated column.
locally, jsonmap will not work.

**Comment by Blackbaud-PatrickOFriel** [comment]
So after investigating this with Dan we found that the problems arise when you have the `name` property of a column set to a string that's the same as a different property in your data set. JQGrid doesn't consider name unique at this point and will cause confusing things to happen with name and jsonmap. We'll take action on this issue by updating our documentation to warn developers about this JQGrid quirk.
