### ISSUE TITLE
bbFileItem isFile() returns true if item.size is "" or null

### ISSUE THREAD

**Issue by Blackbaud-SeanLatif** [blackbaud/skyux1#557]
### Expected behavior

bbFileItem's isFile function returns false if the item's size is an empty string or null
### Actual behavior

bbFileItem's isFile function return true if the item's size is an empty string or null
### Steps to reproduce

Provide bbFileItem with an item that has a size property of an empty string or null
### Plunker

http://plnkr.co/edit/RxUxz4h1awNv9MjkMocp?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Can you please add a plunker to this issue that reproduces the problem? This allows us to have a versioned instance of the problem. You can work off of the File Attachments "Try in Plunker" example at http://skyux.developer.blackbaud.com/components/fileattachments/ if you need a place to get started.

Thanks!

**Comment by Blackbaud-SeanLatif** [comment]
Yes, I've updated the issue with the Plunker. Thank you for taking the time to look at it; it's not a critical issue.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.22](https://github.com/blackbaud/skyux/releases/tag/v1.5.22)
