### ISSUE TITLE
Fix color of "success" styles

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#558]
In some places "success" status is using blue, but should use green.
Needs to be updated for .text-success and .label-success; alerts and toasts are correct.

**Comment by josh-channin** [comment]
@Blackbaud-ToddRoberts I'm looking in _badgeslabels.scss right now, and in addition to label-success being set to blue which I'm about to fix, label-primary is set to green. I'd assume that should also be fixed?

**Comment by Blackbaud-ToddRoberts** [comment]
Leave primary as is, I have not done any research to see if people are using it specifically because it was the only way to get green. Also going forward, primary is not going to be a recommended usage for labels.

**Comment by josh-channin** [comment]
@Blackbaud-ToddRoberts Todd, I also found that btn-success is blue as well. Should that be corrected?

**Comment by Blackbaud-ToddRoberts** [comment]
Yeah you can fix that as well.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.22](https://github.com/blackbaud/skyux/releases/tag/v1.5.22)
