### ISSUE TITLE
Grid - searching for a value not clearing the old highlighted data.

### ISSUE THREAD

**Issue by hpatel81** [blackbaud/skyux1#567]
### Expected behavior

When searching on a value that matches every item in the grid, the search should still highlight every value that matches the search string then you search second time it should clear the old highlighted data. 
### Actual behavior

First time its working fine but when you search second time, that will not clearing the old highlighted data. need to clear old highlighted data before searching.
### Steps to reproduce
1. In the Plunker below, search for 'Paul' in the grid & it will highlighted the data with word 'Paul'
2. Clear the Search Textbox & make sure don't hit enter then search for 'Ringo'.
3. it will also highlight data with 'Ringo' but not clear the data with word 'Paul'.
### Plunker

[http://plnkr.co/jo93XhDz5nFjQ1iHSdx3](http://plnkr.co/jo93XhDz5nFjQ1iHSdx3)

**Comment by hpatel81** [comment]
In _highlightSearchText()_ function, need to add “**bbHighlight.clear(tableEl);**” line before **bbHighlight(tableEl.find("td").not('.bb-grid-no-search'), options.searchText, 'highlight');**.

this will clear up data before searching

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.22](https://github.com/blackbaud/skyux/releases/tag/v1.5.22)
