### ISSUE TITLE
Selecting first checkbox in grid causes rows to shift

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux1#576]
### Expected behavior

Select the first checkbox in a grid and expect the size of the rows to not change.
### Actual behavior

Select the first checkbox in a grid and notice the rows are shifted slightly down.
### Steps to reproduce

Select the first checkbox in the grid.
### Plunker

http://plnkr.co/edit/swUMKdo249vBny9NPqYr?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.1](https://github.com/blackbaud/skyux/releases/tag/v1.6.1)
