### ISSUE TITLE
npm install now requires git

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux1#578]
Now that we're using NPM for our dependencies, we have two using the `git+` syntax.  Unfortunately this means you need git installed on the machine.  We should user another mechanism (npm directly if available, or store the files locally) in order to not add git as a requirement.

**Comment by Blackbaud-PatrickOFriel** [comment]
We think it's reasonable to require git when building/installing SkyUX, so we'll ensure that we add a note of this in the readme

**Comment by blackbaud-johnly** [comment]
Added a note and created a pull request: https://github.com/blackbaud/skyux/pull/622
