### ISSUE TITLE
Key info block microlayout

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#580]
https://blackbaudinc.box.com/s/m62c1toi7tysegnsi111i88cpqf2dgo3 

Designer: Todd
Approved

**Comment by Blackbaud-PaulCrowder** [comment]
Quick and dirty example implementation:

http://plnkr.co/edit/FkOxoCuOUQVUe0gOAcyk?p=preview

We should also update page summary directive documentation to use the new directive.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.3](https://github.com/blackbaud/skyux/releases/tag/v1.6.3)
