### ISSUE TITLE
BB-Tab-Sref doesn't initialize to correct tab based on state

### ISSUE THREAD

**Issue by Blackbaud-ScottVossen** [blackbaud/skyux1#588]
### Expected behavior

The intent of the bb-tab-sref seems to be to emulate the ui-sref/ui-sref-active functionality provided by ui-router in the bb-tabs component. When the page loads, the current $state setting should determine which tab is being displayed. This way, we can bookmark a given url and return to the exact tab we bookmarked.
### Actual behavior

The initial tab is selected regardless of what state we are in on page load.
-- there seems to be a timer which fires some code that causes this switch (tabsref.js:37).
### Steps to reproduce

I tried to emulate the issue I'm having in my application with a plunker, but that doesn't lend itself well to page reloads so I make a static html file to test with (you'll need to rename the extension to view the page). You can see I started with the bb-sref-tab plunker from the SkyUX documentation and added a few more routes and a "state tracker" section at the top of the page. 

You can bring up the page and click the various links/tabs to see things working correctly in sync. If you leave any tab other than the first tab selected and reload the page, the first tab is selected and the state is changed to reflect that tab's bb-sref-tab value.

I ran across this while trying to load the equivalent of the "abstractParent.master.detail" route in my application. I can bookmark the "abstractParent.master" route and display the correct tab, but the child state doesn't work.
### Plunker

[bb-sref-tab-child-state-issue.html.txt](https://github.com/blackbaud/skyux/files/282695/bb-sref-tab-child-state-issue.html.txt)

**Comment by Blackbaud-PatrickOFriel** [comment]
The issue here is that our demo was very poor in showing how tabsref should be used. I just checked in a better example to master which actually changes the tabs as you change the url (and initializes the tabs to have the second active first). The problem was the ui-router required a root `<ui-view>` element that holds the template that interacts with the state/url.

See: https://github.com/blackbaud/skyux/blob/master/js/sky/src/tabsref/docs/demo.html
and https://github.com/blackbaud/skyux/blob/master/js/sky/src/tabsref/docs/demo.js.

We can reopen this if the example doesn't fix the issues you're seeing

**Comment by Blackbaud-ScottVossen** [comment]
Yeah I realized the sample on the documentation page was not displaying things quite right. I was trying to get around that to demonstrate the issue I'm seeing but struggled to make things clear. I think I got a bit off track by focusing on which tab was initially selected.

In the example html file I uploaded, there are master/detail routes which emulate the issue I'm having. Basically, I cannot bookmark one of the nested grandchild routes because the code which initializes the tabs seems to force the $state to one of the states names in the tabs.

Let me start by explaining how my routes are set up.

**Routes:**

```
.state('fund', {
    url: '/fund/:fundId',
    abstract: true,
})

.state('fund.info', {
    url: '',
    ...
})
.state('fund.info.gifts', {
    url: '/gifts',
    ...
})

.state('fund.marketValue', {
    url: '/marketValue',
    ...
})
```

As you can see, I have an abstract "fund" state which requires the child state's urls to start with "/fund". I then have two children, "fund.info" and "fund.marketValue". I also have a group of grand-child views in my page, which I've represented here by listing just the one; "fund.info.gifts".

**Markup:**

```
<uib-tabset class="light-grey-bg">
    <uib-tab heading="Fund information" bb-tab-sref="fund.info"></uib-tab>
    <uib-tab heading="Market value" bb-tab-sref="fund.marketValue"></uib-tab>
</uib-tabset>
```

In my fund-detail.html file, I have the tabs defined as above. The content of these tabs isn't really important as it's the $state and the active tab which matters for this discussion.
1. I can navigate to the /fund url and be defaulted correctly to the "fund.info" state with the correct tab selected. 
2. If I reload this page I will return to the correct tab (fund.info) with the correct content.
3. I can then switch to the "fund.marketValue" tab and see the correct contents. 
4. If I reload this page I will return to the correct tab (MarketValue) with the correct content.
5. If I go back to the fund.info tab and switch to the "grand-child" view (fund.info.gifts), the correct $state is represented in the url and the correct content is displayed.
6. If I reload the grand-child state, initially the correct url is displayed as the page loads. However, as the tabs initialize themselves, the tabs transition the state back to fund.info. Obviously this doesn't display the correct content for me. 

I put a breakpoint on the StateChangeStart event in my routing to see what was triggering this state change and found tabsref.js:37 to be the culprit. Not being familiar with the code myself, I assumed it would be best to just leave the breadcrumb and ask the experts.

**Comment by Blackbaud-PatrickOFriel** [comment]
Okay, let me try to recreate this scenario

**Comment by Blackbaud-ScottVossen** [comment]
Awesome! I appreciate your patience and attention on this!

**Comment by Blackbaud-PatrickOFriel** [comment]
Reopening until #594 gets into master

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.1](https://github.com/blackbaud/skyux/releases/tag/v1.6.1)
