### ISSUE TITLE
bb-checklist single select needs a data-bbauto-field tag inside repeater

### ISSUE THREAD

**Issue by ghost** [blackbaud/skyux1#590]
In attempting to write automation against a bb-checklist in single select mode, it is difficult to click on a specific item inside of the repeater because no data-bbauto-field tag is present and the current automation platform assumes that the repeater content will contain some tag(s).

It appears that there is an element which was given a data-bbauto-field tag but not a value: 

`<button ng-repeat="item in bbChecklist.filteredItems" type="button" class="bb-checklist-list-row ng-scope" ng-class="bbChecklist.getRowCls(item)" data-bbauto-field="" ng-click="bbChecklist.singleSelectRowClick(item)">
            <ng-include class="bb-checklist-list-col ng-scope" src="'sky/templates/checklist/checklistlistrow.include.html'"><div class="ng-scope">`

perhaps this could be given a value provided by the content of the repeater, which seems to be the case for multi-select checkbox lists:

`<label ng-repeat="item in bbChecklist.filteredItems" class="bb-checklist-list-row ng-scope" ng-class="bbChecklist.getRowCls(item)" data-bbauto-field="Admin">`

**Comment by Blackbaud-JeremyRyan** [comment]
The data-bbauto-field tag is set to the value of the `name` property on the row object. However this isn't documented anywhere. I had to discover this by examining the code.

**Comment by Blackbaud-PatrickOFriel** [comment]
I'm going to go ahead and close as this was already how the non-single-select checklist in list mode populates `data-bbauto` attributes. Also not sure how much we want to call out attributes for NXT specific automation in the SkyUX documentation.
