### ISSUE TITLE
Page/form action bar

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#598]
https://blackbaudinc.box.com/s/g7ro7nz514ato8xmsr252qm8943wf2tt

Designer: Todd
Approved

**Comment by Blackbaud-PatrickOFriel** [comment]
Note that the box shadow should only appear if the container that the action bar resides in is scrollable, if it is not scrollable, only show a solid border. Also, modal footers should reflect this style after we create the actionbar component so we will probably be using the action bar component internally within `bb-modal-footer`.

`bb-actionbar` is already taken, so we'll need to come up with another name for this component. like `bb-form-actionbar` or something.

**Comment by blackbaud-johnly** [comment]
Would `bb-summary-actionbar` or `bb-actionbar-summary` work for the component name since this action bar also displays summary info?

**Comment by Blackbaud-PatrickOFriel** [comment]
I'd be fine with `bb-summary-actionbar`

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.9.0](https://github.com/blackbaud/skyux/releases/tag/v1.9.0)
