### ISSUE TITLE
Create summary section pattern documentation

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#60]

**Comment by Blackbaud-ToddRoberts** [comment]
Desktop version:

![page summary full height key desktop](https://cloud.githubusercontent.com/assets/13765813/12277982/775d91ca-b94c-11e5-894b-0391e7040087.png)

Phone version:

![page summary full height key phone](https://cloud.githubusercontent.com/assets/13765813/12277983/78d9875c-b94c-11e5-928f-58ab8a20e888.png)

**Comment by Blackbaud-ToddRoberts** [comment]
Content chunks:
Alert(s)
Image
Primary record identifier
Secondary record identifier
Status labels
Key information
Arbitrary content
Action bar

**Comment by Blackbaud-ToddRoberts** [comment]
Margins:

![page summary full height key desktop](https://cloud.githubusercontent.com/assets/13765813/12362356/d0c47b0c-bb90-11e5-8c13-3db9280b0b23.png)

![page summary full height key phone](https://cloud.githubusercontent.com/assets/13765813/12362359/d42b6fa8-bb90-11e5-95a2-143e6dc7e93f.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.4](https://github.com/blackbaud/skyux/releases/tag/v1.5.4)
