### ISSUE TITLE
Moment.js locale folder not included in dist/js folder

### ISSUE THREAD

**Issue by Blackbaud-JasonBilyeu** [blackbaud/skyux1#609]
### Expected behavior

Requiring sky-bundle.js or libs.js in index.js should work with no errors.
### Actual behavior

If we require sky-bundle.js directly (through index.js), it will fail saying no such directory /locale.  This is caused by the following line in moment.js:  require('./locale/' + name)

The same thing happens when requiring libs.js as it includes the moment code without their locale folder.
### Steps to reproduce

Modify index.js to require sky-bundle.js instead of manually requiring all libraries and sky on separate lines.  Attempt to require blackbaud-skyux from another project.

Once this issue is resolved, the index.js can be simplified to just require sky-bundle.  It will automatically stay up-to-date with dependency changes.
### Plunker

N/A

**Comment by Blackbaud-PaulCrowder** [comment]
Is the `index.js` file you mention part of your own project or is it the one added in #608?

**Comment by Blackbaud-JasonBilyeu** [comment]
This is referring to the index.js added as part of https://github.com/blackbaud/skyux/pull/608.
