### ISSUE TITLE
popover and tooltips do not respect viewport boundaries

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#62]
This is a known issue in Angular UI but we probably want some solution in sky to address this. I'm thinking you can add some directive that recalculates the width/height if it is outside the viewport.

http://plnkr.co/edit/qelel8Kh7xd7DEZ4WcZu?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Here's an example of a popover being cut off by the viewport using the latest version of sky http://plnkr.co/edit/KdrcZqnCkYsxpUqfNCfl?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Is this not an issue you can usually solve by using css and tooltip/popover-placement attributes?

**Comment by Blackbaud-MichaelLopez** [comment]
If you mean dynamically changing the placement attribute based on where on the page the element with the popover is; I don't think that is a reasonable solution. Nothing is ever going to be centered perfectly and there will always be a chance of clipping. I'd rather not have to worry about clipping ever being an issue.

**Comment by Blackbaud-PatrickOFriel** [comment]
But then you could have weird issues like putting a popover-placement="left" when there is only 5px of space to the left. Would the viewpoint sensing directive make a 5px wide and very tall tooltip that would just wrap every word/letter to make it fit?

**Comment by Blackbaud-MichaelLopez** [comment]
Yea I think that would be the expected behavior. I think its better than the clipping that is happening today.

**Comment by Blackbaud-PatrickOFriel** [comment]
Also, there is a feature on the UI-bootstrap docket for smart placement of tooltips/popovers [here](https://github.com/angular-ui/bootstrap/issues/4762). I would think this combined with a sane max-width placed on tooltips and popovers (not having them being able to go extremely wide by default) might be sufficient. We'll discuss it at planning

**Comment by httpete** [comment]
Here is how it should work.  http://download.dojotoolkit.org/release-1.10.4/dojo-release-1.10.4/dijit/tests/test_Tooltip.html  try resizing your browser small so that it would cut off the bottom of a dropdown menu, and it will detect that and pop up.

**Comment by Blackbaud-MichaelLopez** [comment]
Looking into this some more, I believe the CSS overrides in SKY are messing with the Angular UI Tooltip. These overrides are found in _theme.scss

The 'max-width: none' looks particularly bad as this causes overflow. To address this I'm currently using SKY 1.5.9 with the following resets back to the css that ships with Angular UI:

```
.tooltip-inner {
    white-space: normal !important;
    max-width: 200px !important;
    padding: 3px 8px 0 0 !important;
    text-align: center !important;
    font-size: 12px !important;
}
```

As I resize the viewport, the tooltip is adjusting as I would have expected and the positioning of the tooltip looks better as a result. I'm not sure if the SKY overrides are messing with the positioning system in Angular UI.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.0-0](https://github.com/blackbaud/skyux/releases/tag/v1.6.0-0). Will comment on this issue again when the prerelease is merged into master.
