### ISSUE TITLE
Toast displays incorrectly on iOS 8

### ISSUE THREAD

**Issue by Blackbaud-CaitlinEstrella** [blackbaud/skyux1#624]
### Expected behavior

Toast displays with the close button on the right side on an iOS 8 device.
### Actual behavior

Toast displays with an extra blue border and the close button is on top of the message.
![ios8_toast](https://cloud.githubusercontent.com/assets/16723180/16082329/e808d19e-32de-11e6-83bc-df768754e7cb.png)
### Steps to reproduce

Browse to http://skyux.developer.blackbaud.com/components/toast/ on an iOS 8 device. Open a demo toast.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.3](https://github.com/blackbaud/skyux/releases/tag/v1.6.3)
