### ISSUE TITLE
Navbar menus appear as dropdowns on mobile

### ISSUE THREAD

**Issue by Blackbaud-CaitlinEstrella** [blackbaud/skyux1#627]
### Expected behavior

The navbar menus should expand on mobile devices and small screens.
### Actual behavior

The navbar menu inconsistently appears as a dropdown instead of expanding on a touch device.
### Steps to reproduce

This bug is inconsistent so the steps do not always work.
Using a mobile device with a navbar with multiple menus, select a header and see that the menu expands.
Click on a link in the menu, see that the menu changes to a dropdown.
### Notes

When debugging this issue, I noticed that the :hover attribute is applied when this bug occurs. When the menu correctly expands the .open class is applied. This only happens on touch screens.

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-CaitlinFoster Does this happen on a specific iOS/Android version from what you can tell?

**Comment by Blackbaud-CaitlinEstrella** [comment]
@Blackbaud-PatrickOFriel From what I can tell, there is not a specific version. I have seen this issue on Android and iOS devices across multiple versions. But I have only reproduced it on physical devices, I have not been able to reproduce it on any simulators.

**Comment by Blackbaud-PatrickOFriel** [comment]
On the iphone6s simulator, the dropdown menu doesn't even open on touch. I'm going to look at the dropdown menu responding to click as well as a start to this problem. If that doesn't solve this, then maybe we can get the exact html/js structure of when you're seeing this problem, because I have not been able to reproduce your use case so far

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.5](https://github.com/blackbaud/skyux/releases/tag/v1.6.5)
