### ISSUE TITLE
`bb-navbar-showmobile` is not respected in mobile browser

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/skyux1#636]
### Expected behavior

When viewing a page with `bb-navbar` with the class `bb-navbar-showmobile` on a mobile browser, the `bb-navbar` will be shown.
### Actual behavior

The `bb-navbar` disappears on a mobile browser.
### Steps to reproduce
1. In chrome, go to the SKY UX documentation [page](http://skyux.developer.blackbaud.com/components/navbar/) for `bb-navbar`
2. Open chrome developer tools
3. Change the view to display as an iPhone 6
4. Note that the navbar disappears

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.4](https://github.com/blackbaud/skyux/releases/tag/v1.6.4)
