### ISSUE TITLE
Grid documentation:  include something about the default sort behavior

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [blackbaud/skyux1#642]
Reading the documentation, it's unclear what the default sort behavior of the grid is...for example, I've not specified any sortOptions, yet the columns headers are clickable and the sort indicator is toggle-able.  Also, it's unclear from the docs whether the grid does any inherent sorting OOB (I know from the Plunker sample that I can watch the sortOptions for changes and do logic, but it seems reasonable to expect the docs to have something about the default behavior)

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-BenLambert, we updated sorting in `bb-grid`. Now we allow the use of the [sort](http://skyux.developer.blackbaud.com/components/sort/) component, which prevents the grid headers from having their click-sort behavior. Do you think this addresses the documentation need, or should we add some more explanation?

**Comment by Blackbaud-BenLambert** [comment]
maybe just a link to the sort component like you have for the filter module on the bbgrid doc page.

**Comment by Blackbaud-PatrickOFriel** [comment]
Great I added a note about that in the last release under bb-grid-toolbar-sort.
