### ISSUE TITLE
Typo in grid documentation

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux1#645]
Typo in grid documentation.  See attached screenshot.

![typo](https://cloud.githubusercontent.com/assets/4612419/16322888/70123bb6-3974-11e6-837a-67fb47d22504.png)

Reported by @blackbaud-BenLambert

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.4](https://github.com/blackbaud/skyux/releases/tag/v1.6.4)
