### ISSUE TITLE
Date Fields: AutoComplete Should Occur On Focus Loss

### ISSUE THREAD

**Issue by Blackbaud-ScottKavanagh** [blackbaud/skyux1#656]
There's a lot of feedback on the client community around date fields not auto-completing when entering a partial date.
[Idea Bank I-329](https://renxt.ideas.aha.io/ideas/RENXT-I-329)

In the past, RE-NXT was leveraging bbmoment to auto-format a partial date when the field losses focus.  This should be something that occurs by default with date fields that have a standard date format and validation set.

Our fuzzy date fields have custom RE-NXT fuzzy date formatting logic server-side and are attempting to build a valid fuzzy date with the date field focus loss.   We'd also like similar functionality with full date fields.
### Expected behavior

When typing a partial year and leaving the input field, the year should auto-complete based on bbmoment formating logic instead of causing a validation error.
### Actual behavior

Date Fields with a standard format are not auto-completing with partial date input.
The user has to manually type the 8-digit date in order to pass validation.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.2](https://github.com/blackbaud/skyux/releases/tag/v1.7.2)
