### ISSUE TITLE
Context menu in modal forms are not displaying on modal body

### ISSUE THREAD

**Issue by barbam** [blackbaud/skyux1#657]
We would expect a context menu on a modal form to be fully visible on top of the modal body.

What is currently happening seems like an issue with the context menu not being properly appended to the body.

Here is an example plunker of the issue: http://plnkr.co/edit/qIyQEfdIcANit4XPuqCz?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
This is also an issue with ui-bootstrap itself as seen [here](http://plnkr.co/edit/idHDzoYbpxugzfFC35HM?p=preview) where no sky library is brought in. So any fix we create we might want to contribute back to them

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.5](https://github.com/blackbaud/skyux/releases/tag/v1.6.5)
