### ISSUE TITLE
Tile Dashboard state route uses blank url

### ISSUE THREAD

**Issue by nuander** [blackbaud/skyux1#660]
The state used by tile dashboard sample to route tiles uses a blank url.  This causes problems if the application is using ui-router for site navigation, in which case the blank url should redirect to a home page e.g. $urlRouterProvider.when('', '/home').  It also makes it impossible to have multiple tile dashboards with different tiles in the same project.  More documentation around this would be extremely helpful.

**Comment by Blackbaud-PatrickOFriel** [comment]
Can you create a plunker which demonstrates the issue you are having?

**Comment by nuander** [comment]
In this example from your developer website the state name is never referenced in the code,  It could be set to anything like "bob", and the URL is blank.  http://plnkr.co/edit/ICJPJKk254xuKjgAQ7y9?p=preview
Is there a way to specify the state name that the tile dashboard should use in order to create states that will not interfere with the rest of the angular app?

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah the reason the example case looks like this is just to give a very simplified example of how a tile dashboard works. You can place a dashboard in any state or url within a root `<ui-view>` just like you would using `ui-router` at any other time

**Comment by Blackbaud-PatrickOFriel** [comment]
Closing this unless there is an example of being unable to use ui-router properly. We will most likely keep our tile dashboard documentation the way it is because our demo is meant to demonstrate tile dashboard, not how to use different urls with ui-router. I would check https://github.com/angular-ui/ui-router/wiki for more information on that.
