### ISSUE TITLE
Allow "x" on grid filter summary to be conditionally hidden

### ISSUE THREAD

**Issue by Blackbaud-DanMiller** [blackbaud/skyux1#671]
It would be very useful to allow the "x" on the grid filter summary to be conditionally hidden. This will allow us to establish a pattern of _fixed_ or _unremovable_ filters. For example, creating a list from a static query in RE NXT shows the following:

![image](https://cloud.githubusercontent.com/assets/11977741/16620171/6d5e7a98-435f-11e6-91ae-118e8f5f3ccf.png)

In this case, the "x" is misleading, since the backend logic prevents the filter from being removed. Allowing us to hide the "x" will make the intention of the filter clearer to the end user.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.7](https://github.com/blackbaud/skyux/releases/tag/v1.6.7)
