### ISSUE TITLE
Select field > Selecting a value takes one more keystroke than the searchlist component it is replacing

### ISSUE THREAD

**Issue by Blackbaud-TimothyWittig** [blackbaud/skyux1#674]
### Expected behavior

Using a select-field component would require the same or less keystrokes to select an item than the ui-select component it is replacing.
### Actual behavior

Using a select-field component requires more keystrokes to select an item than the ui-select component it is replacing.
### Steps to reproduce
1. Navigate to the given plunker.
2. Click into the select-field component to launch Select value modal (1).
3. Type "Gold" to narrow down to single item (2).
4. Hit tab key to highlight "Gold" entry (3).
5. Hit enter key to select "Gold" entry (4).
6. Click into searchfield component to launch search drop down (1).
7. Type "Gold to narrow down to single item (2).
8. Hit enter key to select "Gold" entry (3).
9. Observe that select-field control requires one more keystroke than searchfield component.
### Plunker

http://plnkr.co/edit/fG3DVt3ztx48avScYpAO?p=preview

**Comment by Blackbaud-ToddRoberts** [comment]
Rob is looking at the overall design for this. Click parity was not a criterion of the select field design, so I will close this and then we will open a new issue whenever a new design is approved.
