### ISSUE TITLE
Select Field - Single select mode icon and clearing

### ISSUE THREAD

**Issue by Blackbaud-TimothyWittig** [blackbaud/skyux1#675]
As of release [1.6.0](https://github.com/blackbaud/skyux/releases/tag/v1.6.0) search fields have been replaced by select fields in SkyUX. However, replacing a search field with a select field results in a change in the symbol displayed on the field. A magnifying glass is almost universally used to indicate a search but the new vertical double arrow on a select field is not universally used to indicate a search. It is sometimes used to indicate a drop down or to indicate a "rearrange" interaction with an element.

**Comment by Blackbaud-ToddRoberts** [comment]
Option to choose search or arrow icon when consuming component.
Clicking the X clears the field.

![single select](https://cloud.githubusercontent.com/assets/13765813/17180659/285897fc-53eb-11e6-878b-429d0dfa3e71.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ToddRoberts question: Does this change remove the "Clear selection" button in the single select modal, or is the new clear an addition and we keep the "Clear selection"?

**Comment by Blackbaud-ToddRoberts** [comment]
In addition to the existing

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.4](https://github.com/blackbaud/skyux/releases/tag/v1.7.4)
