### ISSUE TITLE
The "load more" button and pagination controls are hidden behind the "back to top" footer when browser zoomed at 90%

### ISSUE THREAD

**Issue by Blackbaud-DaveMarino** [blackbaud/skyux1#679]
### Expected behavior

I would expect that the load more button and pagination controls to be visible when scrolling to the bottom of the page regardless of the zoom level of the browser. 
### Actual behavior

The load more button and pagination controls are hidden behind the "back to top" footer when you scroll to the bottom of the page.  
### Steps to reproduce
1. set the zoom on your browser to 90%
2. click load more a few times. 
3. the first time you scroll off the page, it seems ok.  The second or third time, the load more button will be hidden by the "back to top" footer.
### Plunker

http://plnkr.co/edit/ythiaycsGvRRoFWr1Kk6?p=preview
### Other notes

Our support team has indicated that they have spoken to other customers who have their zoom set to 100% and still experience this issue.  However, I have not been able to reproduce that particular scenario.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.8](https://github.com/blackbaud/skyux/releases/tag/v1.6.8)

**Comment by vivekbatra** [comment]
This bug is still occurring albeit with no zoom this time.

[http://plnkr.co/edit/LjVxXlaWa9h673p04Mos?p=preview](url)

This is same for pagination as well where pagination is overshadowed with the 'Back to top' action.
