### ISSUE TITLE
Extend checklist control

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#68]
Extend the checklist control to allow for single-selection and adding new values.

**Comment by Blackbaud-PatrickOFriel** [comment]
Do we have some specs for this we can check out? it should probably be the next feature on our docket because of ui-select mobile issues

**Comment by Blackbaud-ToddRoberts** [comment]
There are specs but I just discovered a possible issue with adding items on the fly, checking with Nick about it.

**Comment by Blackbaud-ToddRoberts** [comment]
The plan for this has changed. For now we are just going to add the Single Select mode. Adding on the fly may be enabled later, but there is uncertainty about whether it was the right approach for the problem it is trying to solve. 

Do you need documentation for Single Select mode? The basic rundown is:
Clicking on the list/grid row returns the value from that row.
Override the "select all/clear all" option to off, since it doesn't make sense for single select.
Don't need an Apply/Cancel action bar for single select.

**Comment by Blackbaud-PatrickOFriel** [comment]
Other questions, since this will be used in place of the current single and multiselect functionality, are we providing guidance about how to launch these from modals/styling for how the interaction should look before and after the checklist is used? Is there a button that shows the text selections when the checklist is applied or anything? I don't know if I'm making any sense so tell me if I'm rambling, @Blackbaud-ToddRoberts

**Comment by Blackbaud-ToddRoberts** [comment]
There is not an official design for the launcher/value display yet. I saw a proposed design that could work, I can track that down. Will it impact the work on the Checklist itself, or just something we need to document?

**Comment by Blackbaud-PatrickOFriel** [comment]
We should definitely document it so we can deprecate the old ui-select control and give users a clear way to replace it.

**Comment by Blackbaud-PatrickOFriel** [comment]
Single-select mode: clicking on the item closes modal. No footer, just a close button up top.

**Comment by Blackbaud-ToddRoberts** [comment]
Default invoke and display selected items:

![invoke and display](https://cloud.githubusercontent.com/assets/13765813/12277394/0f8bf0d0-b949-11e5-9b14-9698083c1da4.png)

Single-select version of control: 

![v8 single select](https://cloud.githubusercontent.com/assets/13765813/12277400/1440518e-b949-11e5-9bf5-0bd72370637b.png)

**Comment by Blackbaud-ToddRoberts** [comment]
Scope of work:
Create a single-select version of the control
Add a "Show only selected items" filter to the multi-select version
Create components to invoke the control and display selected items
Option to not preload the item list in the control (for things like constituents, where there could be tens of thousands)

Excluded from scope of work:
Adding items on the fly - there was not agreement that this was the right approach to solve the problem it was trying to address

**Comment by Blackbaud-ToddRoberts** [comment]
Need to look at possible accessibility issue #213

**Comment by Blackbaud-PaulCrowder** [comment]
@Blackbaud-ToddRoberts What should a selected row look like in single select mode?  Since there's no checkbox visible we'll need some other visual indication for a selected item.

**Comment by Blackbaud-ToddRoberts** [comment]
I would say same style used to show selected rows in grid (the purple bg)

**Comment by Blackbaud-PatrickOFriel** [comment]
TODO: document in conjunction with Todd and write visual tests

**Comment by Blackbaud-PatrickOFriel** [comment]
Hokay @Blackbaud-ToddRoberts , I’m about to fire a bunch of select field questions to you: 
1. Should single select mode input allow some sort of placeholder text like multiselect mode has next to the plus-circle icon? 
2. Should the single-select have a mechanism to clear its value? That does not currently exist. 
3. What does validation look like (required is the only one I can think of) for both single and multi-select mode? Is that something we’re worrying about right now?

**Comment by Blackbaud-ToddRoberts** [comment]
1. Yeah it should allow placeholder text similar to how a select field does.
2. Yeah it should. One way would be to have the first option in the list be "Clear selection" (styled like placeholder text). Another way would be putting a "Clear selection" text link next to the field, which feels awkward.
3. Yes
4. I think we have to account at least for Required. For single select we should do the red border/glow and message underneath. For multiselect we should just use the red message underneath.

**Comment by Blackbaud-PatrickOFriel** [comment]
1. Will do.
2.  I'll try to make that Clear selection option. 

3/4. Will do as well.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.10](https://github.com/blackbaud/skyux/releases/tag/v1.5.10)
