### ISSUE TITLE
Specifying a function for bb-file-drop-accept no longer works

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#682]
### Expected behavior

Specifying a function for `bb-file-drop-accept` should cause that function to be called when a file is dropped so that validation logic can be called.  This appears to be caused by a breaking change in the `ng-file-upload` component since there's a new property `ngf-validate-fn` that is used for specifying a validation function.  See the documentation on the [repo's README](https://github.com/danialfarid/ng-file-upload).
### Actual behavior

The specified function is never called.
### Steps to reproduce
- Create an instance of `bb-file-drop` and specify a function for `bb-file-drop-accept`.
- Drop a file onto the component.
- Notice the function is not called.
### Plunker

http://plnkr.co/edit/mvLfCUTS0janTZMoEBB9?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.6](https://github.com/blackbaud/skyux/releases/tag/v1.6.6)
