### ISSUE TITLE
Quick clear listbuilder search field

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#689]
https://blackbaudinc.box.com/s/4ndf4y5yp1nl9oj2i9gwsbjee8zprbcf
Designer: Raymond

If it is not possible to do the specified different behavior for software keyboard, focus should remain on search bar after clearing.

**Comment by Blackbaud-ToddRoberts** [comment]
#287

**Comment by Blackbaud-PatrickOFriel** [comment]
The clear icon shows in place of the magnifying glass once a search is applied.
The clear icon remains until it is clicked or until searchText is an empty string.
On mobile, the search input is dismissible (has an x in a circle icon) so we might need a different icon for dismiss to avoid confusion with clear.

**Comment by Blackbaud-PatrickOFriel** [comment]
Updates to deal with strangeness with apply search disappearing in favor of clear search:
- Show the clear button when search is in an "applied state" 
- It will be to the right of the input and the left of the apply button
- Do not allow tabbing to the clear search

**Comment by Blackbaud-PatrickOFriel** [comment]
![screen shot 2016-07-18 at 3 24 27 pm](https://cloud.githubusercontent.com/assets/11620552/16927924/fb0002e8-4cfd-11e6-9b24-f916034bfd0a.png)
Here's a screenshot of what we're thinking. Notice that the clear button is smaller than the apply to match it more closely to the text size in the search input

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.8](https://github.com/blackbaud/skyux/releases/tag/v1.6.8)
