### ISSUE TITLE
Gem for Rails apps using Sky UX

### ISSUE THREAD

**Issue by blackbaud-jakespirek** [blackbaud/skyux1#692]
It would be cool to look into potentially building a gem that would make it easy for people using Rails to consume the framework. 

Specifically when they already are using the gems for Bootstrap, AngularJS, etc. 

There are issues with Turbolinks too, so if there was a way to help these not conflict, it'd make it super easy for people to add Sky UX to their apps.

**Comment by Blackbaud-PatrickOFriel** [comment]
We appreciate the suggestion but at this point I don't think we will be supporting a Rails gem for SKY UX at this time.
