### ISSUE TITLE
Update docs to include css class for numbers in tabs

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#706]

**Comment by Blackbaud-BobbyEarl** [comment]
`bb-tab-header-count` is the class that needs to be added.  @blackbaud-johnly Do you think you could handle this one?

**Comment by blackbaud-johnly** [comment]
Sure thing. I'll create a Tab numbers" section in the tabset component documentation at http://skyux.developer.blackbaud.com/components/tabset/.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.1](https://github.com/blackbaud/skyux/releases/tag/v1.7.1)
