### ISSUE TITLE
bb-datepicker bb-date-format getting set to NaN

### ISSUE THREAD

**Issue by Blackbaud-BrandonHay** [blackbaud/skyux1#716]
### Expected behavior

using bb-date-picker, the following html should set the datepicker's date format to "M/dd/yy"

```
<bb-datepicker
    bb-date-format="M/dd/yy"
    name="endDate"
    ng-model="data.dueDate"
    required></bb-datepicker>
```
### Actual behavior

When I do this, the component fails to render on the page. In the datepicker directive, `$scope.format` gets set to `NaN` and this if block fails to catch that

```
if (angular.isUndefined($scope.format)) {
  $scope.format = bbDatepickerConfig.currentCultureDateFormatString;
}
```

resulting in the datepicker not being able to render on the page.
### Steps to reproduce

Add a new bb-datepicker directive and set the `bb-date-format` to "MM/dd/yyyy" or "M/dd/yy".
### Plunker

http://plnkr.co/edit/fU4KEXv0PP7g3qtiki56?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
You're using a literal in the binding and not putting it in string quotes. See http://plnkr.co/edit/yJiAB3U97VTZhS6BY8Pw?p=preview for how to correctly pass literals to an angularjs binding

**Comment by Blackbaud-BrandonHay** [comment]
Ah, well I feel dumb. Thanks Patrick! In case I'm not the only one, maybe explicitly writing that (or providing an example) in the documentation would prevent others from making the same mistake.
