### ISSUE TITLE
bbMoment is failing after upgrading to 1.4.0 or higher due to require issues

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#72]
Our setup is that we load all of Sky and its libs without require on the page, and then we load require.  After upgrading from 1.3.0 to 1.4.2, bbMoment fails due to how it behaves when require exists on the page.

Note that a similar issue exists for how enquire.js is being used by Sky's MediaBreakpoints module. I was able to correct this by using the following line before the app is bootstrapped:

define('enquire', window.enquire);

A similar fix does not work for moment:

define('moment', window.moment);

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.3](https://github.com/blackbaud/skyux/releases/tag/v1.4.3)
