### ISSUE TITLE
Allow bb-grid gridOptions.columns to accept title parameter

### ISSUE THREAD

**Issue by Blackbaud-BrandonHay** [blackbaud/skyux1#720]
### Expected behavior

I would like to disable the title attribute on the `<td>` elements in certain columns of my bb-grid. This attribute results in a mouse over event that shows confusing text (`[Object object]`, in my case). JqGrid checks for `!typeof cm.title === "boolean"` and if that's true it sets the title attribute to true, resulting in this unwanted behavior.
### Actual behavior

Instead, I would like to be able to add `title: false` in certain columns in the gridOptions object that gets passed to jqGrid. I believe the only change necessary would be to add `title` to the `gridColumn` definition in _skyux/js/sky/src/grids/grids.js_:

```
gridColumn = {
                                            index: column.id.toString(),
                                            sortable: false,
                                            id: column.id,
                                            name: column.name,
                                            label: column.caption,
                                            align: (column.right_align ? 'right' : (column.center_align ? 'center' : 'left')),
                                            classes: buildColumnClasses(column),
                                            cellattr: buildCellAttribute,
                                            controller: column.controller,
                                            template_url: column.template_url,
                                            jsonmap: column.jsonmap,
                                            allow_see_more: column.allow_see_more,
                                            width: colWidth,
                                            title: column.title
                                        };
```

This would prevent jqgrid from adding a title attr to the dom element, and we would be free to write in our own title attributes on templates ourselves.
### Steps to reproduce

Create a grid and set one of the columns attributes as `title: false`

```
columns: [
      {
        id: 1,
        jsonmap: 'status',
        name: 'status',
        width_all: 130,
        template_url: 'common/status.tpl.html',
        title: false
```
### Plunker

N/A (Let me know if this needs a plunker. I assumed it was pretty straightforward)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.8](https://github.com/blackbaud/skyux/releases/tag/v1.6.8)
