### ISSUE TITLE
bbGrid failing with: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#73]
The following code does not ensure that $scope.options.data is not null.

$scope.locals.hasWaitAndEmpty = function () {
    return $scope.options && $scope.options.loading && $scope.options.data.length < 1;
};

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.3](https://github.com/blackbaud/skyux/releases/tag/v1.4.3)
