### ISSUE TITLE
Modal Scope

### ISSUE THREAD

**Issue by nuander** [blackbaud/skyux1#734]
I would hope that the modal would be a child of the scope/controller that opens it.  But it is not.  As demonstrated by the attached plunker which fails on the last line.  Suggestions?  

http://plnkr.co/edit/45kF0rWDSaCiBn5znNwK?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
You should pass variables explicitly to your modal using the resolve object in the bbModal open function. See http://plnkr.co/edit/8KUR1zpNGzgMt5TW2xy4?p=preview for an example using your code. Also see https://angular-ui.github.io/bootstrap/#/modal for the underlying modal service that bbModal wraps.

**Comment by nuander** [comment]
OK I'll try that.  Thanks
