### ISSUE TITLE
List contributing prerequisites of SKY UX in Readme more explicitly

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#735]
- git
- nodejs
- npm
- grunt
- ruby sass

Anything else I'm forgetting?

**Comment by blackbaud-johnly** [comment]
I moved contributing content in the README file to the CONTRIBUTING file, added a prerequisites section, and listed the prereqs above. I also made a handful of other tweaks while I was in the docs.

**Comment by Blackbaud-PatrickOFriel** [comment]
https://github.com/blackbaud/skyux/blob/master/.github/CONTRIBUTING.md
