### ISSUE TITLE
Support passing `$stateParams` through `bb-tab-sref`

### ISSUE THREAD

**Issue by blcook223** [blackbaud/skyux1#738]
### Expected behavior

`<uib-tab bb-tab-sref="state1({param: 'foo'})"></uib-tab>` would resolve to a state defined with the following url: `'state1/:param'`.
### Actual behavior

Browser console error indicating state could not be resolved.
### Steps to reproduce

Click the first tab in the plunker below.
### Plunker

http://plnkr.co/edit/LnyPbj78uJiz8TvpUCxU?p=preview

**Comment by blcook223** [comment]
Background discussion from Slack: 
Ben Cook [9:22 AM]  
Hi Sky team, is it possible to pass a `$stateParam` properties to states with `bb-tab-sref`? I have not been successful so far: http://plnkr.co/edit/LnyPbj78uJiz8TvpUCxU?p=preview

Bobby Earl [9:32 AM]  
I don’t think it’s currently possible based on this line.  https://github.com/blackbaud/skyux/blob/master/js/sky/src/tabsref/tabsref.js#L38  Seems we’d have to provide a property to pass those params into the $state.go() method.  http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.10](https://github.com/blackbaud/skyux/releases/tag/v1.6.10)
