### ISSUE TITLE
Sky headers are truncated too soon.

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#74]
When the header text for a tile is long, the text is truncated and an ellipsis is shown.  This is happening even when there is plenty of room to show the full text.

This screenshot shows a window with the full text for the headers showing.
![image](https://cloud.githubusercontent.com/assets/11888587/11340370/a1c809a2-91cb-11e5-9bde-ac4fbdd566de.png)

This screenshot shows a slightly smaller window with the header text for one tile truncated.  Note that there is plenty of room to have shown the full header text.

![image](https://cloud.githubusercontent.com/assets/11888587/11340432/d70dcf02-91cb-11e5-9e53-b56f9dc8c111.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
Problem here is that we're using bootstrap columns to set the width, I'll look at alternatives today, like flexbox or something

**Comment by Blackbaud-MatthewBell** [comment]
Right.  You have a bootstrap column for the buttons, but then you float the buttons to the right.  I'm not sure bootstrap is even needed here?

**Comment by Blackbaud-PatrickOFriel** [comment]
Agreed, I think it just complicates matters

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.4](https://github.com/blackbaud/skyux/releases/tag/v1.4.4)
