### ISSUE TITLE
Documentation for bb-alert-closed setting on alert components is incorrect

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux1#744]
The current documentation for the alert component states that the bb-alert-closed setting is for a function to be triggered on alert closure. However, this setting actually is for a variable that is set to true or false based on if the alert is open or closed. The documentation should be changed to reflect the actual functionality in place to avoid confusion.

**Comment by blackbaud-johnly** [comment]
I corrected the description in the docs and created a pull request with the change (https://github.com/blackbaud/skyux/pull/748).

**Comment by Blackbaud-PatrickOFriel** [comment]
Let's keep this open till we get a release with the new docs out there

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.10](https://github.com/blackbaud/skyux/releases/tag/v1.6.10)
