### ISSUE TITLE
Datepicker Popup Positioning Problems With Min-Date Error

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux1#750]
When a bb-datepicker is:
- Positioned so that there is less than 380 px between the bottom of the input field and the bottom of the page
- A date prior to the the bb-min-date in the month of the min-date has been entered into the input field
- You are viewing the month which the min-date is in 

If you switch between the day and month view the popup will position too high on the page.
### Expected behavior

When you change contexts with the conditions described above the popup should display against the input field as it does normally.
### Actual behavior

When you change contexts with the conditions described above the popup will display too high on the page
### Steps to reproduce
1. Go to the plunker provided
2. Click on the popup button
3. Click May 2014
### Plunker

http://plnkr.co/edit/uNpNuzZDGaowFcs1ERuM?p=preview

This appears to be an issue with when the popup is being positioned. If you set a breakpoint in Chrome on attribute change you can see that when the positionPopup function in Angular UI Bootstrap is called the ng-switch has not fully executed and both the day and month views are shown in the ul element. I'm not sure if this is due to something in Sky or something that is on the Bootstrap side.

**Comment by Blackbaud-PatrickOFriel** [comment]
What browser/os are you seeing this on. I'm not seeing any strange behavior in Chrome on OSX

**Comment by Blackbaud-TrevorBurch** [comment]
I am on Windows 7 and have tested that the bug occurs on both Chrome 52.0.2743.116 and Firefox 48.0. It does not occur for me in IE 11.0.9600.18378 though it does appear the angular issue is happening as I can see the scrollbar appear for a brief moment while both are there and they are just not repositioning in the same manner as the other browsers. I know that our QA member also had this happen on OSX in Firefox 47.0.1. The issue was discovered while implementing a page with a datepicker in eTap and then I rooted out the issue with the steps above and was able to reproduce it in the plunker.

**Comment by Blackbaud-TrevorBurch** [comment]
![image](https://cloud.githubusercontent.com/assets/19909569/17596682/9685a162-5fc0-11e6-80b7-efdca34736e8.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
Investigating with @Blackbaud-TrevorBurch we found a workaround is to use `bb-datepicker-append-to-body="true"` to make this behavior no longer exist. I will investigate further to see why this behavior is occurring, especially since it only seems to happen when a min date is defined

**Comment by Blackbaud-PatrickOFriel** [comment]
Here's my current plunker to isolate the problem http://plnkr.co/edit/zKNoqX3OVLWzJ5wiGkJN?p=preview. Here's a plunker showing trying to isolate the problem in ui-bootstrap and failing http://plnkr.co/edit/AH6l84oJVBvdVY7Z9Om0?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
I currently have a branch called datepicker-positioning that works around the problem by kicking off the ui-bootstrap positioning after manually hiding elements on datepicker mode switch. I think this is the best approach without doing something hacky like relying on timeouts.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.11](https://github.com/blackbaud/skyux/releases/tag/v1.6.11)
