### ISSUE TITLE
Add accessibility guidelines in SKY UX contributing section

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#754]

**Comment by blackbaud-johnly** [comment]
I finished my review of the first draft of the accessibility guidelines and sent my list of edits to Matt.

**Comment by Blackbaud-MattGregg** [comment]
Put in pull request back to the learn branch if this can be merged and then you all can review updates. thx.

**Comment by Blackbaud-BobbyEarl** [comment]
I've merged this PR into the skyux-docs learn branch, if you have the need for further review @blackbaud-johnly.  Otherwise, I'll review it from a developer perspective.

**Comment by blackbaud-johnly** [comment]
I reviewed the guidelines and provided edits to Todd already. I will try to re-review the content when time permits, but I don't think it's necessary to wait for that. If it looks good from a developer perspective, I think it's fine to update the website.

**Comment by blackbaud-johnly** [comment]
Sorry. Just realized I got my wires crossed. I was thinking of Todd's guidelines, not Matt's accessibility guidelines. I'll take a look at Matt's content in the learn branch right now.

**Comment by blackbaud-johnly** [comment]
I re-reviewed the docs, made some edits in a new branch, and created a PR to merge the edits back into the learn branch. I assigned the PR to Matt so that he can review my changes and decide which to keep and which to discard.

**Comment by Blackbaud-MattGregg** [comment]
@Blackbaud-BobbyEarl Think these are ready for review from developer perspective and then potential launch at next release?

**Comment by blackbaud-johnly** [comment]
Added as part of the updates with the learn branch. This was part of the PR https://github.com/blackbaud/skyux-docs/pull/59 in the skyux-docs repo.
