### ISSUE TITLE
Omnibar search results cannot be dismissed on mobile

### ISSUE THREAD

**Issue by Blackbaud-LeslieStaggs** [blackbaud/skyux1#771]
### Expected behavior

According to http://skyux.developer.blackbaud.com/core-design/icons/ the X with a circle icon is used to clear. I expected the X I saw in search to clear the results or at least hide the results once search was closed.
### Actual behavior

On mobile when I searched for text, I saw the X with a circle and clicked it thinking it would clear. Instead it closed the search field but kept the search results open. I had to open the search again and backspace in order to get rid of the search results. Reproduced on developer guides site search and renxt omnibar search.
### Steps to reproduce
1. Access http://skyux.developer.blackbaud.com on an iPhone
2. Click in the omnibar search box and type in 'grid'. Note that an X with a circle appears along with your results.
3. Click the X with a circle. See that the search field goes away but the results stay there.

**Comment by Blackbaud-PatrickOFriel** [comment]
The omnibar is not a part of the SKY UX library, we just provide a convenience wrapper to access it. Please contact @Blackbaud-JonathanBell for any change requests for omnibar
