### ISSUE TITLE
Mark help components as Blackbaud internal

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#788]

**Comment by blackbaud-johnly** [comment]
Added internal-use-only notes to help service and help button directive topics. Included these tweaks in https://github.com/blackbaud/skyux/pull/789.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.2](https://github.com/blackbaud/skyux/releases/tag/v1.7.2)
