### ISSUE TITLE
Add style to child menu items in navbar component for bb-navbar-active

### ISSUE THREAD

**Issue by Blackbaud-BethRichardson** [blackbaud/skyux1#806]
### Expected behavior

Child li elements in navbar that have bb-navbar-active class should apply a selected color and background-color (similar to hover) to the child a element.
### Actual behavior

Child items in a list in navbar are not selected by default navigation scss. You can see that RENXT has custom css to provide this behavior in shell.
### Steps to reproduce
1. Go to https://renxt.blackbaud.com and login
2. In navbar, make sure something is selected.
3. Inspect the child menu item that is selected. (#page-wrapper > div > div > bb-navbar > nav > div > ul.nav.navbar-nav.navbar-left > li.dropdown.ng-scope.bb-navbar-active > ul > li.ng-scope.bb-navbar-active > a). 
4. Note that the Computed color and background-color are applied by shell.
   These styles should be applied by the _navigation.scss. When custom css is not added to override for bb-navbar-active, selected styles do not get applied to child items.
### Plunker

Please use steps above to view in RENXT.

**Comment by Blackbaud-PatrickOFriel** [comment]
Here's an example of the problem in plunker http://plnkr.co/edit/dmtVkdqwJYKR6lSwt8cT?p=preview The active state does not have correct styling in the navbar dropdown

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-BethRichardson did you want to take this one and submit a pull request? If not I can grab it and get it done next week

**Comment by Blackbaud-BethRichardson** [comment]
Next week works. Thanks @Blackbaud-PatrickOFriel !

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.3](https://github.com/blackbaud/skyux/releases/tag/v1.7.3)
