### ISSUE TITLE
Add "traditional" parameter for bbData.query

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#81]
From @Blackbaud-JeremyRyan

The jQuery.param method supports a second parameter "traditional: Boolean" which causes brackets not to be added or encoded for array query parameters. Can bbData.query be extended to allow using this parameter?

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-JeremyRyan Can you give an example of the result today, versus what you're expecting to get if we were to expose the traditional parameter?

**Comment by Blackbaud-PatrickOFriel** [comment]
Closing because of lack of information. We can reopen if there is more info/interest
