### ISSUE TITLE
bb-tab-sref breaks when using latest UI Bootstrap syntax

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#810]
### Expected behavior

bb-tab-sref should behave the same when using the more up to date UI Bootstrap tab syntax as it does with older syntax.
### Actual behavior

When moving from having an `active` attribute on `uib-tab` elements to having an `index` attribute, the presence of `bb-tab-sref` causes the tabs to behave strangely.  Specifically, the tab headers do not always show as selected.
### Steps to reproduce

Use `index`  and `bb-tab-sref` on `uib-tab`.
### Plunker

Example of tabs not working when using both `index`  and `bb-tab-sref`:
http://plnkr.co/edit/fWM0dTtA4HrLtorfcyp7?p=preview

Example of tabs workign when using `bb-tab-sref` but not  `index` :
http://plnkr.co/edit/gzCsdcZKjBxIMo4JoKwl?p=preview

Example of tabs workign when using `index` but not  `bb-tab-sref` :
http://plnkr.co/edit/tpvNel5siuvu76pqvk62?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
I think the index attribute is supposed to be on `uib-tabset` not `uib-tab`

**Comment by Blackbaud-PatrickOFriel** [comment]
wait a second, it's active that's supposed to be on `uib-tabset` with the new stuff. let me take a look

**Comment by Blackbaud-PatrickOFriel** [comment]
Found the problem, will tackle it this sprint

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.3](https://github.com/blackbaud/skyux/releases/tag/v1.7.3)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.4](https://github.com/blackbaud/skyux/releases/tag/v1.7.4)
