### ISSUE TITLE
Extend Toast directive to accomodate triage levels

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#82]
Update the Toast directive to follow our (new/proposed) triage levels that we are also using for labels, badges and notifications:

Success
Info
Warning
Danger

FE NXT has a design ready to go that would make use of this.

**Comment by Blackbaud-PatrickOFriel** [comment]
Dev - talk to JD about specific FE needs to see if those should also be incorporated, or if they will be FE-specific.

**Comment by Blackbaud-ToddRoberts** [comment]
In addition to styling, also need to allow for auto-timeout and manually-dismissed modes of toasts.

**Comment by Blackbaud-ToddRoberts** [comment]
https://blackbaudinc.box.com/s/eftrh2d1r9n2mog5fjchjfuzsi9y48x3
