### ISSUE TITLE
Inline grid filter styling not consistent with date-range picker styling

### ISSUE THREAD

**Issue by Blackbaud-DanielCooke** [blackbaud/skyux1#835]
### Expected behavior

Expected all controls contained in the inline filter set would have consistent styling.
### Actual behavior

Date range picker has a bottom margin of 5px and a right padding of 10px (.form-group.bbdate-range-picker-form-group).   Other controls have no right padding nor do they have a bottom margin.  I think the bottom margin may be useful in case the filters wrap.
### Steps to reproduce

Open the provided plunker.
Click the filter button.
Notice the date-range picker control is not vertically aligned with the other controls and there is a larger gap between the date-range picker control and other controls.
### Plunker

http://plnkr.co/edit/HDAksVSQlpiY5f36CEDt

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.8.0](https://github.com/blackbaud/skyux/releases/tag/v1.8.0)
