### ISSUE TITLE
Add list of supported browsers to documentation

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#837]

**Comment by blackbaud-johnly** [comment]
Here's the list of browsers that we support, as per Paul and Bobby at the planning meeting: IE11; Edge on Windows; the latest Firefox on Windows and Mac; latest Chrome on Windows and Mac; latest Safari on Mac; latest Mobile Safari on IOS; latest Chrome on Android.

**Comment by blackbaud-johnly** [comment]
Incorporated this into the section about consuming SKY UX in the new Learn section for the website.

**Comment by blackbaud-johnly** [comment]
Added as part of the updates with the learn branch. This was part of the PR https://github.com/blackbaud/skyux-docs/pull/59 in the skyux-docs repo.
