### ISSUE TITLE
Code coverage below 100% is not failing the build

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux1#84]
Recently a change was introduced that [dropped our code coverage to under 100%](https://github.com/blackbaud/skyux/issues/83).  This should have caused the build to fail.  I suspect the build still passed because when rounded to a whole number the result was 100%.

**Comment by Blackbaud-BobbyEarl** [comment]
I updated the settings in coveralls.io, so code coverage below 100% will now fail the build.

<img width="253" alt="screen shot 2015-12-01 at 8 46 01 am" src="https://cloud.githubusercontent.com/assets/4612419/11502321/0d0146ba-9808-11e5-8ff9-a84b46e9a7b4.png">
