### ISSUE TITLE
When a Repeater is nested inside of a Pagination control the repeater content is visible on load

### ISSUE THREAD

**Issue by MikeABentley** [blackbaud/skyux1#845]
### Expected behavior

When bb-repeater-item-expanded="false" the repeater content should not be displayed on load
### Actual behavior

If there are enough items in the list to cause pagination the content will be displayed on load.  If there are only a few items, and therefore no pagination, the content is properly hidden on load.
### Steps to reproduce

[Click on this](http://plnkr.co/edit/cR0kwgYYEabkVLekMpMt?p=preview)
### Plunker

http://plnkr.co/edit/cR0kwgYYEabkVLekMpMt?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah the problem here seems to be the fact that in bb-pagination, we're forced to disable animations so that it can measure min height properly. Disabling the animation means that the repeaters are never closed properly. There's probably a workaround using $timeout in your controller code but honestly I would just avoid using the bb-pagination directive and use uib-pagination instead. It doesn't do the crazy min-height checking

**Comment by Blackbaud-PatrickOFriel** [comment]
Here's a workaround if you absolutely need to use `bb-pagination` http://plnkr.co/edit/9YZcrqTNtPRVD9tHN1nM?p=preview. It essentially adds an ng-if around the repeater content. I would still recommend use `uib-pagination` to avoid the wonky min-height calculations that cause this problem.

**Comment by MikeABentley** [comment]
Where is the documentation on the uib version of the pagination control?  I tried just swapping out the directive in my plunker example, but the results were less than desirable.  :/

**Comment by Blackbaud-PatrickOFriel** [comment]
http://angular-ui.github.io/bootstrap/versioned-docs/1.2.5/#/pagination

*Edited to have the correct version

**Comment by MikeABentley** [comment]
Oh, okay.  I thought this was a sky ux directive.  I think I’ll stick with the workaround.  It seems to work for my situation.

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah the bb-pagination directive pretty much just wraps the uib-pagination directive and does some min-height style processing
