### ISSUE TITLE
File dropper is calling bb-file-drop-change before file is selected

### ISSUE THREAD

**Issue by jrdn91** [blackbaud/skyux1#847]
### Expected behavior

I expect the `bb-file-drop-change` function to only get called after the user has either dropped a file it or after the user has clicked it to open the browse menu and selected an file.
### Actual behavior

Dropping a file is working fine, however, when clicking the component to open the systems browse menu it seems to be calling the file dropped function before the user has actually clicked on a file to upload.
### Steps to reproduce

Clicking the component for the first time works fine, the function don't get called until a file is selected. Clicking the component subsequently after the first click calls the function when the browse menu opens.
Interestingly, if you then drop a file on it and then click it again, it goes back to functioning as it should as if it's the first time you've clicked it. It seems to only be doing this after clicking the component at least once and stops doing it after dropping a file.
### Plunker

I've altered the default plunker a little bit to add console logs so you can see this happening in the conole.
http://plnkr.co/edit/1TuFse7vGuTzI8vucZ7E?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.7.6](https://github.com/blackbaud/skyux/releases/tag/v1.7.6)
