### ISSUE TITLE
CSS from blackbaudcdn fails sha384 validation in Firefox 

### ISSUE THREAD

**Issue by Blackbaud-JeffDye** [blackbaud/skyux1#876]
### Expected behavior

CSS/site loads as intended.
### Actual behavior

Site loads without any styles.
### Steps to reproduce

Using latest Firefox (49.0.1, and currently on Windows 7), load any sky site using CSS from the sky.blackbaudcdn.net with the sha384 integrity check. "None of the “sha384” hashes in the integrity attribute match the content of the subresource." is logged in the browser console. 
Removing the integrity and crossorigin attributes allows it to load as intended. The blackbaudcdn javascript passes integrity validation just fine.
### Plunker

http://plnkr.co/edit/qucCz0WmtehcyPgNOHiy?p=preview
This happens in my app too, I can provide a link if needed.

**Comment by Blackbaud-BobbyEarl** [comment]
After some extensive testing, we've found the problem to be a bug in Firefox (versions <52+) where they are incorrectly handling CSS files with BOM (Byte Order Mark). 

https://bug623317.bugzilla.mozilla.org/show_bug.cgi?id=1269241

I've confirmed the bug has been resolved and our current integrity hashes work as expected in Firefox 52 (the current developer edition version).  They currently have Firefox 52 scheduled for release in 2017 Q1.
