### ISSUE TITLE
Grid filter flyout has higher z-index than mobile nav menu

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#88]
If you are viewing a Grid and expand the filter, and then flyout the nav menu on mobile, the filter menu shows above the nav menu.  The mobile nav menu's z-index is inherited from the ombibar.

This issue was introduced due to a recent change in z-index for grid filters.

![image](https://cloud.githubusercontent.com/assets/11888587/11401363/3d1a7e2c-9360-11e5-9eef-cd3155723439.png)

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah didn't see the `$omnibar-zindex` variable. With the change I'm making here, I'm going to move that from _omnibar.scss to the _variables.scss file with the other z-index variables.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.4](https://github.com/blackbaud/skyux/releases/tag/v1.4.4)
