### ISSUE TITLE
Popovers in lists display above list header and omnibar

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#893]
### Expected behavior
When opening a popover inside of a list and then scrolling down, the popover should disappear behind the list and omnibar as it scrolls off the page like the other content does.

### Actual behavior
The popover appears above the list header and omnibar.

### Plunker
http://plnkr.co/edit/DdtFVt1nLIbiemda7BPX?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Note for this: popover z-index=1060 (probably to appear properly when appended to body in a modal?), viewkeeper for toolbar z-index=100, omnibar z-index=1039.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.10.0](https://github.com/blackbaud/skyux/releases/tag/v1.10.0) added the `bb-popover-list` class that can be used with popovers using the `popover-class` attribute.
