### ISSUE TITLE
Document our development process

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#9]
We need to have our development practices documented in case we all get hit by a bus.  This includes our build process, automation, pull request process, etc.

**Comment by Blackbaud-BobbyEarl** [comment]
We need to decide where this information may live.  A few current proposals:
- Enable the blog feature and create a post
- Create an about section and add a process page with this information.

Paul has also documented #90 with a gist.  I think this information is also a good candidate for pulling in similar to the process documentation.  Either a blog post or perhaps create a tutorials section.
