### ISSUE TITLE
Wolverine Bug 691079; Phone field adding unnecessary extra area code to smaller countries

### ISSUE THREAD

**Issue by Blackbaud-SeanLatif** [blackbaud/skyux1#906]
### Expected behavior
Using the Phone field component, selecting the country of Cayman Islands and putting 3453231234 should result in a formatted number of +1 (345) 323-1234.

### Actual behavior
Using the Phone field component, selecting the country of Cayman Islands and putting 3453231234 results in a formatted number of +1345 (345) 323-1234.

### Steps to reproduce
Using the Phone field component, select the country of Cayman Islands and put 3453231234. See the ng-model supplied to the Phone field component is +1345 (345) 323-1234.

### Plunker
[http://plnkr.co/edit/lSgQo7XszqpWEtskgS6A?p=preview](http://plnkr.co/edit/lSgQo7XszqpWEtskgS6A?p=preview)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.9.2](https://github.com/blackbaud/skyux/releases/tag/v1.9.2)
