### ISSUE TITLE
Modal: close icon not floated to the right

### ISSUE THREAD

**Issue by Blackbaud-SpencerMurphy** [blackbaud/skyux1#907]
### Expected behavior
The close button in a modal header should be floated to the right.

### Actual behavior
The close button in a modal header floats to the right if there is a help button with it, but is too far left if it doesn't have one. 

### Steps to reproduce
Open a modal that doesn't have the help button included (the filter button in the plunkr)
Notice the close button isn't floated to the right

### Plunker
http://plnkr.co/edit/mWNh7ZNKuoJoB31x2PiA?p=preview
Filter button shows modal with no help button
Choose columns button shows modal with help button

Doing a little digging, it looks like this has to do with the 'margin-left: auto' style that was applied to the bb-helpbutton class, but not to the close class. This was changed in _modals.scss in https://github.com/blackbaud/skyux/commit/c548a86684d75e26fb153b666210d296915a0fbb. It did look like there'd need to be some conditional logic around when to add it to close though, because the help button gets shifted if the auto margin is on close with a help button.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.9.2](https://github.com/blackbaud/skyux/releases/tag/v1.9.2)
