### ISSUE TITLE
Grid: allow way to specify search placeholder text

### ISSUE THREAD

**Issue by Blackbaud-SpencerMurphy** [blackbaud/skyux1#910]
### Expected behavior
It would be nice to be able to provide placeholder text for the grid search input

### Actual behavior
The placeholder text for search on the grid is always set to the default value. 

Placeholder text is already an option on the search directive, it should be able to be passed down from the grid options.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.10.0](https://github.com/blackbaud/skyux/releases/tag/v1.10.0)
