### ISSUE TITLE
Search: Clear button doesn't disappear after programmatically setting the search text to empty

### ISSUE THREAD

**Issue by Blackbaud-SpencerMurphy** [blackbaud/skyux1#911]
### Expected behavior
If I programmatically set the search text model to empty, the clear button should disappear. As a side note, we are primarily using the search directive as part of the grid directive, so I would expect it to work the same way through the grid search input.

### Actual behavior
I can set the search text to blank, but the clear button still shows up. 

### Steps to reproduce (based on plunkr)
Type something in the search box and hit enter or the search button
Click restore defaults to set the search text to empty
See that the clear button is still there

### Plunker
http://plnkr.co/edit/6HWhNUavKqbBV3VLYqGP?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.10.0](https://github.com/blackbaud/skyux/releases/tag/v1.10.0)
