### ISSUE TITLE
Search: provide a callback for search text being changed

### ISSUE THREAD

**Issue by Blackbaud-SpencerMurphy** [blackbaud/skyux1#917]
### Expected behavior
I'd like some way to be updated with what has been typed in the search field. 

### Actual behavior
The search field text is only accessible through the bb-on-search callback which only fires when the search has been applied or cleared.  

### Steps to reproduce (in plunkr)
1. Type something in the search field and hit enter (or click search icon)
2. See that the list responds to the change
3. Type something else in the search field but don't hit enter (or click search icon)
4. Click the Additional Search Button
5. See that the list did not respond to the new search text

### Plunker
http://plnkr.co/edit/W1Ulbnvge3VHs9KKvsGc?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.10.0](https://github.com/blackbaud/skyux/releases/tag/v1.10.0)
