### ISSUE TITLE
MailTo Links in Tile Dashboard Tiles Open Multiple Tabs (with Chrome Extension)

### ISSUE THREAD

**Issue by Blackbaud-SeanLatif** [blackbaud/skyux1#920]
Please note: This is an issue that is only reproduce (so far) in Chrome when using a Chrome Extension called "MailTo for Gmail" ([click here to download](https://chrome.google.com/webstore/detail/mailto-for-gmail/dgkkmcknielgdhebimdnfahpipajcpjn?hl=en-GB)), which just opens MailTo href's in GMail. This is being filed as an issue because it only happens inside the Tile Dashboard and a client filed it ([bug here](https://tfs.blackbaud.com/tfs/DefaultCollection/Products/_workitems?_a=edit&id=693087)). If this is deemed a non issue by SKY, we'll stick with the stance that we can't address it due to it being related to the extension. This is mainly a "heads up, something could be weird" issue because it only happens inside tiles in the tiles dashboard and nowhere else in RE NXT or other sites.

### Expected behavior
In Chrome, using the Chrome extension "MailTo for Gmail": clicking a link that has a MailTo href opens 1 tab in Gmail to send an email to the clicked email address.

### Actual behavior
In Chrome, using the Chrome extension "MailTo for Gmail": clicking a link that has a MailTo href opens 2 (or more when in an environment)(sometimes 11) tabs in Gmail to send an email to the clicked email address.

### Steps to reproduce
In Chrome, using the Chrome extension, click on a MailTo link inside of a tile inside of a tile dashboard.

### Plunker
Note, again, that [the Chrome extension](https://chrome.google.com/webstore/detail/mailto-for-gmail/dgkkmcknielgdhebimdnfahpipajcpjn?hl=en-GB) is required.
http://plnkr.co/edit/a8NiUmxSvFpS49oEHqR7?p=preview

Let me know if there's anything I can help with.

Notes found during testing: 

In RE NXT, when say 11 tabs were opened, the first tab would have {{email.address}} in the recipient box instead of "blah@blah.com", which all the other tabs had. {{email.address}} is the angular object being passed into those href's in the html.

Also, the number of tabs felt random with each page refresh, but were consistent in between refreshes. So if the link opened 11 tabs, it would continue to open 11 until we refreshed the page. Then it may open 5 tabs consistently until next refresh.

Putting a link outside of the tiles worked fine and putting just a tile (without being in the dashboard) also worked fine. It only occurs for me when the tile is in the tile dashboard.

Last note: Once we would click a "show more" button that would open a modal with all of the emails, clicking any MailTo href would open just 1 tab (as expected) but the recipient would be {{email.address}}

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks for being so thorough @Blackbaud-SeanLatif.  Looking at the extension's support -> problems page, seems others have the same problem on Angular sites.  I doubt there will be anything for us to do. 

Furthermore, I don't believe this extension is even needed to have Chrome open all mailto links in Gmail.  http://blog.hubspot.com/marketing/set-gmail-as-browser-default-email-client-ht#sm.0001qopgjb410dyj10n1gm78pgx9h

**Comment by Blackbaud-SeanLatif** [comment]
Awesome! I think showing that other people are experiencing similar issues will help us say that it's not something we can address but that we have alternatives. Thanks for looking at it though! I don't know if I can mark this closed so I'll just say that this is okay to close.
