### ISSUE TITLE
Search: Provide a way to trigger search

### ISSUE THREAD

**Issue by Blackbaud-SpencerMurphy** [blackbaud/skyux1#927]
### Expected behavior
It'd be great if there was a way to trigger the search functionality in the search input. Right now it's possible to use the value in the search box, but there isn't a good way to trigger the clearing x button show/hide functionality.

### Actual behavior
The only way that the clearing x functionality gets triggered is if you actually click the magnifying glass or hit enter.

### Steps to reproduce (in plunkr)
1. Type something in the search field
2. Click the Additional Search Button
3. See that the list responds to the changes, but there is no clearing x

### Plunker
http://plnkr.co/edit/W1Ulbnvge3VHs9KKvsGc?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.11.0](https://github.com/blackbaud/skyux/releases/tag/v1.11.0)
