### ISSUE TITLE
Checklist: Need a way to customize the "All categories" when using bb-checklist-categories

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux1#929]
### Expected behavior
Ability to customize "All categories" option in the categories dropdown filter to better match the context of the items being filtered.

### Actual behavior
This feature doesn't currently exist.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.11.0](https://github.com/blackbaud/skyux/releases/tag/v1.11.0)
