### ISSUE TITLE
Update color scheme

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#944]
Base palette
Alerts
Labels
Toasts
Text colors
Wizard
Collapsed tile headers

**Comment by Blackbaud-ToddRoberts** [comment]
Color tokens:

https://blackbaudinc.box.com/s/drkakkkkw2y2gi5m5k1kgcdlwn5mhxig

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.16.0-0](https://github.com/blackbaud/skyux/releases/tag/v1.16.0-0)
