### ISSUE TITLE
How to get SKY UX type script libraries with angular JS

### ISSUE THREAD

**Issue by hpatel81** [blackbaud/skyux1#948]
### Expected behavior
We are developing an application using the SKY UX v1.9. We want to utilize the libraries in the type script files (i.e. .ts instead of .js). How can we achieve that?
### Steps to reproduce
Mentioned as above in the question.

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks for filing an issue @hpatel81.  This repo (and version 1.X) of SKY UX is built for use in Angular1 applications.  There is a migration path, which I can help explain if necessary.

I'm assuming however, that you're actually interested in our https://github.com/blackbaud/skyux2 repository.  It's being built for native use in TypeScript and Angular2 applications.

Is that true?

**Comment by Blackbaud-PatrickOFriel** [comment]
Closing due to lack of response
