### ISSUE TITLE
Sugestion: Use SweetAlerts to replace window.alert / window.confirm

### ISSUE THREAD

**Issue by jrdn91** [blackbaud/skyux1#949]
Just a suggestion, I have really liked this library for its visual style and ease of use.

I am about to drop it into our project for success alerts because having the green toast has worried us that our users won't see it, and having a full modal popup doesn't really make a lot of sense.

There is a nice angular implementation of it here...

https://github.com/oitozero/ngSweetAlert

And although it slips a little outside the Sky UX theme it could be restyled easily to match more closely.

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks for the suggestion @Jordan4jc!  We currently have #883 to track a similar request.  I don't see us overriding the `alert()` and `confirm()` methods.  We will most likely provide the visual + api changes necessary to our current modal to support it.
