### ISSUE TITLE
bbAutonumeric does not work correctly if the ng-model value starts out as undefined

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#95]
Having a ng-value that starts out as undefined causes the number to not show:

http://plnkr.co/edit/OTHZWtFrHsbiz18139Kg?p=preview

**Comment by Blackbaud-PaulCrowder** [comment]
In [v1.4.5](https://github.com/blackbaud/skyux/releases/tag/v1.4.5)
