### ISSUE TITLE
Full screen modal, opened on top of a full screen modal, not working as intended on scroll.

### ISSUE THREAD

**Issue by RARowe** [blackbaud/skyux1#965]
### Expected behavior
Theoretically, I should be able to have any number of full screen modals that open on top of each other.

### Actual behavior
If I have a full screen modal that has enough content in it (the plunker will make this more clear), and open another full screen modal on top of it, as I scroll, the top-most full screen modal scrolls away, and I can see the modal underneath (or white screen).

### Steps to reproduce
Steps to reproduce in plunker:
1. Open the full screen modal
2. Notice that I have a lot of scroll-able content on the modal
3. Use the provided button to open the second modal on top of it
4. Proceed to start scrolling down in new modal
5. Notice that the new modal floats away and shows the drop screen underneath 

Let me know if you have any question!
### Plunker
http://plnkr.co/edit/dyuxUMV4JvMREZ4cDkS7?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.13.0](https://github.com/blackbaud/skyux/releases/tag/v1.13.0)

**Comment by RARowe** [comment]
Hey Patrick,

I'm still seeing a variation of this bug in Sky v1.13.0. Though my second modal is not flying away, as it was previously, the body of the full screen modal opened on top of the first full screen modal fits to the size of the first modal, creating unnecessary scrolling.

See: http://plnkr.co/edit/oQn0Q2rJjfivDSQMEG9o?p=preview

If need be I'll open up a new bug for this issue, depending on your opinion.

**Comment by Blackbaud-PatrickOFriel** [comment]
Let me take a look this afternoon or tomorrow and I'll let you know

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah, @RARowe I'll go ahead and reopen this. Looks like there's a `display: block` that's set directly on the modal as an inline style that's overriding my `display: none` for the underneath modal. I'll see if I can find a solution. 

As a fix for your application (and maybe what I end up doing if I can't find something better) you can apply this css rule: 
.bb-modal-fullpage + .bb-modal-fullpage {
  display: none !important;
}

**Comment by Blackbaud-PatrickOFriel** [comment]
One more try @RARowe, in [v1.13.1](https://github.com/blackbaud/skyux/releases/tag/v1.13.1)
