### ISSUE TITLE
'Select field' component label runs over background in IE 11 & 10

### ISSUE THREAD

**Issue by Blackbaud-TonyKnopp** [blackbaud/skyux1#968]
### Expected behavior
Label fits within the background of the control.

### Actual behavior
Label is running over the background of the control.

### Steps to reproduce
Visit https://skyux.developer.blackbaud.com/components/selectfield/ in Internet explorer

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.13.0](https://github.com/blackbaud/skyux/releases/tag/v1.13.0)
