### ISSUE TITLE
Add current version of Font Awesome to our docs

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux1#970]
It's been suggested we add the current version of Font Awesome we include on our icons page.  http://skyux.developer.blackbaud.com/design/icons/

**Comment by blackbaud-johnly** [comment]
Updated topic to call out FontAwesome version and created PR #67 in the skyux-docs repo.

**Comment by Blackbaud-BobbyEarl** [comment]
Fixed in https://github.com/blackbaud/skyux-docs/pull/67
