### ISSUE TITLE
Manually created Tabsets show double tabs when opened at SM and XS breakpoints

### ISSUE THREAD

**Issue by RARowe** [blackbaud/skyux1#972]
### Expected behavior
I should be able to manually create tabsets that contain HTML.

### Actual behavior
When I manually create a small number of tabs directly in the HTML (i.e. not using an `ng-repeat` to generate tabs), and the window containing the tabs opens at a SM or XS breakpoint, I see the dropdown box for the tablist, in addition to the tabs themselves. If I resize the window to a MD/LG breakpoint, and then come back to the smaller breakpoint, the issue is fixed. Additionally if I open the window at a MD or LG breakpoint and size down, the issue does not show up. The issue I'm describing looks like this:

![capture](https://cloud.githubusercontent.com/assets/9261752/21900554/395367ec-d8c2-11e6-826a-7f55996ef035.PNG)

### Steps to reproduce

1. Manually create a tabset without using an `ng-repeat` (I have already done this in the attached plunker)
2. "Stop" the plunker from running
3. Change the preview window size to a SM/XS breakpoint
4. "Run" the plunker
5. The bug should be recreated
6. If you have any questions, please let me know!

### Plunker

http://plnkr.co/edit/N4AB2GR0cIvV0Yhl9j6y?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.13.0](https://github.com/blackbaud/skyux/releases/tag/v1.13.0)
