### ISSUE TITLE
Grid: column size increasing when navigating between pages with and without scrollbar

### ISSUE THREAD

**Issue by Blackbaud-CaitlinEstrella** [blackbaud/skyux1#980]
### Expected behavior
When navigating between pages in a grid the column sizes should stay the same.

### Actual behavior
When navigating between a page in a grid with a vertical scrollbar and one without a scrollbar the column sizes in the page with a scrollbar increases.

### Steps to reproduce
This only happens on Windows machines.

In the plunker below there is a grid with a lot of records on page 1 and a smaller amount on page 2. Make sure that there is a scrollbar on page 1 and there is not a scrollbar on page 2.

Navigate to page 2.
Navigate back to page 1. Note that the first 2 columns are slightly larger.
Navigate back to page 2. Note that the columns are the correct size.

Repeat several times to see the columns on page 1 continue to increase.

### Plunker
http://plnkr.co/edit/HIrI342UB0P404S0qfwB?p=preview

**Comment by Blackbaud-PaulCrowder** [comment]
When you say this only happens on Windows machines, do you mean it only happens in IE or does it happen in every supported browser on Windows?

**Comment by Blackbaud-PatrickOFriel** [comment]
Just glancing at the plunker, I think it would occur on any browser on Windows machines because their scrollbar takes up space in the window. I'll have to look a little deeper to know for sure

**Comment by Blackbaud-CaitlinEstrella** [comment]
I have tried on Chrome, IE, and Firefox and it is happening on all of them.

**Comment by Blackbaud-PatrickOFriel** [comment]
Investigated further, found that this error occurs when you have an extended column (the last column is stretched to fit the remaining area in the grid). If the grid width decreases (if a scrollbar appears), and then increases (scrollbar disappears), and then decreases (scrollbar reappears), the last column was calculating this change incorrectly and kept shrinking more and more each time the scrollbar disappeared. This change fixes that error. Now the columns will only adjust enough for the scrollbar change and it will not continue to shrink. In [v1.13.2](https://github.com/blackbaud/skyux/releases/tag/v1.13.2).
