### ISSUE TITLE
Upgrade to Angular 1.6 to address security flaw

### ISSUE THREAD

**Issue by Blackbaud-SpencerMurphy** [blackbaud/skyux1#995]
The OWASP vulnerability scan that is run on our product revealed that there were several vulnerabilities called Client Side Template Injection vulnerabilities. In the context of an app using Angular, any user input that is dynamically displayed inside of an ng-app context will be evaluated by Angular, meaning that anything not escaping curly braces or inside an element with ng-non-bindable on it that contains the double curly brace syntax will be executed (for example "Test {{2 + 2}}" would render as "Test 4" on the page). While this is a nuisance, it becomes a real problem when someone injects harmful javascript into an angular template. Directly throwing javascript inside the template doesn't actually execute it, but there are ways to include html escaped JS code and execute it using the Angular Sandbox. This affects all versions of AngularJS 1.5 and lower, but in 1.6 they removed the Angular Sandbox that was providing the way to launch malicious JS code. Here is an article detailing this out with examples of ways to inject malicious code: http://blog.portswigger.net/2016/01/xss-without-html-client-side-template.html. While this may not affect apps built from the ground up using only Sky and Angular for handling displaying all user input, apps that are using a mix of sky/angular code with existing pages (in our case lots of old jsp pages) would be potentially (and probably already) vulnerable. 

Here's a simple example showing the injection in action. This isn't a true example since it's just in the html of the page already without showing it being put in by another existing framework, but it shows the angular code executing an alert. http://plnkr.co/edit/CBPYVQxnu48LQqtYINBw?p=preview

I attempted to pull down the sky code and upgrade it myself, but ran into several issues that I wasn't confident in how to address. I'd have no problem sharing anything I've researched around this if it would help determine how or when this would be feasible to do. If there are any questions around this at all, don't hesitate to reach out to me about them.

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-SpencerMurphy, what kind of issues did you run into while upgrading, just so I can try to estimate the effort level of us taking this on.

**Comment by Blackbaud-SpencerMurphy** [comment]
It's been a few weeks since I tried (I've been busy with other things and was trying to see if we could get around it without needing the update), so I can't remember exactly what the issues were. I first tried just updating the angular version and nothing else and that resulted in over 100 of the unit tests to fail. I then tried updating some of the other libraries with angular dependencies (like animate, messages, touch, bootstrap) and that got the number of failures down, but not down to a handful. I don't remember how many were leftover, but I think it was still above 50. Many of those were probably the same issue or a smaller set of repeated issues, I just ran out of the time I had dedicated to it to dig deeper especially since I wasn't positive I was doing the right things.

**Comment by Blackbaud-PatrickOFriel** [comment]
Gotcha, thanks

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-SpencerMurphy we have a prerelease available with the angularjs upgrade in [v1.14.0-0](https://github.com/blackbaud/skyux/releases/tag/v1.14.0-0). Take a look when you get a chance.

**Comment by Blackbaud-PatrickOFriel** [comment]
In v1.14.0
