### ISSUE TITLE
Sectioned form visual cleanup

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#996]
Regular modals have top padding built into the content area. Sectioned form content area should have standard $margin or $padding (10px) top margin or padding as well to avoid having form content butting up against the top of the modal. 

Save button has 10px too much left margin - it looks like the hidden "Show sections" button is triggering the modal-footer button spacing. 

Navigation chevrons are not aligned properly at small viewports in Firefox.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.13.6](https://github.com/blackbaud/skyux/releases/tag/v1.13.6)
