### ISSUE TITLE
Grid Load More button not visible in FireFox in some scenarios

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [blackbaud/skyux1#997]
### Expected behavior
When the grid load more button is available, it should be properly visible so the user can interact with it.

### Actual behavior
When the grid is inside of a tab that uses the tab-scroll functionality, the load more button is covered up by the scroll to top button in Firefox.  This seems to be related to ViewKeeper not working properly.  Its possibly due to the tab-scroll impacting when the view keeper element is ready to be used?

### Steps to reproduce
See plunker in Firefox.  Note that it works in Chrome.  It also works in Firefox is the bb-tab-scroll directive is removed.

**NOTE This issue was filed from a client who uses Firefox and is unable to load more records on large lists in RE NXT.**

### Plunker
http://plnkr.co/edit/qLg3Cmxx0hgNwq5tZRVY

**Comment by Blackbaud-PatrickOFriel** [comment]
We recommend using the infinite scroll functionality rather than the load more button to give users a better experience in general, it also seems to not suffer from the same problem here http://plnkr.co/edit/GubqXYVZJ8cuSsuk3fd2?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
I'll go ahead and close this, but let me know if using infinite scroll doesn't work and I'll reopen

**Comment by ghost** [comment]
We have a scenario in which there are two grids on the same page, so infinite scroll isn't a great solution... would it be possible to get this picked up at some point?  We are doing this for an internal supportal page so not a super pressing issue, but would be nice to have

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-ChrisBellande if you have multiple grids on one page, I wouldn't recommend having any sort of vertical loading paradigm. I would go with numbered pagination instead
